### ISSUE TITLE
[Question] External Module Support

### ISSUE THREAD

**Issue by akhilkedia** [Samsung/iotjs#1010]
Hi!

We need a feature for a project that does not make sense as part of the IoTjs trunk (follow http redirects, similar to [here](https://github.com/olalonde/follow-redirects) ). 
I can see in [module.js](https://github.com/Samsung/iotjs/blob/master/src/js/module.js) right now IoTjs does support external modules to some extent, and in my testing adding external modules by keeping them in a `iotjs_modules` folder does work.
Is support for External Modules something that will remain a part of IoTjs going forward? If yes then we can create the functionality we need as an External Module, and distribute it via some mechanism say `npm`?

**Comment by akhilkedia** [comment]
I found the documentation for this here [https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-Module.md](https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-Module.md). It is clear to me that yes, IoTjs does indeed support "external modules" places in `iotjs_modules` folder, so I will go ahead and use it.

**Comment by yichoi** [comment]
Sorry for late response however I am very happy that you have found the solution. Thanks
