### ISSUE TITLE
Tizen RT Platform defects

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1039]
## Tizen RT Platform defects

The following table shows TizenRT platform issues resolved with our internal workaround. 

Defect Name | IoT.js Temporary Patch | TizenRT Github
------------ | ------------- | ------------- | 
Romfs patch for artik053 | https://github.com/Samsung/iotjs/pull/1037 | https://github.com/Samsung/TizenRT/issues/272

**Comment by kolipka** [comment]
There is another issue:
https://github.com/Samsung/TizenRT/issues/320. I will add reference to temporary fix when it will be ready.

**Comment by daeyeon** [comment]
- Configuration limitations of TizenRT: (https://github.com/Samsung/TizenRT/issues/290, https://github.com/Samsung/TizenRT/issues/196)
- GDB debugger fails to connect with Tizen RT Artik 053 (https://github.com/Samsung/TizenRT/issues/316)
- SPI missing features at Tizen RT (https://github.com/Samsung/TizenRT/issues/202)
- Missing checks for compilation errors (https://github.com/Samsung/TizenRT/issues/195)
- Tizen RT fails to support relative paths (https://github.com/Samsung/TizenRT/issues/320)

**Comment by kolipka** [comment]
OK, this one should solve another net problems:
https://github.com/Samsung/TizenRT/issues/425

**Comment by kolipka** [comment]
And another one LWIP issue:
https://github.com/Samsung/TizenRT/issues/427
With fix described there  test-net-bind-twice.js works like a charm. Results are:
```
finish all tests
PASS : 85
FAIL : 0
TIMEOUT : 0
SKIP : 37
```

**Comment by daeyeon** [comment]
This issue is for tracking major issues blocking IoT.js Tizen RT porting. IoT.js on Tizen RT has been verified with 100% test case successes. Please track each issue itself if needed.
