### ISSUE TITLE
setTimeout blocks nextTick methods.

### ISSUE THREAD

**Issue by KonradNowicki** [Samsung/iotjs#1047]
Method setTimeout  appears to block other functions inserted using nextTick.

```javascript
process.nextTick(function(){ // (1)
    var value = 0;
    process.nextTick(function () { // (2)
      console.log(1);
      value = 1;
    });

    process.nextTick(function () { // (3)
      console.log(2);
      value = 2;
    });

    setTimeout(function () { // (4)

      if (value !== 2) { 
        throw "Problem!";
      }
    }, 2000);
});
```

No console logs appear. Only exception is thrown. Without (1) nextTick code runs without problems.

My expectation is:
- (1) will be added to queue
- (1) will be executed
- (2) will be added to queue
- (3) will be added to queue
- (4) will be added to queue
- (2) will be executed
- (3) will be executed
- (4) will be executed after 2s
- value should be 2

 
OS: Linux

**Comment by yichoi** [comment]
closing since 1060 landed
