### ISSUE TITLE
Nominating Robert Sipka(@robertsipka) to become an IoT.js committer

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#1052]
I would like to nominate Robert Sipka(@robertsipka) to become an IoT.js committer.

Here are merged PRs:

- Remove redundant type validator (#1001)
- Add a more secure type validator to SPI (#985)
- Improve type validator in PWM module (#993)
- Add a more secure type validator to TCP (#977)
- Add a more secure type validator to PWM (#984)
- Fix socket destroy in case of no connection (#955)
- Fix error handling in `server.listen` function (#927)
- Fix a relative link in IoT.js-API-reference (#923)
- Update the stm32f4dis documentation (#921)
- Update UART documentation (#916)
- Update the documentation of the SPI module (#908)
- Small fixes for the documentation of the Events and Net module (#906)
- Update the documentation of the Events module (#900)
- Update the documentation of the Net module (#886)
- Use absolute path for the file system resources in tests. (#823)
- Add `setjmp` and `longjmp` functions for stm32f4-nuttx target (#767)
- Update README.md in stm32f4-nuttx target. (#765)
- Update JerryScript submodule (#661)

**Comment by yichoi** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by daeyeon** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by yichoi** [comment]
Congratulations!
