### ISSUE TITLE
Nominating Roland Takacs(@rtakacs) to become an IoT.js committer

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#1053]
I would like to nominate Roland Takacs(@rtakacs) to become an IoT.js committer.

Here are merged PRs:

- Add test result information to the README.md (#1020)
- Update the testsets.json file (#968)
- Update the testsets.json file (#964)
- Use AF_INET by default on NuttX when no address family specified. (#871)
- Rename test_events_emit_error.js to test_events_assert_emit_error.js in run_pass folder (#867)
- Rename test_events_uncaught_error.js to test_events_emit_error.js in run_fail folder (#863)
- Refactor issue-266.js testfile (#769)
- Refactor testsuite to not use parent directory hard-link in relative paths. (#753)
- Refactor testrunner to use JSON as test descriptor. (#669)
- Update JerryScript submodule (#613)
- Correct wrong urls in README.md (#606)
- Add exception handling for Python's 'submodule' methods (#594)
- Use JSON.stringify to dump error message (#592)
- Fix Buffer.byteLength() to return the valid byte length (#593)
- Update zlib dependency to 1.2.10 (#591)

**Comment by yichoi** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by daeyeon** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by yichoi** [comment]
Congratulations!
