### ISSUE TITLE
Nominating Imre Kiss(@knightburton) to become an IoT.js committer

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#1054]
I would like to nominate Imre Kiss(@knightburton) to become an IoT.js committer.

Here are merged PRs:

- Improve the test coverage. (#706)
- Improve util coverage. (#732)
- Fix the coverage measure script. (#752)
- Fix dns module test. (#778)
- Improve the timers module coverage. (#779)
- [Code coverage] Test the double response in http. (#830)
- [Code coverage] Cover the http status codes. (#831)
- [Code coverage] Improve the http client module coverage. (#832)
- [Code coverage] Improve the http module coverage. (#833)
- [Code coverage] Improve the coverage of stream_readable.js (#838)
- Add a more secure type validator to UDP module based on #911 (#979)
- Add a more secure type validator to UART module based on #911 (#990)
- Fix UDP module build error. (#992)

**Comment by yichoi** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by daeyeon** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by yichoi** [comment]
Congratulations!
