### ISSUE TITLE
Nominating Haesik Jun (@haesik) to become an IoT.js committer

### ISSUE THREAD

**Issue by zherczeg** [Samsung/iotjs#1056]
I would like to nominate Haesik Jun (@haesik) to become an IoT.js committer. The list of his landed patches follows:

Romfs patch for artik053 (#1037)
Delete old and duplicated samples (#1036)
Add config files for TizenRT/Artik053 (#1025)
Fix build error on Artik053 board (#1016)
Change the iotjs execution methods on TizenRT (#755)
Update http-parser submodule (#751)
Add iotjs command on TizenRT (#745)
Fix build configuration for TizenRT (#742)
Delete expired information of Build-for-NuttX.md (#389)
Changing file(Build-for-NuttX-(new).md) permission(755->644) (#384)
update docs/Build-for-NuttX-(new).md with latest wiki-page (#380)

**Comment by yichoi** [comment]
+1

**Comment by daeyeon** [comment]
+1

**Comment by glistening** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by yichoi** [comment]
Congratulations!
