### ISSUE TITLE
Incorrect parsing of regex ended by Unicode characters range

### ISSUE THREAD

**Issue by jgasiewski** [Samsung/iotjs#1057]
For this test Node js and IoT js results of regex test diverge:
`var regexps = [ /^[\u0061-\u007a]+$/, /^[a-z]+$/, /[\u0061-\u007a]+$/, /^[\u0061-\u007a]+/ ];
regexps.forEach(function(elem) {console.log(elem.test('asdf'));});`
Expected result (tested on Node js): 4x true
Result on IoT js:  false, true, false, true

**Comment by LaszloLango** [comment]
This is related to the JS engine (JerryScript). I'll check it later.

**Comment by yichoi** [comment]
jerryscript-project/jerryscript#1927 and #1061 landed
