### ISSUE TITLE
Random travis-ci test fails

### ISSUE THREAD

**Issue by tosyu** [Samsung/iotjs#1059]
Hello

I have a problem with TravisCI tests :scream:  Sometime it raindomly fails on asserts spilling out errors in valgrind environment. Sometimes it fails on coverity, sometimes it fails on host-linux tests. The solution is to force restart the tests hoping that the next run will pass :confused: 

Example https://travis-ci.org/Samsung/iotjs/builds/254446216?utm_source=github_status&utm_medium=notification

IMHO this error has nothing to do with the PR :cry:

**Comment by tadziopazur** [comment]
I have seen this behavior by Travis -- seemingly irrelevant tests fail at uv error handling.
Sometimes they fail directly at timeout handling (net tests IIRC).

I think the real cause is the invalid handling of timeouts that are due to underpowered Travis worker instances.

**Comment by pmarcinkiew** [comment]
Today it happen two times already for me. I just change commit message and trigger Travis to get 100% pass. It was test_net_2 two times. In my opinion it is unstable. We should disable it and investigate it separately. It is not efficient to debug some network instability during each pull request.

**Comment by daeyeon** [comment]
No further update for a long time. Some tests seriously flaky on Travis are now skipped. https://github.com/Samsung/iotjs/blob/master/test/testsets.json
