### ISSUE TITLE
Require recursive load.

### ISSUE THREAD

**Issue by KonradNowicki** [Samsung/iotjs#1077]
Hello,

I have a problem with modules with the same name that loads itself recursively. There are 2 situations described below.

1. Core module vs local module
I have test file ./test/gpio.js
```javascript 
var gpio = require('gpio');
```
When run: script loads itself until recursion limit is reached.
```bash
iotjs ./test/gpio.js
```
I would expect that require will load gpio core module not local one, if I would want to load local module I would use: ` require('./gpio.js');`

In docs there are native first so I guess there must be some caching problem?

2. User module vs local module
I have create similar setup with user module:
* iotjs_modules/my-module/index.js
* test/my-module.js

In this case behavior is as documented in your docs. But in this situation I have no way of referencing  user modules ('iotjs_modules') from files of the same name.

In [Node.JS docs ](https://nodejs.org/api/modules.html#modules_all_together) there is described algorithm. When require path start from '/ ', './' or '../' then it tries to load local script otherwise it tries core module and then user modules.

This may be enhancement proposal.

Regards

**Comment by LaszloLango** [comment]
I'll check this issue. Thanks for reporting.

**Comment by daeyeon** [comment]
@KonradNowicki I simply tested the issue 1, but my observation with the latest was different.

./test/console.js
```js
var con = require('console');
con.log('local console');
```

Result:
> iotjs ./test/console.js
> local console

When run: the local script doesn't load itself. Can you clarify if I correctly reproduce the issue you raised?

**Comment by LaszloLango** [comment]
@daeyeon it the native module is built than it works as expected. This happens when you try to load the gpio module when it is not built. At least that was my observation and that's what I fixed in #1094

**Comment by KonradNowicki** [comment]
@daeyeon I guess I have used iotjs version without gpio for testing (as @LaszloLango  mentioned). Sorry for that.

**Comment by daeyeon** [comment]
@KonradNowicki @LaszloLango Thanks for your clarification.
