### ISSUE TITLE
Http request - server unreachable bug

### ISSUE THREAD

**Issue by jgasiewski** [Samsung/iotjs#1078]
Hello,
I have a problem with http request case when server is unreachable. 
Running test code bellow, doesn't return any error/exception when request is sent to unreachable host.
```
var http = require('http');

var request = http.request({
  host: 'localhost',
  port: 5000,
  path: '/',
  method: 'GET'
}, function (response) {
  response.on('data', function (chunk) {});
  response.on('end', function (chunk) {
    console.log('RESPONSE');
  });
  response.on('error', function (error) {
    console.log('RESPONSE', error);
  });
});
request.on('error', function (error) {
  console.log('REQUEST', error);
});
request.end();
```
Commenting the last line, hides(removes?) bug and example works properly. However, if I understand correctly API reference, this line is mandatory.

**Comment by akhilkedia** [comment]
This seems to be a synchronysation issue - calling request.end() after a 1 second timeout does give the error callback.
