### ISSUE TITLE
Complete document: API References

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#111]
https://github.com/Samsung/iotjs/wiki/IoT.js%20API%20Reference

* Basic modules
 * [x] assert (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Assert)
 * [x] buffer (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Buffer)
 * [x] dns (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-DNS)
 * [x] events (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Events)
 * [ ] fs
 * [x] gpio  (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-GPIO)
 * [x] http
 * [ ] module
 * [x] net (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Net)
 * [ ] process
 * [ ] stream
 * [x] timers (https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Timers)

**Comment by wuxj2015** [comment]
@ILyoan 
Excuse me, have you support Extended API CoAP? 
If you did, how can I get it and use it ?

**Comment by glistening** [comment]
As of this writing, the missing documentations for basic modules exist (e.g., fs, module, process, stream). So I think we could close this issue. 

@wuxj2015 
We don't support Extended API CoAP yet.

**Comment by yichoi** [comment]
closing. let's update each APIs as updated
