### ISSUE TITLE
RPi3 Installation guide broken link

### ISSUE THREAD

**Issue by shulgaalexey** [Samsung/iotjs#1116]
The link https://git.tizen.org/cgit/platform/kernel/linux-rpi3/plain/scripts/sd_fusing_rpi3.sh?h=tizen seems inaccessible

Context: the Chapter 2 of the Guide https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-RPi3-Tizen.md

**Comment by yichoi** [comment]
fixed by #1118
