### ISSUE TITLE
Artik board is missing in process variables

### ISSUE THREAD

**Issue by tosyu** [Samsung/iotjs#1117]
The list for the `board` variable in the documentation is not complete

> process.iotjs.board - specifies the device type on which the IoT.js is running currently. For instance 'STM32F4DIS', 'RP2', or 'unknown'

How can I know If I am running on Artik board?

**Comment by daeyeon** [comment]
It isn't a result from board detection in realtime. The build option given for `--target-board` is stored for `process.iotjs.board`. So, clearily speaking, it indicates which board the IoT.js was made for. I will update the document.

**Comment by tosyu** [comment]
> The build option given for` --target-board` is stored for process.iotjs.board
@daeyeon this is not true, when passing the option --target-board the option is **rpi2** while the variable holds **RP2** which suggests there is no connection between `--target-board` param and `process.iotjs.board` variable

**Comment by daeyeon** [comment]
Oh, there was a mistake in writing my meaning. Finding where `TARGET_BOARD` is defined might be a clue to know the cause of this problem. https://github.com/Samsung/iotjs/blob/master/src/modules/iotjs_module_process.c#L236

**Comment by daeyeon** [comment]
no further update for this issue. please reopen issue once you find out the way to properly check `board`.
