### ISSUE TITLE
Problematic exception handling in callbacks

### ISSUE THREAD

**Issue by tosyu** [Samsung/iotjs#1121]
The following code in `iotjs_binding.c`

```c
iotjs_jval_t iotjs_jhelper_call_ok(const iotjs_jval_t* jfunc,
                                   const iotjs_jval_t* jthis,
                                   const iotjs_jargs_t* jargs) {
  bool throws;
  iotjs_jval_t jres = iotjs_jhelper_call(jfunc, jthis, jargs, &throws);
  IOTJS_ASSERT(!throws);
  return jres;
}
```

Doesn't do anything when exception is thrown in release build, but on debug build it terminates the whole process. Which can fail automated tests (the whole test runner) if exception is thrown in callbacks, example:

```javascript
var onData = function (data) {
        console.log('uart: received ' + data);
        assert(data == DATA, 'uart: response was ok');
        console.log('uart: closing');
        res.closeSync();
    };
```

This code will terminate the whole iotjs process with message:

```bash
/home/tosyu/Projects/iotjs/src/iotjs_binding.c:530: Assertion '!throws' failed.
```

Two bugs I see here:
1. Inconsistency, debug and release versions differ a lot with handling of callbacks
2. The exception is not propagated, which means that test runner harness will not catch if the assertion fails

The current dirty-quick-fix for me is to write

```javascript
var onData = function (data) {
        console.log('uart: received ' + data);
        setTimeout(function () { // @fixme: onData caller fails test when exception thrown
            assert(data == DATA, 'uart: response was ok');
        }, 0);
        console.log('uart: closing');
        res.closeSync();
    };
```

Which is not the most best solution for the problem

**Comment by DanielBallaSZTE** [comment]
I think this issue can be closed, as `iotjs_jhelper_call_ok` is not present anymore in the code.
