### ISSUE TITLE
Precommit script produces broken STM32/Nuttx port

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#1126]
Recent iotjs repository (aa96e33310, Wed Aug 16 03:25:04 2017) built for STM32F4Discovery does not support serial console over USB (CN5).
It does not support USART1 nor USART2.

Not sure if it boots at all, nothing indicates it does.

On the other hand, upstream nuttx, with no IOTSJ and attached configuration works like a charm (well, after an include is added and the project actually builds).

https://github.com/Samsung/iotjs/pull/1125

How is Nuttx port with IoT.js supposed to be built and run on STM32F4 Discovery1?

Tests appear to be generating reports, so I guess the builds are generated and do run on target.
https://samsung.github.io/iotjs-test-results/

**Comment by bzsolt** [comment]
@tadziopazur  based on [this guide](https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-STM32F4-NuttX.md) I can build the current IoT.js master (1f29e9f) from the beginning to stm32f4/NuttX, I can login to the board via `minicom`, can run tests, so everything seems to be fine.

I've tried to create a nuttx binary with the `precommit.py --test=nuttx`, it's also works, but I couldn't flash this binary onto the board, I guess further configuration is required, but as I know this way is intended to testing the build itself for NuttX, not for testing.

**Comment by tadziopazur** [comment]
Oh, that is disconcerting, I'd much prefer that tests actually run what is build in automated process.
Alas, the instruction is unclear and didn't allow me to obtain a workable build.

So far I have had issues building and running IoT.js on STM32F4, as it does not build/boot with just random configuration. In my case, whatever I did, the build wouldn't boot with either:
 - FPU enabled
 - ethernet enabled
 - SDIO (=mmc) enabled

To add insult to injury, IoT.js has hardcoded FPU support for nuttx target. Is there a canonical, _working_ nuttx configuration for the IoT.js? Could you please share that config file?

**Comment by tadziopazur** [comment]
All great and exciting, but there is three pages worth of manual changes applied to the mentioned config listed in the guide, so the file you mentioned is not the answer to my question.
Also, applying those changes is error-prone and AFAIR cannot be done in a single pass.
Thus I ask for the ACTUAL configuration (config the nuttx has been built with) file.
Can you dig it up please?

**Comment by bzsolt** [comment]
I've used this config file without any manual configuration and it worked for me.

**Comment by tadziopazur** [comment]
For me it didn't.
Nevermind, I crafted a config that works and supports most of what we need (that pesky ethernet causes firmware to fail at boot).
It can be found in the PR: https://github.com/Samsung/iotjs/pull/1138

**Comment by yichoi** [comment]
reopen along with #1138.

**Comment by daeyeon** [comment]
https://github.com/Samsung/iotjs/pull/1138 is closed.
