### ISSUE TITLE
Tests: iotjs should not be test runner

### ISSUE THREAD

**Issue by tosyu** [Samsung/iotjs#1132]
Using IoT.js for running test harness is prone to errors. When testing uart I have encountered problems with uart waiting for the response and hanging the whole test process, as there is no tool to kill an "async job" in the `iotjs` platform. 

This would be easy to fix if IoT.js could spawn new instances of itself and if one would hang, the master process could kill it after a period of time. Having a timer that just spills out "TIMEOUT" message in the log does not cut it :cry: 

`iotjs` can be (and has to be, as it's the only option for remote testing) used to run a test file and return results, but in my opinion, it should not be used as a harness that manages the tests.

`check_test.js` runner should be refactored to run with `nodejs` and execute `iotjs` processes for each test file or `jasmine` (or other) automated test framework should be used.

**Comment by daeyeon** [comment]
The same was on https://github.com/Samsung/iotjs/issues/1073. We're using remote-testrunner to avoid the issues you raised.

For instance, it runs tests on stm32f4dis:

- For timeout: https://github.com/rtakacs/remote-testrunner/blob/serial_com/API/device/stm32f4dis.py#L111
- For clean test, it even reboots the board per a test.
https://github.com/rtakacs/remote-testrunner/blob/serial_com/API/device/stm32f4dis.py#L128
- `check_test.js` is not used.

**Comment by tosyu** [comment]
> even reboots the board per a test

IMHO This should not be done per test, only if the board fails. As this prevents detecting memory problems

**Comment by rtakacs** [comment]
As I checked on stm32f4-nuttx, when the board is not restarted at every tests, it could cause random fails on tests. This is the reason why the remote-testrunner reboots the device per test (to ensure a clean environment).

**Comment by tosyu** [comment]
Ok,

@rtakacs @daeyeon so I should make my changes in #1127 also in remote-test-runner, since `check_test.js` is not used, right?

**Comment by daeyeon** [comment]
@tosyu No. We need to first know why this repeated misunderstanding happens. We need to clarify requirements, due date and priorities SRPOL understands again. Please contact us internally with them.

**Comment by daeyeon** [comment]
Now, https://github.com/Samsung/js-remote-test is available for this matter.
