### ISSUE TITLE
Broken links in Build-for-RPi3-Tizen doc

### ISSUE THREAD

**Issue by shulgaalexey** [Samsung/iotjs#1178]
Hi @sumin-lim 

Pls check hyperlinks in **Downloading TizenIoT Core Image for RPi3** section of docs https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-RPi3-Tizen.md#downloading-tizeniot-core-image-for-rpi3 
master branch

Seems both are out of date

Thanks

**Comment by glistening** [comment]
@shulgaalexey Thank you for informing us. I've asked @sumin-lim. I hope http://download.tizen.org/snapshots/tizen/unified/latest/images/standard/iot-headless-2parts-armv7l-rpi3/ and http://download.tizen.org/snapshots/tizen/unified/latest/images/standard/iot-boot-arm64-rpi3/ work.

**Comment by daeyeon** [comment]
It looks fixed. 👍
