### ISSUE TITLE
measuring coverage on rpi2

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1197]
`Error: ERR_REF_COUNT_LIMIT` occurs while check_test.js runs under `measure_coverage.sh` on rpi2. 

In the above observation, I modified the following items in measure_coverage.sh :
- check_architecture is blocked.
- use nvm install 4.0.0

**Comment by rtakacs** [comment]
@daeyeon I also noticed that you wrote (#1196)

**Comment by daeyeon** [comment]
This is fixed with https://github.com/Samsung/iotjs/pull/1205.
