### ISSUE TITLE
Replace type checker calls

### ISSUE THREAD

**Issue by tkeri** [Samsung/iotjs#1198]
@hs0225 I think you get me wrong there: https://github.com/Samsung/iotjs/pull/1158

The function implementations weren't deleted (util.js). These were replaced with JavaScript
comparison operator in other JavaScript files.. I think it's a useful patch, because we can reduce the memory with this.

**Comment by tkeri** [comment]
**Tester: freya, build: release arm-rpi2 4b665d4**
===================
| testfile                                   | total       | peak        |
|--------------------------------------------|-------------|-------------|
|                                            | diff / byte | diff / byte |
||||
| run_pass/test_process_cwd.js               |             |             |
| Jerry Heapsize: 256                        | +29         | +53         |     
| run_pass/test_events_assert_emit_error.js  |             |             |
| Jerry Heapsize: 256                        | +29         | +37         |    
| run_pass/test_net_6.js                     |             |             |
| Jerry Heapsize: 256                        | +29         | +45         |   
| run_pass/test_fs_rename_sync.js            |             |             |
| Jerry Heapsize: 256                        | +37         | +246        |   
| run_pass/test_process_uncaught_order.js    |             |             |
| Jerry Heapsize: 256                        | +29         | +37         |  
| run_pass/test_fs_open_close.js             |             |             |
| Jerry Heapsize: 256                        | +29         | +245        | 
| run_pass/test_net_4.js                     |             |             |
| Jerry Heapsize: 256                        | +21         | +45         |   
| run_pass/test_process.js                   |             |             |
| Jerry Heapsize: 256                        | +29         | +53         |   

**NOTE:** The '+' means memory saving in bytes.

**Comment by tkeri** [comment]
**Tester: freya, build: release x86 4b665d4**
===================
| testfile                                   | total       | peak        |
|--------------------------------------------|-------------|-------------|
|                                            | diff / byte | diff / byte |
||||
| run_pass/test_process_cwd.js               |             |             |
| Jerry Heapsize: 256                        | +40         | +48         |     
| run_pass/test_events_assert_emit_error.js  |             |             |
| Jerry Heapsize: 256                        | +32         | +48         |    
| run_pass/test_net_6.js                     |             |             |
| Jerry Heapsize: 256                        | +76         | +64         |   
| run_pass/test_fs_rename_sync.js            |             |             |
| Jerry Heapsize: 256                        | +40         | +48         |   
| run_pass/test_fs_fstat_sync.js             |             |             |
| Jerry Heapsize: 256                        | +40         | +48         |  
| run_pass/test_fs_open_close.js             |             |             |
| Jerry Heapsize: 256                        | +24         | +48         | 
| run_pass/test_net_4.js                     |             |             |
| Jerry Heapsize: 256                        | +60         | +64         |   
| run_pass/test_process.js                   |             |             |
| Jerry Heapsize: 256                        | +40         | +48         |   

**NOTE:** The '+' means memory saving in bytes.

**Comment by tkeri** [comment]
The tables show difference of two binaries. 

In a similar manner: https://github.com/Samsung/iotjs/pull/1143

**Comment by hs0225** [comment]
@tkeri Sorry for the delay. I think changing a typechecker except for `isObject` reduces code consistency and cause developers to make mistakes. In fs.js, we can remove unnecessary binding function for type checking.

**Comment by tkeri** [comment]
@hs0225 you are right, the changing reduces code consistency and also reduces the memory.
Can you explain why we could remove this function only in fs.js?

**Comment by hs0225** [comment]
@tkeri I think, it is not necessary to have `checkArg...` in fs.js.

**Comment by DanielBallaSZTE** [comment]
@tkeri @hs0225 Is this issue still valid? Can it be closed?

**Comment by hs0225** [comment]
@DanielBallaSZTE No. I close this issue.
