### ISSUE TITLE
test_net_http_request_response.js in js-remote-test

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1208]
Testing `test_net_http_request_response.js` on rp2 has failed in https://samsung.github.io/js-remote-test since daily testing on 5 Sep. However, I can't reproduce it with the latest on the board.

**Comment by LaszloLango** [comment]
CC: @rtakacs

**Comment by bzsolt** [comment]
I've checked this issue, the error message was the following:
```
uncaughtException: Error: Uncaught 'error' event
iotjs: iotjs/deps/libtuv/src/unix/stream.c:461: uv__stream_destroy: Assertion `!uv__io_active(&stream->io_watcher, 0x001 | 0x004)' failed.
Aborted
```
The test-device was running for a long time, perhaps some resource got stuck.
After a simple reboot it is gone, so tonight this test will also pass on the site.

**Comment by daeyeon** [comment]
@bzsolt Thank you. We may need to see how the test works in a long-term test.
