### ISSUE TITLE
Missing HTTPS documentation in WIKI

### ISSUE THREAD

**Issue by tosyu** [Samsung/iotjs#1215]
Documentation [docs/api/IoT.js-API-HTTPS.md](https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-HTTPS.md) is missing from [docs/api/IoT.js-API-reference.md](https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-reference.md)

**Comment by daeyeon** [comment]
Closed with the reason on https://github.com/Samsung/iotjs/pull/1218
