### ISSUE TITLE
Remove Travis checks in precommit.py

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1229]
All the travis checks in `precommit.py` are being moved to `travis_script.py`. Once that's done, `precommit.py` will not be used for travis and be renamed for another possible purpose.

**Comment by LaszloLango** [comment]
@daeyeon can you clarify for me what should be done by `precommit.py` and `travis_script.py`? Why do we need two sparate scripts?

**Comment by daeyeon** [comment]
@LaszloLango Please take a look at #1392 newly PRed. Some functionalities such as `flash images`, which is not related to travis tests, have been dropped from `precommit.py`. It's no longer needed for travis tests, but not removed yet. We could revise it to easily set up build environments.

**Comment by LaszloLango** [comment]
What is the meaning of the precommit script? I still don't understand why do we need to maintain two script for testing which are basically do the same testing, so there are a lot of code duplication.

**Comment by daeyeon** [comment]
@LaszloLango There is no intention to maintain `precommit.py` for testing. It can be removed. Do you mind if we remove it from #1392?

**Comment by LaszloLango** [comment]
@daeyeon yes please. If nobody should use the `precommit.py`, then we should remove it in #1392

**Comment by bzsolt** [comment]
Is there anything else what wasn't covered by #1392?

**Comment by LaszloLango** [comment]
AFAIK nothing is left. We can close this issue now. @daeyeon feel free to reopen if necessary.
