### ISSUE TITLE
Random Questions

### ISSUE THREAD

**Issue by Ash200012** [Samsung/iotjs#1241]
1. Does iotjs support any sort of downloader option? I am looking for something where I can download images or files in the background. 

2. On a related note, does the HTTP module support Range requests?

3. Any plans to add websockets module? Or if it already exists, where can I get it?

**Comment by glistening** [comment]
@Ash200012 

1. There is no dedicated downloader module. And if you mean separate thread by `in the background`, iotjs does not support multithread.

2. I think not. However, I would like to check it. Do you have sample code for checking `Range request`? 

3. Currently websocket is not supported, and we don't have plan. We will support https first. The websocket library that used in jerryscript debugger may be starting point if we decide to support websocket module.

**Comment by Ash200012** [comment]
Thanks for responding.
1. There are multi threads though when using setTimeout and such...I meant in terms of this.
2. Here is an example: https://www.npmjs.com/package/http-range
3. There is already https source code in the iotjs. Is it incomplete? I guess it requires crypto libraries?

**Comment by glistening** [comment]
1. I think you can use that approach. In fact, it is same thread that runs in one loop.
2. If you mean parser for Content-Range and Range HTTP header field. you may put the name, value pair directly using [http.setHeader](https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-HTTP.md#responsesetheadername-value)
3. HTTPS module is supported and verified on Tizen platform only. It is based on libcurl. We will prepare lightweight version https for low-end device like artik053/tizenrt.

**Comment by Ash200012** [comment]
1. When will HTTPS module be ready for x86 for testing? Is there something simple I can do to enable it for x86?
2. Is it possible to write native module in C++. If not, what CMake files would I need to change to use G++ instead of gcc

**Comment by glistening** [comment]
1. Although HTTP is supported only on Tizen, It should not take much time for porting it to Ubuntu since tizen is based on linux. Please refer to HTTPS related PRs.

2. You may refer to old version CMakefiles from our repository history since our project used C++ about 1 year ago. Perhaps, there may be other issues like name-mangling ( If your native module has public C++ interface that IoT.js has to call ).
