### ISSUE TITLE
Complete GPIO module

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#128]
Implement https://github.com/Samsung/iotjs/wiki/GPIO-API-candidate
Related issue: #110, #117 
Update document https://github.com/Samsung/iotjs/wiki/IoT.js-API:-GPIO

* [x] JS API
   * [x] setPin (#131)
   * [x] readPin , writePin (#169)
   * [x] setPort, readPort, writePort
* [x] x86 linux dummy
* [x] arm-linux on Raspberry Pi 2
* [ ] arm-nuttx on STM32F4-discovery (#276)

* let `query()` be in another task. we need to defined what and how.

**Comment by yichoi** [comment]
Closing since basic GPIO module completed
