### ISSUE TITLE
HTTPS on linux (x86 vs arm)

### ISSUE THREAD

**Issue by Ash200012** [Samsung/iotjs#1294]
I modified the build scripts to compile in HTTPS support for x86 and arm instead of just tizen. On x86 doing an https get of www.google.com works fine and is fast, the chunks come in fast. However on arm, the chunks come in every 350ms (more or less) and so there is a delay before the whole web page is received. Does anyone know why this is?

**Comment by Ash200012** [comment]
Any idea?

**Comment by LaszloLango** [comment]
@Ash200012 sorry for the late answer. HTTPS is an experimental module at the moment. I have no idea what cause the difference, but do not hesitate if you would like the do a deeper investigation on this issue. Any improvement is welcome.

**Comment by LaszloLango** [comment]
cc: @akhilkedia 
Original PR: #926

**Comment by akhilkedia** [comment]
HTTPS module was only officially tested on Tizen (though I did test it on x64 on my own PC).
HTTPS module uses `libcurl` as the backend to make the requests. I think the difference should be coming from `libcurl` itself (probably a result of how it was built for arm).

@Ash200012 Can you add the following line at the end of the function `iotjs_https_initialize_curl_opts()` in [iotjs_module_https.c](https://github.com/Samsung/iotjs/blob/master/src/modules/iotjs_module_https.c) (after line 288) - 
````C
  curl_easy_setopt(_this->curl_easy_handle, CURLOPT_VERBOSE, 1L);
````
This will make libcurl to print verbose output to the commandline.
Make this change, build for arm, and try https get again. If this shows libcurl only getting the information in chunks in every 350sec, it points towards a problem with libcurl build rather than IoT.js. Else its a problem with IoT.js https.

**Comment by Ash200012** [comment]
I actually did enable curl verbose but it didn’t show any issues with curl. I tried same code on x64 and arm and both exhibit the issue with different curl versions. I thought there was something wrong in libtuv but if you aren’t seeing it I am not sure what else could be wrong.
Any other way to debug it?

**Comment by akhilkedia** [comment]
So am I correct in that for you, it works fine on x86, but not on x64 or arm?
(Also, just as quick check, if you have commandline curl on these platforms you are using, can you try to get google.com with commandline curl and verify that it does not have that delay problem?)

**Comment by Ash200012** [comment]
It doesn’t work well on x86 either .. curl command line is fine.
Keep in mind x86, x64, and arm are all different physical machines

**Comment by akhilkedia** [comment]
Oh. I thought you said "On x86 doing an https get of www.google.com works fine and is fast, the chunks come in fast", so I believed you had https working fine for you on x86.

Can you perhaps try the same with HTTP and see if HTTP performs fast? (google.com does not serve on http, but you could big any other big webpage and see if http performs fast, but https does not.)

I will attempt to replicate this issue myself and see. HTTPS is officially supported only for Tizen platform (and I think it is experimental even there), but any improvements are welcome.

**Comment by Ash200012** [comment]
Yes I did say that, but it is still slower than http. I did try http and it is fine in both cases. I think arm was the slowest with https.

**Comment by galpeter** [comment]
@Ash200012 Could you try out my speculative fix? See: https://github.com/galpeter/iotjs/tree/https-improve-ondata

If it works for you I'll submit it as PR to get it into the mainline.

**Comment by Ash200012** [comment]
This works! Was something non performant about the iotjs_jval_create_byte_array and append?

**Comment by galpeter** [comment]
Great I'll create the PR.

The byte array function creates a different data structure which could have bad performance if there is to much data.

**Comment by glistening** [comment]
`iotjs_https_curl_write_callback` (#1311 try to change) is used on both `x86/linux` and `arm/linux`. But there was no problem on `x86/linux` . Any of you knows about the reason? x86 is fast enough to cover the inefficient code? ( @Ash200012 what board do you use arm? RPI2? )  Is there something that I miss?

**Comment by Ash200012** [comment]
I believe that is the case, on x86/x64 it was faster than on arm. My x64 machine is very powerful and the arm was an odroid C1 box.
