### ISSUE TITLE
Link to GPIO-control-ideas on "Getting Started" page is dead

### ISSUE THREAD

**Issue by raju-bitter** [Samsung/iotjs#130]
On the "Getting Started" page, the link to GPIO-control-ideas is dead (URL is https://github.com/Samsung/iotjs/wiki/GPIO-control-ideas).
Should that link be "https://github.com/Samsung/iotjs/wiki/GPIO-API-candidate" instead?

**Comment by seanshpark** [comment]
Yes, you are right. I've changed to link in 'Getting Started' page. Thank you!

**Comment by ILyoan** [comment]
Closing
