### ISSUE TITLE
Building failed for STM4diss

### ISSUE THREAD

**Issue by Zakaria-Ben** [Samsung/iotjs#1308]
Hi,
I've tried to run iotjs for STM32F4dis but I got this error : 

make[3]: Leaving directory '/home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug/deps/jerry-host'
[ 49%] No install step for 'hostjerry'
[ 50%] Completed 'hostjerry'
make[2]: Leaving directory '/home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug'
[ 50%] Built target hostjerry
make[1]: Leaving directory '/home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug'

[Failed - 2] make -C /home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug -j

**Comment by LaszloLango** [comment]
@Zakaria-Ben how do you try to build? Is `tools/precommit.py --test=nuttx` works on your local machine?

**Comment by Zakaria-Ben** [comment]
Thanks @LaszloLango. No, it doesn't work, I got another error 

make: Leaving directory '/home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug'

[Failed - 2] make -C /home/ubuntu/iotjs-nuttx3/iotjs/build/arm-nuttx/debug -j

[Failed - 1] ./tools/build.py --buildtype=debug --target-arch=arm --target-os=nuttx --nuttx-home=/home/ubuntu/iotjs-nuttx3/iotjs/deps/nuttx/nuttx --target-board=stm32f4dis --jerry-heaplimit=78 --profile=test/profiles/nuttx.profile

**Comment by LaszloLango** [comment]
@Zakaria-Ben that is only the command, but not the error. Search for the error message in the build log.

**Comment by Zakaria-Ben** [comment]
I think I have a problem from the previous steps, when I do the configuration from make menuconfig and then I run the make command I got this : 
make[1]: Entering directory '/home/ubuntu/iotjs-nuttx/nuttx/libxx'
make[1]: cygpath: Command not found
make[1]: cygpath: Command not found

It's a problem with cygpath ?

**Comment by LaszloLango** [comment]
Did you run `tools/apt-get-install-nuttx.sh`?

**Comment by Zakaria-Ben** [comment]
./tools/apt-get-install-nuttx.sh: No such file or directory

**Comment by Zakaria-Ben** [comment]
Yes, but I still have the same problem

**Comment by Zakaria-Ben** [comment]
@LaszloLango I've tried again following the steps from https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-STM32F4-NuttX.md. But again I got this : 

make[2]: Entering directory '/home/ubuntu/iotjs-nuttx/apps/system/iotjs'
cp /home/ubuntu/build/arm-nuttx/debug/lib/lib*.a .
cp: cannot stat '/home/ubuntu/build/arm-nuttx/debug/lib/lib*.a': No such file or directory
Makefile:125: recipe for target 'copylibs' failed

**Comment by glistening** [comment]
@Zakaria-Ben What os do you use?

**Comment by Zakaria-Ben** [comment]
Yes I know it's strange, I'm using ubuntu 17.10.
I've tried to do the configuration from the beginning, but I got this :

**Comment by Zakaria-Ben** [comment]
I still have the same issue since yesterday, I need help
