### ISSUE TITLE
issue while building iotjs for nuttx

### ISSUE THREAD

**Issue by Zakaria-Ben** [Samsung/iotjs#1313]
Hi guys,
I'm really struggling since a couple of days with building iotjs for Nuttx.
When I disable **Application Configuration -> System Libraries and NSH Add-ons -> IoT.js** from the menuconfig, Nuttx finish the compilation without any error, but without IoT.js application. And when I try to compile iotjs using : 
`./tools/build.py --target-arch=arm --target-os=nuttx --nuttx-home=../nuttx --target-board=stm32f4dis --jerry-heaplimit=78`

I got this :

[ 94%] Building C object CMakeFiles/tuv.dir/src/unix/nuttx.c.obj
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c: In function 'uv__to_stat':
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:587:28: error: 'struct stat' has no member named 'st_atim'
   dst->st_atim.tv_sec = src->st_atim.tv_sec;
                            ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:588:29: error: 'struct stat' has no member named 'st_atim'
   dst->st_atim.tv_nsec = src->st_atim.tv_nsec;
                             ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:589:28: error: 'struct stat' has no member named 'st_mtim'
   dst->st_mtim.tv_sec = src->st_mtim.tv_sec;
                            ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:590:29: error: 'struct stat' has no member named 'st_mtim'
   dst->st_mtim.tv_nsec = src->st_mtim.tv_nsec;
                             ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:591:28: error: 'struct stat' has no member named 'st_ctim'
   dst->st_ctim.tv_sec = src->st_ctim.tv_sec;
                            ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:592:29: error: 'struct stat' has no member named 'st_ctim'
   dst->st_ctim.tv_nsec = src->st_ctim.tv_nsec;
                             ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:602:32: error: 'struct stat' has no member named 'st_ctim'
   dst->st_birthtim.tv_sec = src->st_ctim.tv_sec;
                                ^
/home/ubuntu/iotjs-nuttx2/iotjs/deps/libtuv/src/unix/fs.c:603:33: error: 'struct stat' has no member named 'st_ctim'
   dst->st_birthtim.tv_nsec = src->st_ctim.tv_nsec;
                                 ^
CMakeFiles/tuv.dir/build.make:206: recipe for target 'CMakeFiles/tuv.dir/src/unix/fs.c.obj' failed
make[5]: *** [CMakeFiles/tuv.dir/src/unix/fs.c.obj] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/home/ubuntu/iotjs-nuttx2/iotjs/build/arm-nuttx/debug/deps/libtuv'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tuv.dir/all' failed
make[4]: *** [CMakeFiles/tuv.dir/all] Error 2

**Comment by glistening** [comment]
@Zakaria-Ben A memory occurred from the log above. Please see https://github.com/Samsung/iotjs/issues/641#issuecomment-281120316 and the followings. In your build system, `_DEFAULT_SOURCE` may be defined.  Could you let me know what version of `gcc` do you use?

**Comment by Zakaria-Ben** [comment]
I'm using gcc 7.2.0

**Comment by glistening** [comment]
@Zakaria-Ben I've found following error on Ubuntu 17.10.

```
[ 36%] Performing install step for 'libjerry'
[ 37%] Completed 'libjerry'
make[2]: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug'
[ 37%] Built target libjerry
make[5]: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug/deps/jerry-host'
[100%] Built target jerry-snapshot
make[4]: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug/deps/jerry-host'
make[3]: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug/deps/jerry-host'
[ 39%] No install step for 'hostjerry'
[ 40%] Completed 'hostjerry'
make[2]: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug'
[ 40%] Built target hostjerry
make[1]: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/brian/iotjs/build/arm-nuttx/debug'

[Failed - 2] make -C /home/brian/iotjs/build/arm-nuttx/debug -j


[Failed - 1] ./tools/build.py --buildtype=debug --target-arch=arm --target-os=nuttx --nuttx-home=/home/brian/iotjs/deps/nuttx/nuttx --target-board=stm32f4dis --jerry-heaplimit=78 --profile=test/profiles/nuttx.profile
```

It looks same  to https://github.com/Samsung/iotjs/issues/1308#issue-274486448.

We may need time to support Ubuntu 17.10 because of other jobs in progress.
If you are in a hurry, what about trying build on Ubuntu 16.04 LTS? You can copy the final nuttx.bin to flash to device.

**Comment by galpeter** [comment]
@Zakaria-Ben Hi, could you try out applying this patch (https://gist.github.com/galpeter/9748ea23b726d8e8c1d75b1263ccc095) to your `deps/libtuv` repository? After that please try the build again.

**Comment by Zakaria-Ben** [comment]
@galpeter , @glistening Thanks guys for your help.
@galpeter your solution works perfectly, thank you.

**Comment by galpeter** [comment]
@Zakaria-Ben It's just a bit workaround (for now). We'll get it into the mainline in the coming days.

**Comment by Zakaria-Ben** [comment]
Yes I see. @galpeter another question, can I run iotjs on a raspberry Pi 3 ?

**Comment by galpeter** [comment]
@Zakaria-Ben Yes! just build it like the rpi2 and it should work.

**Comment by Zakaria-Ben** [comment]
Perfect, thanks.

**Comment by glistening** [comment]
Close since https://github.com/Samsung/iotjs/pull/1320 landed.
