### ISSUE TITLE
Error build on Linux Fedora 22

### ISSUE THREAD

**Issue by junwatu** [Samsung/iotjs#132]
I have an issue when building iotjs on Fedora 22. Any help? thanks

...
cmake /home/equan/Downloads/IoT/iotjs/deps/jerry -DENABLE_LTO=OFF -DCMAKE_TOOLCHAIN_FILE=/home/equan/Downloads/IoT/iotjs/cmake/config/x86_64-linux.cmake

Traceback (most recent call last):
  File "./tools/build.py", line 535, in <module>
    if not build_libjerry():
  File "./tools/build.py", line 412, in build_libjerry
    check_run_cmd('cmake', jerry_cmake_opt)
  File "./tools/build.py", line 106, in check_run_cmd
    retcode = run_cmd(cmd, args)
  File "./tools/build.py", line 96, in run_cmd
    return subprocess.call([cmd] + args)
  File "/usr/lib64/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by seanshpark** [comment]
May be some tools are not prepared(cmake?) 
Please check https://github.com/Samsung/iotjs/wiki/Build-for-Linux#prerequisite.
As we are not currently using Fedora, it may take time to check. 
Please leave a note if solved. Thank you.

**Comment by junwatu** [comment]
@seanshpark yes you'r right i didnt have cmake on my system . Have compiled it but another issue arise. I cannot find what's cq here and I try to build jerry manually but it take to long. any advice? thanks 

...
make -C /home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry debug.jerry-core -j

make: Entering directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
make[1]: Entering directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
make[2]: Entering directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
make[3]: Entering directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
make[3]: Leaving directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
make[3]: Entering directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
Linking CXX static library libdebug.jerry-core.a
ccache: error: Could not find compiler "cq" in PATH
jerry-core/CMakeFiles/debug.jerry-core.dir/build.make:2785: recipe for target 'jerry-core/libdebug.jerry-core.a' failed
make[3]: *** [jerry-core/libdebug.jerry-core.a] Error 1
make[3]: Leaving directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
CMakeFiles/Makefile2:4248: recipe for target 'jerry-core/CMakeFiles/debug.jerry-core.dir/all' failed
make[2]: *** [jerry-core/CMakeFiles/debug.jerry-core.dir/all] Error 2
make[2]: Leaving directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
CMakeFiles/Makefile2:4260: recipe for target 'jerry-core/CMakeFiles/debug.jerry-core.dir/rule' failed
make[1]: *** [jerry-core/CMakeFiles/debug.jerry-core.dir/rule] Error 2
make[1]: Leaving directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'
Makefile:1643: recipe for target 'debug.jerry-core' failed
make: *** [debug.jerry-core] Error 2
make: Leaving directory '/home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry'

[Failed - 2] make -C /home/equan/Downloads/IoT/iotjs/build/x86_64-linux/debug/deps/jerry debug.jerry-core -j

**Comment by seanshpark** [comment]
I also don't know what `cq` can be. as the error message is `ccache: error: Could not find compiler "cq" in PATH`, it seems to be some files in the tool chain you have in your Fedora.
I think it may take time to build iotjs. but lets try with jerryscript(https://github.com/Samsung/jerryscript) first. jerryscript has it's own build system, it must be ok with this also. so try like this;
```
cd deps/jerryscript
make debug.linux
```
it doesn't show any message but will record in a text log. if there my be any error, it'll show you the log file path so you can open ad check what's the problem. there will be no console message when success.

**Comment by hs0225** [comment]
Use make debug.linux
