### ISSUE TITLE
`./tools/build.py --jerry-debugger` fails

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1328]
Running `./tools/build.py --jerry-debugger` fails with the following errors.

```
error: implicit declaration of function ‘nanosleep’ [-Werror=implicit-function-declaration]
   nanosleep (&(const struct timespec)
error: invalid use of undefined type ‘struct timespec’
```
It's seemingly occurred since #1315. Do we need to consider a travis check for this?

**Comment by LaszloLango** [comment]
@daeyeon We also recognized that the build fails with `--jerry-debugger` since the "all in one" build was enabled. AFAIK, @galpeter is working on it.

**Comment by galpeter** [comment]
Currently I don't have any good/clean solution. So I think we should revert the all-in-one build for now until we have a good resolution. I'll create a PR to revert it.
