### ISSUE TITLE
Builtin Javascript module issue

### ISSUE THREAD

**Issue by Zakaria-Ben** [Samsung/iotjs#1337]
Hi,
I would add a new Javascript module to Iotjs. I've created the js file in src/js, and then I tried to build using `./tools/build.py --iotjs-include-module`, but it doesn't work :
build.py: error: unrecognized arguments: --iotjs-include-module

**Comment by LaszloLango** [comment]
Hi @Zakaria-Ben,
the `--iotjs-include-module` build option was removed recently during the module system rework. Please check https://github.com/Samsung/iotjs/blob/master/docs/devs/Writing-New-Module.md

You must edit `src/modules.json`, if you put your module into `src/js`. Don't forget to enable it during the build with `--cmake-param=-DENABLE_MODULE_[NAME]=ON` or create your own profile file based on `profiles/*.profile` or `test/profiles/*.profile`.

IoT.js also support CommonJS modules. For details please check https://github.com/Samsung/iotjs/blob/master/docs/devs/Developer-Tutorial.md#writing-user-modules

**Comment by Zakaria-Ben** [comment]
Thanks for the help @LaszloLango

**Comment by Zakaria-Ben** [comment]
@LaszloLango Can I add a package to iotjs?

**Comment by LaszloLango** [comment]
@Zakaria-Ben could you explain what would you like to do exactly? Do you want to add you module to the code base under `src/js` and `src/module.json`?

**Comment by Zakaria-Ben** [comment]
For adding a module, I did what to told me before and that's fine, I need right now to use when.js: https://github.com/cujojs/when

**Comment by LaszloLango** [comment]
I don't think when.js fits well into the main repo.
