### ISSUE TITLE
Handling uncaught exception (early exit)

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#1340]
Several issues about uncaught exception are reported.
I think this items should be considered together, and put discussion in one place.

- [x] What should we do when exception is occurred during exit?
  - Related issue: Process.exit (#1323)
- [x] How can we clean up on NuttX or TizenRT?
  - Related issue: UV cleanup assertion failure (#1245)

**Comment by glistening** [comment]
Related Issues: #1348, #1349, #1350

**Comment by LaszloLango** [comment]
All related issues/PRs are closed. Feel free to reopen if still valid.
