### ISSUE TITLE
The 3rd party libraries used in a native module

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1362]
When a native module uses the 3rd party libraries and it's needed to be built and linked with iot.js, the current features supported by `modules.json`, the module description, seems not enough.

Assuming `mbedtls` which would be used in `https` native module, there are more things not handled in `modules.json`. Its source seemingly needs to be located within `/deps`, the build description goes into `/cmake`, and it's added to `iotjs.cmake` as a part of building iot.js. That means that user may need to learn and touch iot.js build description to add their native module. And, the resource like `iotjs.cmake` will be bigger when the 3rd party libraries come more and more.

If users can somehow independently describe information about the 3rd party libraries in `modules.json`, we can reduce the burdens on users and let them more focus on their module.

**Comment by LaszloLango** [comment]
CC: @galpeter

**Comment by galpeter** [comment]
I was also looking into this and I've got two things:
1) a simple way to specify extra third-party modules. See: https://github.com/galpeter/iotjs/commit/3b357305a73c81a57f51cf099b837e5382db885f
   With this the developer can specify an pre-built shared/static lib to be linked for the iotjs binary.
2) a cmake based way: https://github.com/galpeter/iotjs/commit/83619505af5f633b89ba385afc1f6e33deea3381 
  I've also created an example module: https://github.com/galpeter/iotjs_ext_dem
  With this the developer can do more powerful things, like compile the module call extra methods if needed and everything will be integrated into the IoT.js build.

In my opinion both things have purpose in the repo. The first one is a light-weight way to add 3rd party modules which can be used most of the times.

What do you think?

**Comment by daeyeon** [comment]
Thanks for the swift response. I agree that having both is useful for each purpose.

By the way, in case that a module needs to clone a remote repository before building itself, do you think that we need to take care of it? (e.g: automatically clone such a repository if it doesn't exist), or else, we'd better leave it as user's responsibility?

**Comment by galpeter** [comment]
If the module uses CMake logic it can clone itself out during the build (CMake have support for svn/git), but generally I would say it should be user's responsibility (as there could be simply to many possibilities). Still we could provide a preferred way to do so.

I'll try create another example which uses cloned repo to see what can we do.

**Comment by LaszloLango** [comment]
#1371 must resolve this. Feel free to reopen if it is still a valid issue.
