### ISSUE TITLE
What's the status of BLE(Bluetooth Low Energy) Support?

### ISSUE THREAD

**Issue by ziransun** [Samsung/iotjs#1363]
Hi,

Is it okay to let me know the status of BLE? What OSs and boards does it support? And any instruction on setting up?

Thanks!

Ziran

**Comment by glistening** [comment]
@ziransun Currently BLE is tested on `rpi` only. But I believe it will work for linux based system with a little effort. For `tizenrt/artik053` and `nuttx/stm32f4`, we don't support BLE yet since we don't have BLE native support for that platforms.

**Comment by ziransun** [comment]
@glistening Thanks very much for your reply. Just to confirm - Did you mean BLE tested on rpi for both Central and peripheral modules? And is it okay to point any instructions on building  BLE support for rpi?

**Comment by glistening** [comment]
@ziransun We support BLE peripheral only, and we ported [bleno](https://github.com/sandeepmistry/bleno) into iotjs.

**Comment by glistening** [comment]
@ziransun 

1. make new profile for ble enabled.

```sh
$ cp profiles/default.profile profiles/ble.profile
$ echo "ENABLE_MODULE_BLE" >> profiles/ble.profile
```

2. build iotjs
```
./tools/build.py --target-arch=arm --target-board=rpi2 --profile=profiles/ble.profile
```
