### ISSUE TITLE
Remove JavaScript layer and rework API in System I/O module

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#1367]
To simplify the code like ADC, remove the JavaScript layer that only performs type checking.

Currently, some APIs are confusing to us. For example, the close function of GPIO works asynchronously, but, close function of I2C is performed in synchronization. This needs to be fixed.
All API provide sync and async functions depending on the presence of the callback function.
The following APIs are changed.

Before,
```js
var Gpio = require('gpio');
var gpio = new Gpio();

// only must open asynchronously
var gpio1 = gpio.open({pin: 1}, function(err) {
    var value = gpio1.readSync(); // sync
    gpio1.read(function(err, value) { // async
    });
});
```

After,
```js
var Gpio = require('gpio');

var gpio1 = new Gpio({pin: 1}); // sync
var gpio2 = new Gpio({pin: 2}, function(err) {  // async
   var value = gpio1.read(); // sync
   gpio2.read(function(err, value) { // async
      
   });
});
```
The modules below are involved in this task.

- [x] ADC
- [x] GPIO
- [x] I2C
- [x] PWM
- [x] SPI
- [x] UART

**Comment by galpeter** [comment]
I've been thinking a while now about the optional callback parameter and it's effect to make the call async. I think it can be a bit confusing that a given call is sync or not simply on the number of arguments. In my opinion we should provide a sync and async methods just like our fs api to reduce the possible programming errors.

**Comment by hs0225** [comment]
Considering the opinion of many people, I would like to confirm the following.
```js
var Gpio = require('gpio');

// async API
gpio.open({pin: 1}, function(err, gpioPin) {
    gpioPin.read(function(err, value) {
    });
});

// sync API
var gpioPin = gpio.openSync({pin: 1});
var value = gpioPin.readSync();
```

**Comment by hs0225** [comment]
Done.
