### ISSUE TITLE
fatal error: sys/boardctl.h: No such file or directory

### ISSUE THREAD

**Issue by morganrallen** [Samsung/iotjs#138]
```
CC:  nsh_init.c
nsh_init.c:42:26: fatal error: sys/boardctl.h: No such file or directory
 #include <sys/boardctl.h>
```

I'm getting this error while trying to build NuttX using these instructions. https://github.com/Samsung/iotjs/wiki/Build-for-NuttX

I can get to step 5 but `make` for NuttX fails.

**Comment by seanshpark** [comment]
`sys/boardctl.h` file does not exist for the revision iotjs is based on. I think you may had some problem with `git checkout -b iotjs 9388ed9a1780cea6fb349a0b91bfcd657f00ca90` step. please start from the beginning and watch the messages and if there is some problem, please let me know.

**Comment by morganrallen** [comment]
OK! That was it, right away things went much smoother. Sadly it didn't drop in and run on the NUCLEO-F401RE looks like it just barely meets the specs so might be possible to do a port.
