### ISSUE TITLE
What is the purpose of `struct iotjs_module_objects_t` ?

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#1383]
Is `iotjs_module_objects_t` for (1) hiding the module object's type `jerry_value_t` or (2) aggregating non-static data that would be in `iotjs_module_t` (#1304) ?

I would like to change the name after getting your opinion. (@LaszloLango, @galpeter)

For (1),
I would like to rename `iotjs_module_objects_t` to `iotjs_module_object_t` since it is not a type for an aggregation of module objects, but for a module object itself. `jerry_value_t` could be another candidate because we are removing JS engine abstraction layer.

For (2),
What about using `iotjs_module_rw_data`, `iotjs_module_nonstatic_data` or whatever for that purpose?

**Comment by LaszloLango** [comment]
Sorry for the late answer. The second one. Both names are good for me.

**Comment by glistening** [comment]
I pushed PR #1394 for this issue.

**Comment by glistening** [comment]
#1394 landed
