### ISSUE TITLE
WISH: Support raspbian for raspberrypi0

### ISSUE THREAD

**Issue by rzr** [Samsung/iotjs#1389]
Hi,
Here is a low priority wish about supporting raspbian, the issue can be closed anytime since it's more a downstream task than upstream work.

But to help community I will use this URL to share my work in progress.

More to come soon.

Note that Pi0 can also supported be by Tizen too, PM me if any interest.

Relate-to: https://github.com/Samsung/iotjs/pull/1145
Cc: @ziransun
Cc: @nherriot

**Comment by rzr** [comment]
If anyone want to try on raspbian (or debian):
git clone https://github.com/tizenteam/iotjs && cd iotjs && ./debian/rules
Once verified, extra optional modules could be added.

**Comment by nherriot** [comment]
I think it would be a very good 'strategic' move to support raspberry pi. Especially now IoTJS is second place in rankings to cylonjs.com - it's now the 3rd biggest selling personal compute platform 'ever' !
https://www.raspberrypi.org/magpi/raspberry-pi-sales/

**Comment by rzr** [comment]
Yea, I agrea it would be a good target to extend support, I have a plan to get it available directly from debian and derivates (raspbian etc), It's on my list I will keep you updated stay tunned at:
https://blogs.s-osg.org/author/pcoval

**Comment by yichoi** [comment]
IoT.js supports RPi2 officially and I don't have a plan to support other variants of RPis. I think everyone who can handle RPis can easily port to each variants of RPis.

**Comment by nherriot** [comment]
yicho - are you saying that 'everyone' who can handle RPis know how to port a Javascript framework from one Linux variant to another? (That's more than 10 million people!!!) I personally think that is a skilled job and certainly not one that even experienced Java Scrip developers want to be bothered with. I hope that in the near future this is something the community can find here at the IoTJS home! :-)

**Comment by rzr** [comment]
To be tracked at:
https://bugs.debian.org/889824
