### ISSUE TITLE
Minor semantic error in wiki

### ISSUE THREAD

**Issue by mmatyas** [Samsung/iotjs#1402]
The following sentence from the description of [iotjs_handlewrap_t](https://github.com/Samsung/iotjs/wiki/Inside-IoT.js#iotjs_handlewrap_t) might need a review:

---

*Unlike **iotjs_jobjectwrap_t**, **iotjs_jobjectwrap_t** increases RC for the Javascript object when an instance of it is created to prevent GC while the handle is alive.*

---

(I assume you didn't intend to repeat `iotjs_jobjectwrap_t` twice.)

**Comment by LaszloLango** [comment]
Wiki pages are out of date. The up to date documentation is available in the `docs` folder: https://github.com/Samsung/iotjs/tree/master/docs
