### ISSUE TITLE
RiotOS

### ISSUE THREAD

**Issue by drasko** [Samsung/iotjs#150]
Hi,
although NuttX is excellent choice, it would be interested considering RiotOS also, due to the evolved IoT stack (6LoWPAN, RPL, CoAP, CBOR, ...): http://www.riot-os.org/. Or at least target for high portability, so that IoT.js can be ported to other RTOSes easily. Any thoughts?

BR,
Drasko

**Comment by chunseoklee** [comment]
First of all, thank you for your interest and suggestion.
RiotOS seems to be a great platform for IoT.js.
IMHO, it is not that hard to port IoT.js to RiotOS if RiotOS is POSIX compliance.

**Comment by yichoi** [comment]
no more discussion. closing.
