### ISSUE TITLE
Stop running your own registry

### ISSUE THREAD

**Issue by indexzero** [Samsung/iotjs#153]
From your [docs on packages](https://github.com/Samsung/iotjs/wiki/IoT.js-Package):

> IoT.js follows the practice of node.js npm to provide module development community with separate IoT.js own registry.

This is actually *not the practice* of JavaScript and node developer communities. The trend has been to bring separate registries into the mainline npm registry because having multiple sources of truth is very frustrating and silly. Most recently this was done with Apache Cordova (aka PhoneGap):

https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

Save yourself future pain and just move back into the mainline npm registry now. It probably made sense to run your own registry until you announced the project but now that it's announced just prefix your packages with `iotjs-` just like `level-`, `grunt-` and `gulp-` package communities already do.

**Comment by seanshpark** [comment]
@indexzero , thank you for point this out. IPM server is ready but not active yet so I think we have some time. 
@lemmaa , what do you think?

**Comment by indexzero** [comment]
Ready but not active is the perfect time to do it. If you want until it is active then you will have pain.

**Comment by diorahman** [comment]
+1

**Comment by lemmaa** [comment]
@indexzero , @seanshpark , I agree. But, can we find more sophisticate way of distinguishing IoT.js compatible packages from all npm packages, even before install? Because IoT.js will support only part of node.js API.

**Comment by diorahman** [comment]
Can we introduce a "special" client just like [apm](https://www.npmjs.com/package/atom-package-manager) for atom.io to make sure the compatibility?

**Comment by indexzero** [comment]
+1 to the suggestion from @diorahman. This is what `atom` and `cordova` do.

**Comment by Qard** [comment]
+1 for a special client. It could just scope installable packages to only ones which include the iotjs keyword and could automatically include it when initializing or publishing a module.

**Comment by yichoi** [comment]
closing. ipm is not maintained.
