### ISSUE TITLE
Nominating Minsoo Kim(@irishair7) to become an IoT.js committer

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#1539]
I would like to nominate Minsoo Kim(@irishair7) to become a committer. 

He already has 10 patches:

- Remove iotjs_jhelper_call_ok (#1533) 
- Modify style checker to use regular expression (#1534) 
- Add release for the return of iotjs_jhelper_call (#1525) 
- Remove code that has no effect. (#1524)
- Remove redundant condition statement (#1519) 
- Fix wrong type local var in buffer_allocate (#1521) 
- Fix wrong behaviour of iotjs_process_exitcode (#1510) 
- Make iotjs_https_create() more simple and readable (#1516) 
- Defer the release of builtin modules after uv_loop close. (#1505) 
- add assert for handling exceptional cases (#1497)

**Comment by yichoi** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by daeyeon** [comment]
+1

**Comment by haesik** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by yichoi** [comment]
No objection for a long time, he is now IoT.js committer. Congratulation!
