### ISSUE TITLE
broken Timers

### ISSUE THREAD

**Issue by WebReflection** [Samsung/iotjs#154]
By [specification](http://dev.w3.org/html5/spec-LC/timers.html#timers), and since about ever in every engine, timers accept extra arguments.

```js
setTimeout(function (str) {
  console.log(str);
}, 1000, "Hello IoT.js!!");
```
Above code should log `Hello IoT.js!` ... it prints
```
uncaughtException: undefined
```
instead.

Please get core functionalities right ;-) thank you!

**Comment by ILyoan** [comment]
@WebReflection Thanks for pointing out. It looks like we haven't been visiting timer for long time since initial implementation. I'll take a look at this.

**Comment by ILyoan** [comment]
Closing as #157 landed.
Feel free to reopen if needed
