### ISSUE TITLE
MbedTLS integration process

### ISSUE THREAD

**Issue by DanielBallaSZTE** [Samsung/iotjs#1541]
Here are the main steps of integrating MbedTLS into IoT.js:

- [x] ~TLS Client~
- [x] ~TLS Server~
- [x] ~HTTPS Client~
- [x] ~HTTPS Server~

Currently we are focusing on implementing the client, both HTTPS and TLS, and providing a Node.js like API and behaviour.

The connections between the components presented in a component diagram would look like this so far:

![image](https://user-images.githubusercontent.com/20175069/37398446-de3f548a-277e-11e8-8904-5bc2f09e28d2.png)

**Comment by daeyeon** [comment]
Thanks for sharing the plan. BTW, can you clarify if we need to have http**s**_incoming? I guess we can use http_incoming instead.

**Comment by zherczeg** [comment]
We will try to reuse the code as much as possible.
