### ISSUE TITLE
build arm-cross error on Ubuntu 14.04 x86

### ISSUE THREAD

**Issue by leenux** [Samsung/iotjs#160]
After sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
I run ./tools/build.py --buildtype=release --noinit-submodule \
--target-arch=arm --target-os=linux
Error Msg:
Linking CXX static library librelease.jerry-core.a
Error running link command: No such file or directory
make[3]: *** [jerry-core/librelease.jerry-core.a] Error 2
make[3]: Leaving directory `/root/arm/iotjs/iotjs/build/arm-linux/release/deps/jerry'
make[2]: *** [jerry-core/CMakeFiles/release.jerry-core.dir/all] Error 2
make[2]: Leaving directory `/root/arm/iotjs/iotjs/build/arm-linux/release/deps/jerry'
make[1]: *** [jerry-core/CMakeFiles/release.jerry-core.dir/rule] Error 2
make[1]: Leaving directory `/root/arm/iotjs/iotjs/build/arm-linux/release/deps/jerry'
make: *** [release.jerry-core] Error 2
make: Leaving directory `/root/arm/iotjs/iotjs/build/arm-linux/release/deps/jerry'

How to solve the problem？ 
thanks

**Comment by ILyoan** [comment]
@leenux Could you try with
```
./tools/build.py --buildtype=release --target-arch=arm --target-os=linux
```
?

**Comment by leenux** [comment]
yes,I try ./tools/build.py --buildtype=release --target-arch=arm --target-os=linux.
and the same error message was occured.

**Comment by ILyoan** [comment]
@leenux Can I see the full build output?

**Comment by ILyoan** [comment]
Not sure but this probably is related to https://github.com/Samsung/jerryscript/issues/489.

**Comment by ILyoan** [comment]
@leenux Is the problem still there?

**Comment by LaszloLango** [comment]
There is no response since Nov 9, 2015, so we should close this.
