### ISSUE TITLE
how should i use it?

### ISSUE THREAD

**Issue by martinwithyou** [Samsung/iotjs#1601]
thanks

**Comment by akosthekiss** [comment]
Could you please be a bit more specific about your issue? Have you taken a look at the documentation? Was there something not clear? Do you have a use case that's not described well enough? Did you have problems building the project? On what host system, for what platform, using which tool chain? Could you not run it? Could you not write your own JS app or module for or run them on it?

**Comment by jiwonpark** [comment]
I think it's a perfectly valid question.

I have 7 years of experience as a Tizen developer, but am having trouble figuring out where to start from.

**Comment by zherczeg** [comment]
I would recommend to start with something simple, e.g. a write a "hello world" apllication. Then you can continue with using modules to do something (e.g. read / process a file, create output), then write modules to help you.

**Comment by jiwonpark** [comment]
Is there a comprehensive guide for running this framework on each of the supported devices?

I think that might help.

**Comment by jiwonpark** [comment]
https://github.com/Samsung/iotjs/wiki/Getting-Started

**Comment by LaszloLango** [comment]
Tizen build guide: https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-RPi3-Tizen.md

**Comment by jiwonpark** [comment]
Yes this is the guide I followed and build failed..

**Comment by jiwonpark** [comment]
By any chance, do I have to cook up my own .gbs.conf?

**Comment by LaszloLango** [comment]
No you don't. It should work out of the box. Unfortunately I am not familiar with Tizen, so I cannot help much. @rtakacs @hs0225 could you take a look in this?

P.S.: The CI uses docker, so you can also use the existing docker image if you want a quick workaround.
`docker pull iotjs/ubuntu:0.8`

**Comment by jiwonpark** [comment]
Thanks for the help!

**Comment by jiwonpark** [comment]
It seems you can simply get the latest rpm package from here:
http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/armv7l/iotjs-1.0.0-8.1.armv7l.rpm

**Comment by daeyeon** [comment]
Closed because of no more response from the issue owner.
