### ISSUE TITLE
Tizen target cannot be compiled with minimal profile

### ISSUE THREAD

**Issue by rtakacs** [Samsung/iotjs#1603]
The **mbedtls static libs** are always linked to the shared object ([iotjs.spec#L96](https://github.com/Samsung/iotjs/blob/master/config/tizen/packaging/iotjs.spec#L96)). Since js-remote-test creates **minimal profile** build, there is an error because the HTTPS module is disabled (mbedtls is not compiled). So, the mbedtls static libs should only be used if the HTTPS module is enabled.

I've moved the shared object part of the iotjs.spec to the CMake file because the CMake knows all information about the build.

**Comment by hs0225** [comment]
#1604 landed.
