### ISSUE TITLE
Supporting benchmark of JerryScript

### ISSUE THREAD

**Issue by lemmaa** [Samsung/iotjs#161]
IoT.js contains an amount of JavaScript codes to implement built-in modules. How can we provide the way of using such codes in IoT.js to benchmark the performance of JerryScript.
Let's list up the ideas and issues.

**Comment by egavrin** [comment]
As far as I understood, the main issue is to emulate I/O.
Can we just define strings with appropriate input data and replace all I/O with this data?

**Comment by ILyoan** [comment]
One option that we can think about is adding a build mode for benchmarking JerryScript. In this mode, main entry for IoT.js requires all of the native modules that makes JerryScript parse and run all the native modules. Since native modules are included in IoT.js binary there will be no I/O.

**Comment by yichoi** [comment]
Closing. It's better to handle at [JerryScript](https://github.com/Samsung/jerryscript) itself.
