### ISSUE TITLE
Please add License for how iotjs distributed

### ISSUE THREAD

**Issue by martensms** [Samsung/iotjs#164]
Please add a License to the repository, so people can be safe using it :)

I'd love to see this project as MIT/expat (personal preference), as it resolves issues that come with LGPL if someone decides to build his own runtime based on your project (e.g. OpenGL bindings or similar). But that's just a suggestion.

**Comment by seanshpark** [comment]
@martensms , out license is described at https://github.com/Samsung/iotjs/wiki/License page, and please look at https://github.com/Samsung/iotjs/wiki/IoT.js-Developer's-Certificate-of-Origin-1.0 also. 
Thank you.

**Comment by martensms** [comment]
@seanshpark Oh, okay. I didn't take a look at the wiki for the license.

Usually, projects store the License files in the repository (LICENSE.txt), because you can get into legal troubles if people download the repo as a zip file and they had no license in the zip file.
