### ISSUE TITLE
Ease up installation with Debian packages

### ISSUE THREAD

**Issue by cookiengineer** [Samsung/iotjs#165]
Hey guys,

I just got my RPi2 and wanted to try out jerryscript / IoT.js. I figured out that you don't have any binary builds in the releases section :(

I was kind of an apt shadow in the past and would love to contribute to the project by building up a repo with the required bundling logic. I do that myself for most JS projects (see [lycheejs-bundle](https://github.com/Artificial-Engineering/lycheejs-bundle) if you're interested) and debian packages are supercool for first-time users as they don't have to have a proper compiler setup and bla.

So I'm gonna start building some packages today (hope I'll get far enough) and I hope to get feedback. Creating a generic repo and if everyone likes it, I would love to move it upstream to the Samsung orga.

What kind of license is iotjs shipped with? I'd use the same license for the bundling logic.
Couldn't find it, so I opened [an issue](https://github.com/Samsung/iotjs/issues/164) for it.

**Comment by seanshpark** [comment]
@martensms , about RPi2 binary, hope https://github.com/Samsung/iotjs/wiki/Build-for-Linux and https://github.com/Samsung/iotjs/wiki/Build-for-ARM-Linux-(RPi2) pages help.
And please go on with `building some packages` :). It may be a great help to us and others.

**Comment by yichoi** [comment]
@cookiengineer , do you still have plan to work on it?

**Comment by cookiengineer** [comment]
I kind of put it on hold, due to some weird problems I got with some segfaults while running my code. I'm not sure if it's related to memory limits of the VM or if it's related to a bug in the code. The Debian package generation itself is pretty easy, as it just requires `ar` and `tar` as a binary.

- I don't know where to put the code for it?
- Is there something like an existing CI solution in place already?
- Would it make sense to have something like `iotjs-bundles` as a repository, so that people can create their own bundles for other platforms as well?

**Comment by yichoi** [comment]
Hi. Before answering your questions, please note that I'm not an expert on debian packaging. As far as I understand, you're going to write a bundling logic, and that logic can be written first, and then moved to upstream Samsung repository.

* About where to put the code, if I understood correctly, it seems that it can be placed in some personal repository first, and then we can discuss it later about where to put the code officially.
* And about existing CI solution, currently we are using travis CI. Please see https://github.com/Samsung/iotjs/blob/master/.travis.yml file for more details.
* And for the license issue, IoT.js is mainly shipped with Apache license. You can see https://github.com/Samsung/iotjs/blob/master/LICENSE for details.

And it will be helpful for us if you report your segfaults to our [issues](https://github.com/Samsung/iotjs/issues)
