### ISSUE TITLE
Enabling TLS or HTTPS fails on TizenRT

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#1660]
- On TizenRT, enabling TLS or HTTPS fails unlike described in the docs.
  - https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-TLS.md
  - https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-HTTPS.md
- Enabling tests for them is needed on https://samsung.github.io/iotjs-test-results/?view=artik053

**Comment by LaszloLango** [comment]
CC: @rtakacs

**Comment by LaszloLango** [comment]
This is fixed and it should work. Feel free to re-open if needed.
