### ISSUE TITLE
Crypto module

### ISSUE THREAD

**Issue by DanielBallaSZTE** [Samsung/iotjs#1705]
Currently the `WebSocket` implementation relies on `mbedTLS`'s hashing algorithms, namely `base64` and `sha1`.

At the implementation steps of the `WebSocket` module, I was already thinking about creating a minimized `crypto` module that could grow out as we need more and more functions, however didn't feel like doing it for only one module.

Now, that we would also need some sort of `crypto` for `HTTP Request Signature`, I have already started making it.
However, there is one question that arises:
Do we:
 - <b>strictly follow `Node.js`'s `crypto` API </b>
 - <b>create our own minimized module </b>?

For me, I would vote for the latter, since from my personal standpoint Node's implementation would be a heavy overkill for such a task.

With that said, I am all open for any suggestions about the question.

**Comment by DanielBallaSZTE** [comment]
For comparison:
Creating an sha hash in node.js:
```js
var hash = crypto.createHash('sha1');

hash.update('my string to hash');
console.log(hash.digest('hex'));
```

While we could have something as simple as:
```js
console.log(crypto.sha1_encode('my string to hash', hexOrBinary));
```

**Comment by daeyeon** [comment]
I totally agree with the approach to creating a minimized crypto module that could grow out for more needs. However, meeting nodejs style APIs seems better, IMO.

Their api looks to have a single responsibility (creating instances/updating contents)/calculating digests). Such a design could flexibly cope with many unexpected demands and could reduce code complexity for any case. 

I don't object to the idea of providing additional handy apis along with them.

**Comment by DanielBallaSZTE** [comment]
I'm closing this issue, thank you for your answer!
