### ISSUE TITLE
wish: version release

### ISSUE THREAD

**Issue by rzr** [Samsung/iotjs#1726]
Hi, 

Dear iotjs team,

Is there a new release planned soon ?
If not, may I suggested this.

The reason is that current master branch has really improved support for Tizen:Rt (which currently ship a snapshot before 1.0) since some downstream changes have been upstreamed.. so I guess it is valuable to upgrade snapshot in TizenRt.

Relate-to:

https://github.com/Samsung/TizenRT/pull/2018#issuecomment-412433508

Again this is just a suggestion, I don't want to change any plans.

https://github.com/Samsung/TizenRT/pull/2018#issuecomment-412433508

**Comment by daeyeon** [comment]
We do encourage suggestions for IoT.js but do not guarantee IoT.js which each individual applies to external projects. And, its acceptance is beyond our jurisdiction.

#1732 can answer your query about the plan. A selected version of the platform is applied to our CI before a release. That's for post-maintenance and would be the same for next release.
