### ISSUE TITLE
Modify IoT.js build on TizenRT

### ISSUE THREAD

**Issue by sunghan-chang** [Samsung/iotjs#1731]
Hello all.

I modified IoT.js build file on TizenRT.
https://github.com/Samsung/TizenRT/commit/bbd3cdbd498ff11eeca3f021496423cc0222497e
Originally it was in Makefile.unix and Makefile of external, not in IoT.js folder.
But module-specific content should be in each folder.
Except iotivity and iotjs, there is no module-specific content in Makefile.unix.

Because Kconfig is in config/tizenrt folder, I add Makefile in config/tizenrt.
Could you add that here as well? It makes easy to maintain.

Thanks
Sunghan

**Comment by haesik** [comment]
Hello, Thank you for the information. I have talked to the team members. Of course we agree with your suggestion. We will add the makefile in config/tizenrt when we release the latest IoT.js to TizenRT. Please wait until that time.

**Comment by rzr** [comment]
Relate-to: https://github.com/Samsung/iotjs/pull/1732
