### ISSUE TITLE
Complete process module

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#176]
https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Process
- [ ] Documentation
- [ ] Implementation
  - [x] event: exit
  - [x] event: uncaughtException
  - [x] process.argv
  - [x] process.exit()
  - [x] process.exticode
  - [x] ~~process.version~~
  - [x] process.arch
  - [x] process.platform
  - [x] process.nextTick()

**Comment by yichoi** [comment]
#1014 landed
