### ISSUE TITLE
Make ReqWrap template.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#190]
Many module implement its own request wrapper class inheriting `ReqWrap`. but it just add one field - specific request type of `uv_req_t`. So I think we can generalize it by using c++ template.

**Comment by seanshpark** [comment]
I do not agree on using c++ template.

**Comment by ILyoan** [comment]
@seanshpark Could you tell us why you disagree over using C++ template ?

**Comment by ILyoan** [comment]
Close as we had tentatively come to an agreement on using template from offline meeting.
But we can roll back any time when it's clear that using template is inappropriate for embedded environment.
