### ISSUE TITLE
IoT.js memory consumption

### ISSUE THREAD

**Issue by zherczeg** [Samsung/iotjs#212]
After applying https://github.com/Samsung/jerryscript/pull/611, and run the Freya tool I got some interesting results. The test file contained a single space. The following result is an excerpt:

[0] Peak: 56.6Kb (58016b) Allocs: 18404 Reallocs: 0 Total: 4.3Mb (4556210b).
Group: JerryScript

The peak memory consumption of Jerry is 56K.

    [0] Peak: 56.6Kb (58016b) Allocs: 18404 Reallocs: 0 Total: 4.3Mb (4556210b).
    Group: JerryScript
      [1] Group: jerry-core
        [2] Peak: 52.7Kb (54016b) Allocs: 16794 Reallocs: 0 Total: 4.3Mb (4541893b).
        Group: parser
          [3] Peak: 52.7Kb (54016b) Allocs: 16794 Reallocs: 0 Total: 4.3Mb (4541893b).
          Group: parser_js

From that, 52.7K is consumed by the parser

    [4] Peak: 32.5Kb (33344b) Allocs: 2426 Reallocs: 0 Total: 151.6Kb (155264b).
    scopes_tree_add_op_meta(scopes_tree_int*, op_meta) (jerry-core/parser/js/scopes-tree.cpp:69)
      [5] Peak: 25.0Kb (25600b) Allocs: 1381 Reallocs: 0 Total: 86.3Kb (88384b).
      serializer_dump_subscope(scopes_tree_int*) (jerry-core/parser/js/serializer.cpp:144)
        [6] Peak: 15.3Kb (15744b) Allocs: 822 Reallocs: 0 Total: 51.3Kb (52608b).
        serializer_dump_subscope(scopes_tree_int*) (jerry-core/parser/js/serializer.cpp:139)

I think scopes_tree_add_op_meta adds another opcode to some linked list.

    [4] Peak: 19.9Kb (20432b) Allocs: 10 Reallocs: 0 Total: 19.9Kb (20432b).
    serializer_merge_scopes_into_bytecode() (jerry-core/parser/js/serializer.cpp:164)
      [5] parser_parse_program(unsigned char const*, unsigned long, bool, bool, bool, vm_instr_t const**, bool*) (jerry-core/parser/js/parser.cpp:3193)
        [6] Peak: 19.8Kb (20376b) Allocs: 9 Reallocs: 0 Total: 19.8Kb (20376b).
        parser_parse_eval(unsigned char const*, unsigned long, bool, vm_instr_t const**, bool*) (jerry-core/parser/js/parser.cpp:3277)

I suspect serializer_merge_scopes_into_bytecode converts the linked list to another representation.

    [4] Peak: 2.5Kb (2560b) Allocs: 40 Reallocs: 0 Total: 2.5Kb (2560b).
    lexer_create_token_for_charset(token_type, unsigned char const*, unsigned int) (/home/hzoli/SamsungJS/
      [5] Peak: 1.7Kb (1792b) Allocs: 28 Reallocs: 0 Total: 1.7Kb (1792b).
      lexer_parse_identifier_or_keyword() (/home/hzoli/SamsungJS/iotjs/iotjs

The peak memory consumption of the next item is negligible, it is likely not worth to optimize it.

The rule of the peak memory consumption that they are generally not additive, since they might happen in different times. For example this is possible:

[1] Peak: 10K
  [2] Peak: 10K
  [2] Peak: 10K

In this case, the peaks happen in a different time, so the root node only consumes 10K. However, this is also possible:

[1] Peak: 20K
  [2] Peak: 10K
  [2] Peak: 10K

In this case the two child nodes reached their peak in the same time.

Hence the peak memory consumption of a root node is always >= than the peak memory consumption of any child node, and <= than the sum of the peak memory consumption of all child nodes.

The 52.7K memory consumption of the parser is pretty big, so I suspect the 32.5Kb and the 19.9Kb memory consumption happens in the same time.

My impression is that we generate too many byte-codes, or the byte-code generator infrastructure requires too much memory (inefficient linked list for example). We also noticed that the parser do heavy recursion. But that is another issue.

What do you think? Shall we invent a much more compact byte code format?

**Comment by zherczeg** [comment]
One more thing: Freya did not report any leak (only for the libuv submodule, i suspect tiotjs did not terminate that module) so the allocations / frees are correctly matched.

**Comment by seanshpark** [comment]
Interesting...
Can you profile iotjs with test js code with
```
var http=require('http');
```
?

**Comment by zherczeg** [comment]
Yes, here is the exceprt:

    [0] Peak: 132.3Kb (135476b) Allocs: 54935 Reallocs: 0 Total: 11.3Mb (11856309b).
    Group: JerryScript
      [1] Group: jerry-core
        [2] Peak: 84.2Kb (86312b) Allocs: 43755 Reallocs: 0 Total: 11.2Mb (11762750b).
        Group: parser
          [3] Peak: 84.2Kb (86312b) Allocs: 43755 Reallocs: 0 Total: 11.2Mb (11762750b).
          Group: parser-js
            [4] Peak: 51.5Kb (52824b) Allocs: 23 Reallocs: 0 Total: 51.5Kb (52824b).
            serializer_merge_scopes_into_bytecode()
            [...]
            [4] Peak: 48.7Kb (49920b) Allocs: 5897 Reallocs: 0 Total: 368.5Kb (377408b).
            scopes_tree_add_op_meta(scopes_tree_int*, op_meta)
            [...]
            [4] Peak: 8.2Kb (8448b) Allocs: 132 Reallocs: 0 Total: 8.2Kb (8448b).
            lexer_create_token_for_charset(token_type, unsigned char const*, unsigned int)
            [...]
        [2] Peak: 41.0Kb (42024b) Allocs: 7275 Reallocs: 0 Total: 57.0Kb (58385b).
        Group: jerry-other
          [3] Peak: 9.9Kb (10144b) Allocs: 1331 Reallocs: 0 Total: 10.3Kb (10648b).
          ecma_op_general_object_define_own_property(...)
            [4] Peak: 9.7Kb (9992b) Allocs: 1312 Reallocs: 0 Total: 10.2Kb (10496b).
            ecma_op_object_define_own_property(...)
            [...]
          [3] Peak: 3.4Kb (3520b) Allocs: 590 Reallocs: 0 Total: 4.6Kb (4720b).
          ecma_op_create_mutable_binding(ecma_object_t*, ecma_string_t*, bool)
          [... lots of small allocations here...]
        [2] Peak: 14.5Kb (14888b) Allocs: 3781 Reallocs: 0 Total: 33.1Kb (33910b).
        Group: vm
          [3] Peak: 3.1Kb (3208b) Allocs: 1080 Reallocs: 0 Total: 8.4Kb (8640b).
          opfunc_assignment(vm_instr_t, vm_frame_ctx_t*) 
          [... lots of small allocations here...]

The number of allocations increased a lot (18404 -> 54935) so the extra source parsing clearly added a lot of extra work. It seems both JavaScript objects and byte-code grow the memory a lot.

    [0] Peak: 22.2Kb (22835b) Allocs: 130 Reallocs: 0 Total: 157.5Kb (161347b) Leak: 32b.
    Group: IoT.js
      [1] Peak: 22.0Kb (22603b) Allocs: 46 Reallocs: 0 Total: 156.1Kb (159923b).
      iotjs::AllocBuffer(unsigned long)
        [2] iotjs::String::String(char const*, int, int)

It seems iot.js allocates space for the source buffer twice. Libuv allocates 128 byte (negligible).

**Comment by seanshpark** [comment]
@zherczeg , thank you. "iot.js allocates space for the source buffer twice" needs review.
I would like to repeat this and look inside more.

And I think this will surely  solve https://github.com/Samsung/iotjs/issues/213 task. I think reading https://github.com/Samsung/jerryscript/pull/602 can be a good starting point. Is there addition documents that can be a help ?

**Comment by zherczeg** [comment]
@seanshpark: regarding the double allocation:

    JHANDLER_FUNCTION(CompileNativePtr, handler) 
    {
       String source((const char*)handler.GetArg(0)->GetNative());
      JResult jres = WrapEval(source);
    }

And WrapEval also creates a copy:

   static JResult WrapEval(const String& source) {
    String code("", len1 + len2 + len3 + 1);     
   }

I think the WrapEval could accept a char* directly. Since sources are around 10K, this is 20K memory consumption.

What do you mean by "addition documents"?

**Comment by zherczeg** [comment]
Just for confirmation I printed the byte-code sizes when loading the http submodule.

bytecode-size: 24 (total: 24), lit-table-size: 32 (total: 32)
bytecode-size: 2432 (total: 2456), lit-table-size: 760 (total: 792)
bytecode-size: 472 (total: 2928), lit-table-size: 160 (total: 952)
bytecode-size: 1328 (total: 4256), lit-table-size: 448 (total: 1400)
bytecode-size: 2848 (total: 7104), lit-table-size: 832 (total: 2232)
bytecode-size: 1344 (total: 8448), lit-table-size: 400 (total: 2632)
bytecode-size: 2456 (total: 10904), lit-table-size: 840 (total: 3472)
bytecode-size: 4264 (total: 15168), lit-table-size: 1392 (total: 4864)
bytecode-size: 160 (total: 15328), lit-table-size: 72 (total: 4936)
bytecode-size: 128 (total: 15456), lit-table-size: 64 (total: 5000)
bytecode-size: 352 (total: 15808), lit-table-size: 144 (total: 5144)
bytecode-size: 3032 (total: 18840), lit-table-size: 952 (total: 6096)
bytecode-size: 6376 (total: 25216), lit-table-size: 1920 (total: 8016)
bytecode-size: 304 (total: 25520), lit-table-size: 136 (total: 8152)
bytecode-size: 2512 (total: 28032), lit-table-size: 720 (total: 8872)
bytecode-size: 1296 (total: 29328), lit-table-size: 496 (total: 9368)
bytecode-size: 2432 (total: 31760), lit-table-size: 768 (total: 10136)
bytecode-size: 464 (total: 32224), lit-table-size: 184 (total: 10320)
bytecode-size: 1680 (total: 33904), lit-table-size: 504 (total: 10824)
bytecode-size: 640 (total: 34544), lit-table-size: 200 (total: 11024)
bytecode-size: 1752 (total: 36296), lit-table-size: 480 (total: 11504)
bytecode-size: 1240 (total: 37536), lit-table-size: 488 (total: 11992)
bytecode-size: 2400 (total: 39936), lit-table-size: 896 (total: 12888)

Freya was right, the total is really 52K. And we keep this (unlike the parser memory allocation).

**Comment by seanshpark** [comment]
@zherczeg , thank you for pointing the code. 
"addition documents" not literally but I see https://github.com/szeged/Freya page but didn't look inside the  codes yet and there's nothing in wiki page, so as not good at memory analysis and optimisation, it could be a help to me if you can add some links that I can study.

**Comment by zherczeg** [comment]
The explanation is here: http://webkit.sed.hu/node/29

I can copy here the configuration we are using if you are interested.

**Comment by seanshpark** [comment]
Yes, please attach the configuration. I'll study and try out Freya.

**Comment by zherczeg** [comment]
Here is my current config:

```
# discarded allocations
-                  jerry-core/mem
-                  jerry-core/ecma/base
-                  jerry-core/lit
-                  jerry-core/parser/js/collections
-                  jerry-core/rcs
-                  m_replacemalloc
-                  (mmap)

#JerryScript
parser-bc1         (serializer_merge_scopes_into_bytecode)
parser-bc2         (scopes_tree_add_op_meta)
objects1           ecma-objects-general.cpp
objects2           ecma-objects.cpp
functions          ecma-function-object.cpp
parser-js          jerry-core/parser/js
parser-regex       jerry-core/parser/regexp
builtins           jerry-core/ecma/builtin-objects
vm                 jerry-core/vm
jerry-other        jerry-core
libc               eglibc-2.19
iotjs              iotjs/src

# group for total consumption
[JerryScript]
  [jerry-core]
    [parser]
      [parser-sub]
         {parser-bc1}
         {parser-bc2}
      (parser-js)
      (parser-regex)
    [objects]
      [objects-sub]
        {objects1}
        {objects2}
      (functions)
    (builtins)
    (vm)
    (jerry-other)

[IoT.js]
  {iotjs}

(libc)

# Everything else
[other]+
```

You need to use the latest Jerry, apply https://github.com/Samsung/jerryscript/pull/611, enable valgrind support, and compile iot.js in debug mode. Your libc might be different from eglibc-2.19, you should modify that rule then.

**Comment by seanshpark** [comment]
@zherczeg , Thanks !
