### ISSUE TITLE
GPIO 'write', 'read' event.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#217]
Our [GPIO API](https://github.com/Samsung/iotjs/wiki/IoT.js-API:-GPIO) does not declare 'write' and 'read' event for inform result of 'writePin' and 'readPin' operations, respectively.

From PR #215, request for the 'write' event was raised.

Let's discuss about it in this thread.

**Comment by ILyoan** [comment]
According to the API ref. The prototype of `writePin` is:
```
gpio.writePin(pinNumber: Number, value: Boolean [, callback: Function(err: Error)])
```

Here callback function is optional, and only feeds error information via parameter since the pin number and value are obvious. 

If we decide to provide 'writePin' event for result of the operation. prototype of the event will be:

```
event: writePin(pinNumber: Number, value:Boolean)
```

The event will be emitted after writing operation finished successfully. Hence `error` parameter would not be needed. `pinNumber` and `value` are needed.

We can provoide 'writePort' event for `writePort()` operation in similar manner.

**Comment by ILyoan** [comment]
For view point of API consistency:

I think GPIO has similar operations with Filesystem which has `read(fd, buffer, callback)` and `write(fd, buffer ,callback)`. But file system does not provide 'read' and 'write' event.

**Comment by ILyoan** [comment]
What about providing `watch(pinNumber)` and 'event: change' ?

**Comment by chunseoklee** [comment]
For API consistency, providing xxxSync functions and removing async events  seem to be better. 
But, if breaking API consistency is OK, it would be nice to provide many options(events) for user convenience.

**Comment by ILyoan** [comment]
@chunseoklee  I think providing xxxSync functions for sync mode operation is necessary regardless of API consistency.

**Comment by ILyoan** [comment]
@chunseoklee No problem with emitting 'writePin' event when writePin finishes.

A question makes me reluctant is that emitting 'writePin' event after `writePinSync()` sounds odd to me.
Also I'm not sure about emitting 'writePin' only after asynchronous 'writePin()' is OK.

**Comment by chunseoklee** [comment]
Agree with emitting 'writePin' event only after async writePin: `event: writePin(pinNumber: Number, value:Boolean)`

**Comment by ILyoan** [comment]
Closing
