### ISSUE TITLE
shutdown() not supported by NuttX

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#229]
`socket shutdown()` function doesn't exist in NuttX nor has plan to implement in near future.
http://pubs.opengroup.org/onlinepubs/009695399/functions/shutdown.html
thus `uv_shutdown` will not work and may have to change current implementation.

**Comment by seanshpark** [comment]
I can think of these cases.
* Add `shutdown()` to NuttX: 
   * It the tail wagging the dog. Should we?
* Redesign `net` without using `shutdown()`
   * May have to drop compatibility with node.js
* Move to platform that supports `shutdown()`
   * So, which one? `mbed` also doesn't seem to support `shutdown()`

embed as of today, supports these IP APIs (https://github.com/ARMmbed/sal)
```
struct socket_api {
    socket_stack_t              stack;
    uint32_t                    version;
    socket_init                 init;
    socket_create               create;
    socket_destroy              destroy;
    socket_close                close;
    socket_periodic_task        periodic_task;
    socket_periodic_interval    periodic_interval;
    socket_resolve              resolve;
    socket_connect              connect;
    socket_str2addr             str2addr;
    socket_bind                 bind;
    socket_start_listen         start_listen;
    socket_stop_listen          stop_listen;
    socket_accept               accept;
    socket_reject               reject;
    socket_send                 send;
    socket_send_to              send_to;
    socket_recv                 recv;
    socket_recv_from            recv_from;
    socket_is_connected         is_connected;
    socket_is_bound             is_bound;
    socket_get_local_addr       get_local_addr;
    socket_get_remote_addr      get_remote_addr;
    socket_get_local_port       get_local_port;
    socket_get_remote_port      get_remote_port;
};
```

**Comment by chokobole** [comment]
close since [commit](https://bitbucket.org/nuttx/nuttx/commits/8a87e3ca6e29c4de5ab0dcb3edb806cf88dddbec) landed. (But this is an empty function.)
