### ISSUE TITLE
Enable running unittests on STM32F4 target board

### ISSUE THREAD

**Issue by lemmaa** [Samsung/iotjs#237]

**Comment by ILyoan** [comment]
To accomplish this mission we need:
- [ ] Special build host machine connected with STM32F4 target device.
- [ ] Mechanism to trigger build action.
- [ ] Unit test descriptor that describes which target the test should be done.
- [ ] Modified build script.
  - [ ] Make connection with target device.
  - [ ] Copy test files.
  - [ ] Run test on target device.
  - [ ] Report result.
- [ ] Reporting tool.

**Comment by yichoi** [comment]
Closing since #450 landed. now we can test with JavaScript driver
