### ISSUE TITLE
File read/write check on STM32F4 with NuttX

### ISSUE THREAD

**Issue by lemmaa** [Samsung/iotjs#240]

**Comment by ILyoan** [comment]
Check list:
- [ ] fs.open()
- [ ] fs.close()
- [ ] fs.read()
- [ ] fs.write()
- [ ] fs.readFile()
- [ ] fs.writeFile()

**Comment by chunseoklee** [comment]
tested on master (5ddddcc3172918ce).
open, read, readFile works fine.

**Comment by chokobole** [comment]
Close since tested running js driver(#472) on nuttx. if the path  is an absolute path, it works well.
