### ISSUE TITLE
Problem with build for stm32

### ISSUE THREAD

**Issue by mulderp** [Samsung/iotjs#244]
Hi,

I am trying to follow the instructions for the STM32F4 build.
I tried virtual machines with Ubuntu 14.04 and Debian Jessie.

In both cases I get:

```
configure.ac:27: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:110: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf failed with exit status: 1
````

when I try to run:

    root@vagrant-ubuntu-trusty-64:/home/vagrant/kconfig-frontends# ./bootstrap

Maybe the guide misses some `apt-get install ...` command?

**Comment by mulderp** [comment]
solved when installing pkg-config http://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error

**Comment by mulderp** [comment]
also useful to run make menuconfig:

         apt-get install ncurses
        apt-get install libncurses-dev

**Comment by mulderp** [comment]
Another problems comes when doing `make` in the nuttx project:

     make: *** No rule to make target `lib/libuv.a', needed by `pass2deps'.  Stop.

**Comment by seanshpark** [comment]
Thanks, it'll help others with same problem.
