### ISSUE TITLE
A problem in building the target.

### ISSUE THREAD

**Issue by GrowingM** [Samsung/iotjs#250]
When I build the target with ./tools/build.py, there is a problem as follows:

Cloning into 'deps/http-parser'...
remote: Counting objects: 1360, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1360 (delta 0), reused 0 (delta 0), pack-reused 1357
Receiving objects: 100% (1360/1360), 279.94 KiB | 65.00 KiB/s, done.
Resolving deltas: 100% (910/910), done.
Checking connectivity... done.
fatal: reference is not a tree: 7e1178d99af814a208c6f8b6b604d58f96dcd3b0

Unable to checkout '7e1178d99af814a208c6f8b6b604d58f96dcd3b0' in submodule path 'deps/http-parser'

[Failed - 1] git submodule update

It's also occured in building STM32F407.

How to solve the problem？ 
thanks

**Comment by chunseoklee** [comment]
@GrowingM It is solved now on master branch.

**Comment by GrowingM** [comment]
Thanks a lot!

**Comment by GrowingM** [comment]
@chunseoklee Thanks a lot!

**Comment by seanshpark** [comment]
Closing since solved.
