### ISSUE TITLE
Need to check uv_loop_close return value

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#256]
As for patch #252 now closes loop but needs to check the return value.
`uv_loop_close` may return `UV_EBUSY` if some handle is still active.

```
   // close uv loop.
-  uv_loop_close(env->loop());
+  IOTJS_ASSERT(uv_loop_close(env->loop()) == 0);
```

But with this change, most of the unit test fails to pass. We need to check all of them.

**Comment by ILyoan** [comment]
PR #254 fixes this.

**Comment by ILyoan** [comment]
Closing as #254 landed.
