### ISSUE TITLE
Not implemented required uv API on tuv

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#258]
#254 need following uv API for releasing active resources during finishing program.

* uv_is_closing()
* uv_work()

**Comment by seanshpark** [comment]
Cannot find uv_work() in libuv. Do you mean uv_queue_work() ?

**Comment by ILyoan** [comment]
@seanshpark 
Sorry It was uv_walk().

**Comment by seanshpark** [comment]
Added to libtuv master done.
