### ISSUE TITLE
Remove previous build directory before start new build.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#269]
Currently, build system intentionally reuses output from previous build to reduce build time. 
But sometimes it affects build result especially build option was different from previous one.

As build process does not consume much time. I think we can clean previous build result up and trigger clean build.

**Comment by lemmaa** [comment]
@ILyoan , I think 'make clear' is better in such case. :)

**Comment by ILyoan** [comment]
@lemma I think make clean is already there.
What I'm saying is about using "build.py" tools that automates build processes for easy build.
And I'm suggesting something like 'make clean' before building project when using the tool by default.

**Comment by seanshpark** [comment]
@ILyoan , I think calling `make clean` before building  will clean the problem and current build time is just several minutes. But before doing that, can you describe what `especially build option was different from previous one` is?
We might solve the problem in another way so that not hurt the build time.

**Comment by ILyoan** [comment]
@seanshpark It's weird it takes less than 10 seconds to build in my PC. only build time, excluding unit tests.

Anyway, we can also 'make clean' before start build. but as "build.py" creates build directory for out of source build. make clean also will delete almost every file in that directory except CMake caches. so I think remove hole directory at once and start new build from the beginning is much efficient and safe way to clean build.

Adding option something like "--clean" to build.py to clean build is OK for you? without the option given, build time will remain the same.

**Comment by seanshpark** [comment]
I just want to know what you are talking about `But sometimes it affects build result especially build option was different from previous one.`

**Comment by ILyoan** [comment]
@seanshpark We can pass CMAKE options and make options via 'cmake-option' and 'make-flags' respectively when building with "build.py". And putting different options for each build sometimes give me back not  a expected build result appliying previous options. I think the problem should occur during mis-treating these parameters but I'm not sure which part is the problem.
Caching in build.py script might be a source of the problem. So I'm considering removing the caching too. since sometimes it takes too much time to finally realize the build was not completed correctly(It sometimes takes more than several hours) comparing to little lose of building from scratch(few seconds for each build).

**Comment by lemmaa** [comment]
@ILyoan, I think it's not bad that we have alternative way to remove all outputs at once, not only controlled by 'make'.

**Comment by ILyoan** [comment]
`build.py --clean` do this.
Closing.
