### ISSUE TITLE
Implement GPIO by libmraa, which can directly operate the board pins in Edison Board and others

### ISSUE THREAD

**Issue by jiangzidong** [Samsung/iotjs#272]
IoTjs is designed for iot device, so the GPIO is one of the main features. Now the linux gpio has a general impl, which directly operate the gpios in kernel. While the mapping between kernel's gpio and physical gpio in board is difficult and varies with different embedded board, so we propose to import mraa into IoTjs and let mraa handle the mapping work. (https://github.com/intel-iot-devkit/mraa)

The codes are in https://github.com/jiangzidong/iotjs/tree/mraa_enable.
**Should I just directly create a pull request, and let's discuss there?** or stay in this issue? I think PR is easy to review the code.

1, We add a file : iotjs_module_gpio-linux-mraa.inl.h, which is parallel with iotjs_module_gpio-linux-general.inl.h. **The GPIO API is not changed**. Users can choose suitable implementation by the building option. 
```
./tools/build.py --mraa
```
2, Gpio-linux-mraa implement export, unexport, setpin, readpin, writepin with mraa api. Then the users can operate board gpio pin directly. For example, to turn on the LED in Edison Arduino Board.
```javascript
var gpio = require("gpio");
gpio.initialize(init_done);
function init_done() {
  print("init done!");
  gpio.setPin(13, "out", set_done);// the led is in the board pin 13
}
function set_done() {
  print("set done!");
   gpio.writePin(13, 1);
}
```
if the users operate the kernel gpio to turn on the led, they may need to refer the handbook and handle more than 5 gpios. see example in http://www.emutexlabs.com/project/215-intel-edison-gpio-pin-multiplexing-guide.

3, The libmraa is a **dinamic** libraries and is included in the official Edison/Galileo image. We add mraa as a submodule, and only build it for link. So the final `iotjs` doesn't have any mraa codes. It can run in the linux env with libmraa, such as Edison board. Building iotjs for Edison is easy. i686 version can run directly in Edison. In the host PC(no matter 32bit or 64bit), `./tools/build.py --mraa --target-arch=i686`, then copy the binary `iotjs` into Edison board.

**Comment by seanshpark** [comment]
@jiangzidong , Thank you. I think it's nice to use `mraa` for gpio control. Hope to see others opinion also.
I think it's ok to discuss in this issue as it is created and when ready, make a PR referencing this.

I glanced your changes and wondered if we can use `target-board` option to distinguish (for same intel+linux) or (I'm not used to mraa) can we use mraa to other core + os ?
maybe putting in `deps` can depend on this, but this is my thought.

About the code, in `cmake/iotjs.cmake` 
```
-                     ${HTTPPARSER_INCDIR})
+                     ${HTTPPARSER_INCDIR}
+                     ${MRAA_INCDIR})

-    ${LIBUV_LIB} ${HTTPPARSER_LIB})
+    ${LIBUV_LIB} ${HTTPPARSER_LIB} ${MRAA_LIB})
```
and also in `cmake/iotjstuv.cmake`, needs to be fixed so that it is linked only when option is enabled.

**Comment by jiangzidong** [comment]
@seanshpark, Thank you for your advice. 
1) I think the code in `iotjs.cmake` and `iotjstuv.cmake` can run correctly whatever the mraa is enabled or not. If it is not enabled, the mraa.cmake will not included, so `MRAA_INCDIR` and `MRAA_LIB` is undefined and empty. But I am a newbie of cmake, I'm not sure whether there is hidden trouble.

2)I thought about the `target-board` before, but mraa is cross-platform from arm(Raspberry Pi, BB..) to x86(Edison, Galileo,...). Different boards and archs can use mraa, so I give it a separate option and let users to choose.
But your way is also reasonable. When the `target-board` is in some "mraa-support" list, (e.g. Edison), the building process will enable mraa automatically. I am totally okay with that.

**Comment by seanshpark** [comment]
@jiangzidong , for 1) it seems OK to add  `MRAA_INCDIR` and `MRAA_LIB` as you wrote. I think you've already checked and we can also check when PR is available.
2) So MRAA is available to most linux then letting it as an option as you proposed seems reasonable.
I wish to read comments from others and if you are not in a hurry we can wait for a day or two for the PR. Thanks.

**Comment by seanshpark** [comment]
@jiangzidong , I was thinking a while about adding `mraa` in `deps` and it should be considered as optional and removed, as IoT.js  primary targets devices with RTOS and less than a mega bytes of memory or so and cannot use `mraa`.  And thus for 1) adding `MRAA_INCDIR` and `MRAA_LIB` also to an option. Current code may mislead that `mraa` is a default library.

**Comment by jiangzidong** [comment]
@seanshpark 
1) Yes, I can put `MRAA_INCDIR` and `MRAA_LIB` into a `if-else`block in `iotjs.cmake`

2) About the `deps` problem, do you mean that the iotjs project **don't** compile the libmraa, and users who need to use should prepare the .so and .h (for example, put those file into a specific dirs). When the mraa enabled, iotjs will search the related files in the dir and link to it. Am I right?

**Comment by seanshpark** [comment]
@jiangzidong , 2) Yes, correct. As you wrote this can be inconvenient and may bring errors by version mismatch. So I want to hear from others.

**Comment by jiangzidong** [comment]
@seanshpark Should I PR now? We can using the external-include-dir and external-shared-lib in #273 (https://github.com/Samsung/iotjs/wiki/Build-Script) to put the mraa .h and .so files.

**Comment by seanshpark** [comment]
@jiangzidong , last comment I've wrote disappeared. strange, it's second time. anyway, sorry for late response. we had a f2f meeting last week in our office and ILyoan will prepare something so that you can merge this. can you please wait for sometime(don't know exactly how long) ?

**Comment by seanshpark** [comment]
@jiangzidong , sorry I've closed and reopened. clicked wrong button.

**Comment by jiangzidong** [comment]
@seanshpark Never mind. Could you please remind me when your preparations are done. Thanks

**Comment by seanshpark** [comment]
@jiangzidong , Yes sure.

**Comment by seanshpark** [comment]
@jiangzidong , please look inside #281. If you need something, please add comments to #281

**Comment by jiangzidong** [comment]
@seanshpark Thanks, #281 already provides the external-include-dir and external-shared-lib options.
After it merge, My patch will 1) add the mraa option, 2) let the users to prepare the corresponding header and shared lib, which are matched to the lib version in their target board.

**Comment by ILyoan** [comment]
@jiangzidong Your approach corresponds with the intention of #281. 

We are cautious about adding options to build script, since while adding an option is relatively easy, removing one might difficult for compatibility issue. So, in my opinion, It would be better to choose GPIO implementation via compile-flag. Afterward mraa become prevalent, it'll still no late to add an option for it.

And `external-shared-lib` is removed in recent PR, since I think it could be coverd by `link-flag`. If I was wrong please let me know.

**Comment by jiangzidong** [comment]
@ILyoan I agree with you.
`compile_flag` can send "MRAA marco define" to compiler, and `link-flag` can set "-Lxxx" “-lxxx” to link libmraa

**Comment by ILyoan** [comment]
@jiangzidong Thanks.
#281 is landed, please go ahead with your patch.
Hope to see mraa landing :)

**Comment by jiangzidong** [comment]
@ILyoan I met a problem when link mraa using `--link-flag`
--link-flag use the -DCMAKE_EXE_LINKER_FLAGS to pass the flag, while the library order is wrong.
```
Linking CXX executable iotjs
liblibiotjs.a(iotjs_module_gpio-i686-linux.cpp.o): In function `iotjs::GpioLinuxMraa::_ExportPin(int)':
/home/jzd/iotjs/src/platform/i686-linux/../iotjs_module_gpio-linux-mraa.inl.h:83: undefined reference to `mraa_gpio_init'
liblibiotjs.a(iotjs_module_gpio-i686-linux.cpp.o): In function `iotjs::GpioLinuxMraa::_UnexportPin(int)':
/home/jzd/iotjs/src/platform/i686-linux/../iotjs_module_gpio-linux-mraa.inl.h:95: undefined reference to `mraa_gpio_close'
liblibiotjs.a(iotjs_module_gpio-i686-linux.cpp.o): In function `iotjs::GpioLinuxMraa::_SetPinDirection(int, iotjs::GpioDirection)':
/home/jzd/iotjs/src/platform/i686-linux/../iotjs_module_gpio-linux-mraa.inl.h:114: undefined reference to `mraa_gpio_dir'
/home/jzd/iotjs/src/platform/i686-linux/../iotjs_module_gpio-linux-mraa.inl.h:116: undefined reference to `mraa_gpio_dir'
liblibiotjs.a(iotjs_module_gpio-i686-linux.cpp.o): In function `iotjs::GpioLinuxMraa::_WritePin(int, bool)':
/home/jzd/iotjs/src/platform/i686-linux/../iotjs_module_gpio-linux-mraa.inl.h:143: undefined reference to `mraa_gpio_write'
liblibiotjs.a(iotjs_module_gpio-i686-linux.cpp.o): In function `iotjs::GpioLinuxMraa::_ReadPin(int, int*)':
/home/jzd/iotjs/src/platform/i686-linux/../iotjs_module_gpio-linux-mraa.inl.h:158: undefined reference to `mraa_gpio_read'
collect2: error: ld returned 1 exit status
make[2]: *** [iotjs] Error 1
make[1]: *** [CMakeFiles/iotjs.dir/all] Error 2
make: *** [all] Error 2

[Failed - 2] make -j

```


My command is as follows
```./tools/build.py --compile-flag="-DUSING_MRAA" --external-include-dir="../iotm/" --clean --link-flag="-lmraa"
```
will link error, in ./build/i686-linux/debug/iotjs/CMakeFiles/iotjs.dir/link.txt
```
./build/i686-linux/debug/iotjs/CMakeFiles/iotjs.dir/link.txt:/usr/bin/c++   -D__LINUX__ -fno-builtin -D__i686__ -D__x86__ -D__I686__ -D__X86__ -march=i686 -m32 -g -DDEBUG -DENABLE_DEBUG_LOG -DUSING_MRAA -std=c++11 -fno-exceptions -g  -pthread -lmraa -pthread -lmraa CMakeFiles/iotjs.dir/iotjs_linux.cpp.o  -o iotjs -rdynamic liblibiotjs.a ../lib/libjerrycore.a ../lib/libtuv.a ../lib/libhttpparser.a
```
the `-lmraa` appear before liblibiotjs, it should after that.

if I modify the libtuv.cmake, `  target_link_libraries(${targetName} libiotjs ${JERRY_LIB}
    ${LIBTUV_LIB} ${HTTPPARSER_LIB} "mraa")`. It will build correctly

**Comment by ILyoan** [comment]
@jiangzidong I see, you are right.
Could you add `external_shared_lib` feature in your PR with separate commit?

**Comment by jiangzidong** [comment]
@ILyoan @seanshpark Could you please review the PR #295. Thanks!
