### ISSUE TITLE
To enable LTO for iotjs.

### ISSUE THREAD

**Issue by huxinx** [Samsung/iotjs#274]
The current IoT.js is build without LTO.
From my watching, after enable LTO,
we get a iotjs binary with shrunk binary size and boosting performance.

Here is SunSpider 1.0.2 data I collected on ubuntu 15.04 32-bit, ATOM system,
first column is LTO ON, the second is LTO OFF data.                                        

3d-cube.js.......................1.475........9.782
access-binary-trees.js.....1.167........4.998
access-fannkuch.js.........3.803........26.549
access-nbody.js.............uncaughtException..uncaughtException
bitops-3bit-bits-in-byte.js.1.494........9.407
bitops-bits-in-byte.js	........1.827........13.518
bitops-bitwise-and.js........1.503........11.637
controlflow-recursive.js....1.828.........6.407
date-format-xparb.js........2.177.........5.432
math-cordic.js..................1.902........13.313
math-partial-sums.js.........uncaughtException..uncaughtException
math-spectral-norm.js......1.351.........8.024
string-fasta.js....................6.824........15.988

binary size ,
1.0M    iotjs.on  // LTO ON
2.5M    iotjs.off  // LTO OFF

Since LTO introduces so many benefits,  shall it be enabled ?

**Comment by egavrin** [comment]
LTO build is a very useful feature. So, I'd strongly vote for adding this by default.
Could you please create pull request enabling LTO?

**Comment by bzsolt** [comment]
We investigated this issue nowadays, and the conclusion was the same as you wrote.
I agree with @egavrin, it would be good to enable it.
I've created a PR for this, please check it: #275

**Comment by egavrin** [comment]
@bzsolt great!

**Comment by seanshpark** [comment]
Have you tried building and testing for NuttX / STM32F4-discovery?

**Comment by huxinx** [comment]
I do not have STM32F4-discovery at this moment. For my experience, on x86, with gcc 4.9, just enable jerry_cmake_opt.append('-DENABLE_LTO=ON' is fine. With gcc 4.8, need to send extra flag '-flto' , other introduces link error. Maybe you can try to use another version gcc.

**Comment by huxinx** [comment]
https://github.com/Samsung/iotjs/compare/master...huxinx:lto

@bzsolt @seanshpark @egavrin 
Here is my solution, add a switch for lto in build.py
the default config is still LTO=OFF,
turn on lto with --lto

**Comment by huxinx** [comment]
Since 275 has been merged, please close this one.
