### ISSUE TITLE
Discussion about current reference target board(STM32F4)

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/iotjs#277]
I would like to hear opinions about our ref target board.
Based on my personal (demonstration) experience in OSCON/SOSCON, most developers were not interest in STM-like board. The most mentioned board is ARDUINO. 
If we switch(or extend) our ref board to more popular board like arduino, it would be easy to distribute iot.js. 
To do that, we have to resolve the following issues:

1. Memory : other board has less memory than STM32F4
2. System Call(libuv) : libuv depends on POSIX system call(poll, ...)

**Comment by seanshpark** [comment]
As reference board, I think it is ok using STM boards. 
For expanding supporting boards, Arduino is a good device but needs issues to solve... so search a little bit and got this;
1. Expanding RAM with SPI: http://playground.arduino.cc/Main/SpiRAM . We can use this memory for JerryHeap with some(or lots of) modification. Speed will definitely degrade.
2. There is multi-loop experiment: https://www.arduino.cc/en/Reference/Scheduler . But no task synchronization. Need more search like using FreeRTOS in Arduino...

**Comment by samuel-xu** [comment]
Is it possible that “Intel® Edison Kit for Arduino” can be one of the targets?

Some pros, e.g:
•         Easy to get from market(e.g. https://www.arduino.cc/en/ArduinoCertified/IntelEdison#toc3) , has Arduino capacity and beyond
•         No need to expand memory  ( the only possible extra need is a Edison IO Expansion Shield for Arduino http://www.avrcircuit.com/shop/product.php?id_product=29,  if user really want to connect Edison with physical peripheral )
•         Full Linux OS environment , no system call concern (in fact, target Linux is very similar with host dev environment, and many Linux tool can be re-use)
•         Good integration on wifi, BT, flash memory, SDRAM, serial port, USB host..etc
•         Edison listed in https://github.com/Samsung/iotjs/wiki/Getting-Started, set is as one of targets can make it from “plan” to “practice” :)

**Comment by zherczeg** [comment]
Definitely porting Jerry to Edison is easy, since it has 1G RAM. But our focus is systems with very low memory (64-128K), where no other engine (V8, etc.) is capable of running. Is there other Edison Kits with such amount of memory?

**Comment by diorahman** [comment]
Good news on supporting Arduino!

**Comment by yichoi** [comment]
Current reference targets are STM32F4Discovery and Raspberry Pi 2. If further discussion needed please reopen it again.
