### ISSUE TITLE
Complete fs module

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#28]
Complete implementation of [fs module](https://github.com/Samsung/iotjs/wiki/IoT.js-API:-File-System).

Required Items:
- [ ] ~~fs.access()~~
- [ ] ~~fs.accessSync()~~
- [x] ~~fs.exist() (deprecated)~~
- [x] ~~fs.existSync() (deprecated)~~
- [x] fs.stat()
- [x] fs.statSync()
- [ ] ~~fs.chmod()~~
- [ ] ~~fs.chmodSync()~~
- [ ] ~~fs.chown()~~
- [ ] ~~fs.chownSync()~~
- [x] fs.rename()
- [x] fs.renameSync()
- [x] fs.close()
- [x] fs.closeSync()
- [x] fs.open()
- [x] fs.openSync()
- [x] fs.read()
- [x] fs.readSync()
- [x] fs.readFile()
- [x] fs.readFileSync()
- [x] fs.write()
- [x] fs.writeSync()
- [x] fs.writeFile()
- [x] fs.writeFileSync()
- [ ] ~~fs.appendFile()~~
- [ ] ~~fs.appendFileSync()~~
- [ ] ~~fs.truncate()~~
- [ ] ~~fs.truncateSync()~~
- [x] fs.mkdir()
- [x] fs.mkdirSync()
- [x] fs.rmdir()
- [x] fs.rmdirSync()
- [x] fs.readdir()
- [x] fs.readdirSync()
- [x] fs.unlink()
- [x] fs.unlinkSync()

**Comment by glistening** [comment]
I checked File System's basic APIs works in our main supporting platforms. So I close it.
