### ISSUE TITLE
Supporting libtuv as base async I/O library and removing libuv

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#283]
There are two options for asynchronus I/O supporting - libuv and libtuv.

Current build system takes libuv by default, but we are maintaining libtuv more actively. For example, we can build IoT.js for arm-nuttx-stm32f4dis with libtuv, while can not with libuv.

I think it is reasonable to select libtuv as default async I/O library, and furthermore, even removing libuv from our source tree is also considerable.

**Comment by seanshpark** [comment]
Agree, +1

**Comment by lemmaa** [comment]
Agree, +1

**Comment by ILyoan** [comment]
Apparently, #281 was landed and it already regards tuv as primary library.
So the first proposal has been already applied.

**Comment by poussa** [comment]
It would have been nice to keep the libuv as a build option. I can't build libtuv for OS X but libuv I can. Thus, one can't build iot.js for darwin target. Or should this (iotjs build for darwin) be possible?

**Comment by hs0225** [comment]
need to documents update about libtuv option. refer to [fetch](https://github.com/Samsung/iotjs/pull/382)

**Comment by yichoi** [comment]
Closing since libtuv is default async I/O library.
