### ISSUE TITLE
Have snapshot branch merged.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#284]
Using snapshot feature is inevitable to run IoT.js on STM32F4. 

The development branch is:
https://github.com/Samsung/iotjs/tree/snapshot-dev

Let's make it merged

**Comment by ILyoan** [comment]
PR: #286

**Comment by ILyoan** [comment]
Close as #286 landed

**Comment by jiangzidong** [comment]
@ILyoan I just curious about what's your mean by "inevitable"? Snapshot will saving the parsing time for native js libs and decrease the ram size of storing the code. Am I right?

**Comment by ILyoan** [comment]
@jiangzidong Yes you are right. more precisely, parsing native modules requires large amount of memory that exceeds memory capacity provided by STM32F4 board that we need to parse native modules in advance.
