### ISSUE TITLE
deps/jerry fails to build in 32bit

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#287]
Got this error in Ubuntu 32bit, code: 80ebc7d94a8662d1e8bda0d7b095772405793aae
```
CMake Error at jerry-libc/CMakeLists.txt:113 (message):
  Unsupported machine architecture
```
`${CMAKE_SYSTEM_PROCESSOR}` is `i686` but was `x86`

**Comment by jiangzidong** [comment]
@seanshpark sorry that I didn't notice this issue. I just opened a PR #288 to fix it. I choose to change the set(CMAKE_SYSTEM_PROCESSOR i686) in cmake/config/i686-linux.cmake to set(CMAKE_SYSTEM_PROCESSOR x86).

Should I close that PR?

**Comment by seanshpark** [comment]
@jiangzidong , I think using `uname -p` that is `i686` would be better. You can close #288.
