### ISSUE TITLE
libtuv uv__eventfd2 failed at MIPS 

### ISSUE THREAD

**Issue by gridnow** [Samsung/iotjs#296]
libtuv uv__eventfd2 failed at MIPS , which is called at uv__async_eventfd durring initializing process.

**Comment by seanshpark** [comment]
@gridnow , can you please tell me how to reproduce this?
Compiler version, how to get that compiler, host, target, etc, so that I can check.

**Comment by gridnow** [comment]
@seanshpark , I found out that uv__eventfd2 faile on MIPS is caused by invalidate  UV__O_NONBLOCK value, patch file :https://github.com/gridnow/libtuv/commit/f11fcee13dc492ffeb3f2e169413b140d12d767a

Could this patch be merged into trunck? 
And I will work out additional patchs for running iotjs on MIPS (compiler configure, options ,etc) .

**Comment by seanshpark** [comment]
@gridnow , yes please post a PR :)

**Comment by gridnow** [comment]
@seanshpark but waht is PR? 
thanks!

**Comment by gridnow** [comment]
@seanshpark done!
