### ISSUE TITLE
compile function too slow

### ISSUE THREAD

**Issue by gridnow** [Samsung/iotjs#297]
I have traced to this function which take so much time (about 1 second)on MIPS at starting up a simple hello world:

212   Native.prototype.compile = function() {
213     // process.native_sources has a list of pointers to
214     // the source strings defined in 'iotjs_js.h', not
215     // source strings.
216     var source = process.native_sources[this.id];
217     var fn = process.compileNativePtr(source);
218     fn(this.exports, Native.require, this);
219   };
220 
221 
222   // temp impl. before JSON.parse is done
223   process.JSONParse = function(text) {
224     return JSON.parse(text);
225   };

And find out that it's compile a "fs" module.(this.id is fs). fs.js only has 312 lines!!!

Anybody has some idea to speed up this process?

**Comment by chunseoklee** [comment]
@gridnow Recently, snapshot(preparsed bytecode) feature is merged to master branch. It could reduce compile time. Please check it out.
