### ISSUE TITLE
I need more memory than 256KB

### ISSUE THREAD

**Issue by gridnow** [Samsung/iotjs#298]
HI, 
We need memory more than 256kb in our program(100MB is better). Does iotjs provide any convenience method to set memory heap limitation? Thanks.

**Comment by seanshpark** [comment]
@gridnow , memory is limited (up to 256KB) by JerryScript, it's byte code structure (http://samsung.github.io/jerryscript/internals/)

**Comment by gridnow** [comment]
but more memory is needed in our test case.....

**Comment by seanshpark** [comment]
It's current design decision, IoT.js and JerryScript aims for small devices with several hundred kilo bytes of memory. If you want to use 100MB of memory, I recommend you to use node.js.
BTW, what is your test case?

**Comment by gridnow** [comment]
Got it, but if there's any method to define the memory size for different scenario?

**Comment by seanshpark** [comment]
It would be better to add an issue to JerryScript.

**Comment by zherczeg** [comment]
It is possible to control the available memory, but it cannot be set to 100MB at the moment because JerryScript uses 16 bit compressed pointers. With 8 byte aligned pointers, the maximum addressable memory is 512KB. I think setting the alignment to 16 byte may waste too much memory, and we would still only have 1MB.

**Comment by lemmaa** [comment]
Hi @gridnow , what's your test case? Is it really need 100MB of memory allocation directly in JavaScript engine itself or can be solved by other way using special purpose module?

**Comment by scriby** [comment]
I was looking at using iot.js to run on openwrt based routers. It's not uncommon to only have 10-50 free MB of RAM in this scenario. V8's memory overhead makes it a tight fit. This is probably an area where iot.js would be a better fit if it supported larger heap sizes.

**Comment by gridnow** [comment]
yes, we may not really need 100MB memory,but we need bigger memory.

**Comment by LaszloLango** [comment]
We have plans to make Jerry more scalable.

**Comment by yichoi** [comment]
Closing. It is more related with [JerryScript](https://github.com/Samsung/jerryscript) than IoT.js

**Comment by LaszloLango** [comment]
@yichoi, after https://github.com/Samsung/jerryscript/pull/1271 it is possible to do this in JerryScript.

**Comment by yichoi** [comment]
@LaszloLango, That's great! looks like almost landed.
