### ISSUE TITLE
iot에 대해서 이제 막 관심을 갖은 초보입니다.

### ISSUE THREAD

**Issue by goodhi** [Samsung/iotjs#299]
임베디드 프로그래밍 경험이 없는  웹프로그래머입니다.

iot에 대한 관심이 있던 중 iotjs를 알게 되어 이렇게 찾아왔습니다.

자바스크립트 기반이라는 점이 저에겐 다른 언어를 배우지 않아도 되는 장점이라서 

관심을 갖게 되었습니다.

완전 초보인 저로서는 - 개념조차도 모르는 저로서는 - 지금 있는 도규멘트와 예제로는

iotjs 를 어떻게 활용해야 할지 감이 잡히지 않습니다.

일단 컴퓨터에 가상 머신을 설치해서 ubuntu를 설치한 후 헬로 월드까지 확인은 해봤는데

더이상 뭘 어떻게 해야 하는지 모르겠네요.

기본도 없는 저의 질문이 어이없을 지도 모르겠지만 용기내서 질문해봅니다.

아래는 제가 공부하고자 하는 방법인데 맞는 지 궁금합니다. 개인이 study할 수 있는 최적의 

방법을 추천해주시면 더욱 감사합니다.

1. 라즈베리 파이2를 사서 ubuntu를 설치한 후 iotjs를 설치한다.

2. 원하는 기능을 가진 js 파일을 생성해서 iotjs 명령어로 실행한다.
  -  gpio관련 api를 이용해서 원하는 프로그램을 만든다.
  
그리고 마지막으로 iot같은 경우 사물 인터넷이니까 무선 인터넷을 통해서 사물간의 통신이 이루어지는 거니
nodeJs를 이용해서 각자 서버 생성하고 그 서버로 서로 연동하는 방식으로 만들어야 하는 건가요?

답답하시더라도 아시는 한도 안에서 답변 부탁드리겠습니다.

**Comment by seanshpark** [comment]
좋은 질문입니다. 지금 생각하는 것을 실천에 옮겨보는것도 좋아 보입니다.
GPIO에 계전기를 통해 전등을 붙이고 핸드폰 웹 브라우저에서 전등 키고 끄고를 해 보는 것도 생활에 별 도움은 안될수 있으나 재미는 있을것 같습니다.

**Comment by yichoi** [comment]
no more advice. closing
