### ISSUE TITLE
How to building on stm32F103xxx

### ISSUE THREAD

**Issue by zhongjixiuxing** [Samsung/iotjs#304]
Hi guys:
      I have a stm32F103c8t6 development board, and i don't know how to building base stm32F103XX chip. 
     I read some this project document, and i see Getting Started section, on it write : 
           " H/W boards
                 Current supporting
                      STM32F4-Discovery + BB
                      Raspberry Pi 2
                 Plan to support
                      Samsung Artik 1
                      STM32F429-Discovery
                      STM32F411-Nucleo
                      Intel Edison
           (and your contributions including above plans)
 
,  now this project is Seems to be un-support build base stm32F103xx chip, is right?

   Regards

**Comment by haesik** [comment]
Hello, 
Now iotjs is not support the build base of stm32F103xx chip.
