### ISSUE TITLE
build iotjs for nuttx failed: can't find <netdb.h>

### ISSUE THREAD

**Issue by jiangzidong** [Samsung/iotjs#305]
Hi, I follow the wiki: https://github.com/Samsung/iotjs/wiki/Build-for-NuttX to build iotjs, but met some problems.

In the last step of `3. Build IoT.js with libuv and JerryScript`, after 
`./tools/build.py --buildtype=release --target-arch=arm --target-os=nuttx 
--nuttx-home=/XXXX/nuttx/nuttx --no-check-test`, it shows error: **cannot find netdb.h**
Have you met the problems before? and how to solve it?

Besides, some infomation is out-of-date in that wiki. for example: should be --no-check-test instead of --no-checktest, and iotjs use libtuv instead of libuv. How to handle libtuv in nuttx?

**Comment by seanshpark** [comment]
@jiangzidong , please follow https://github.com/Samsung/iotjs/wiki/Build-for-Nuttx-(new) page to build, but still options are not updated to latest IoT.js build system, so please check `build.py`

**Comment by jiangzidong** [comment]
@seanshpark I tried the new method, build the nuttx.bin and st-flash it. shows: `2015-11-24T09:31:03 INFO src/stlink-common.c: Flash written and verified! jolly good!`

But when I connect my board with host PC, there is no ttyACM0 or other ttyUSBxxx in /dev. ( I am using stm32f407 discovery and ubuntu 14.04. ) Which board do you use?

**Comment by seanshpark** [comment]
@jiangzidong , I use [STM32F4-Discovery + Base board](http://www.st.com/web/catalog/tools/FM146/CL1984/SC720/SS1462/PF255417?sc=stm32f4dis-expansion) . 
When you connect to Mini USB, no device will appear in /dev folder. Please connect micro USB on the other side of the board. It should appear /dev/ttyACM0. I also use USART0 for debug logs. So 3 connections in total. Not pretty.

**Comment by jiangzidong** [comment]
@seanshpark I connected the micro usb and nothing new appeared in /dev. Is that any specific menuconfig needed before building the nuttx? I typed `./configure.sh stm32f4discovery/iotjs`, and leave other configs as default value.

**Comment by seanshpark** [comment]
@jiangzidong , configure is ok. Did you perhaps connect the Ethernet cable and maybe also micro SD card ? If network is not connected it may take a while to boot up. 
For the network IP, please set
```
CONFIG_NSH_IPADDR=0x0a000002
CONFIG_NSH_DRIPADDR=0x0a000001
CONFIG_NSH_MACADDR=0x1e000a000002
```
to some valid address.

**Comment by jiangzidong** [comment]
@seanshpark I don't connect micsoSD or Ethernet (I only have the discovery board, without the extension board). so I don't change the ADDRs. 
After flashing the buttx.bin, the **red user led** is on, is that correct?

During the building, I found there is several things in the wiki need to modified.
1, while clone the nuttx code, there should not `.git` in the url. `git submodule add https://bitbucket.org/seanshpark/nuttx nuttx`
2, ./mkromfsimg.sh needs `sudo apt-get genromfs` first
3, when building the nuttx for the first time, the error should be `no rule for libfdlibm.a` instead of `libtuv.a`
4, the iotjs building command: remove `--tuv`, and the target board should be `stm32f4dis`
5, it shoule be a bug in `tools/build/py`, the nuttx need `liblibiotjs.a`, while build.py copy the `libiotjs.a`

**Comment by seanshpark** [comment]
@jiangzidong , so did /dev/ttyACM0 appear? I think it would after time-out value. I think the red LED would be LD5 and if it's on then I think it is OK. 
Thank you for the comments. Is there any problem with `.git`? Site tells there is `.git`

**Comment by jiangzidong** [comment]
@seanshpark No, there is no ttyACM, and LD5 is off, LD3 is on.
Sorry, `.git` works well too.

**Comment by seanshpark** [comment]
@jiangzidong , LD3 on is not normal. I think it's because you didn't attach BB.

**Comment by jiangzidong** [comment]
@seanshpark so We cannot run nuttx normally on STM32F discovery without the BB?

**Comment by seanshpark** [comment]
@jiangzidong , yes, IoT.js uses network and file system and without BB, it's useless. It's written in WiKi, 
https://github.com/Samsung/iotjs/wiki/Build-for-NuttX#target-board.  So, may I ask what your intension is to run IoT.js on STM32F4-discovery board without the network and file system?

**Comment by jiangzidong** [comment]
@seanshpark Thanks.
1, I will try to get a BB and retry it. but it's strange, why nuttx's serial port depends on fs and network. 
2, Because we have no experience in developing program on RTOS, and iotjs/jerry's target board is the embedded board with RTOS, so we want to try it and familiar with its unique properties from host PC. (e.g, it has no virtual memory and binary code is in flash). So that we will be able to propose/ maintain/debug new features on stm32f4/nuttx or other embedded board.

**Comment by seanshpark** [comment]
@jiangzidong , 
1.  `why nuttx's serial port depends on fs and network.`: I don't think serial depends on fs or network. It's just that as network and fs hardware is not available the codes related to them in NuttX is waiting for any kind of response from it but nothing. I'm not sure if there are any kind of error checking codes. As we configured there will be network and fs hardware it might be unnecessary cause it's not plug-n-play.
2. OK. I understand. Maybe Arduino can help. Sometimes I play with ["this"] (https://www.arduino.cc/en/Main/ArduinoBoardProMini) one. Its small and simple with no OS.

**Comment by jiangzidong** [comment]
@seanshpark As to Arduino, can iotjs run on that?

**Comment by seanshpark** [comment]
@jiangzidong , well, no.... too simple? Please look in ["this"](https://www.arduino.cc/en/Tutorial/BlinkWithoutDelay) page and you can see that it's not something like Unix or event RTOS. It's very simple and good for education, especially if you want to know about `"no virtual memory and binary code is in flash"`

**Comment by jiangzidong** [comment]
@seanshpark After we connect the BB board, we can find the serial port and run iotjs in nuttx! Thanks for  your help.
But do you know how to measure the memory consumption for iotjs in nuttx? So that we can measure whether a feature/patch's memory behavior

**Comment by seanshpark** [comment]
@jiangzidong , good to hear you got the BB board.
I used `free` command and looked into `map` file.

**Comment by jiangzidong** [comment]
@seanshpark `free` will tell the current memory usage of the system. And is `map` you mean `System.map`? 
Is there a method to tell the flash usage and ram usage of the iotjs in stm32?
