### ISSUE TITLE
Make IoT.js to use ccm memory on stm32f4board

### ISSUE THREAD

**Issue by tczene** [Samsung/iotjs#306]
I succesfully moved the heap and stack of nuttx and the heap of IoT.js to ccm. The stack of IoT. js and the heap of Jerryscript stayed on sram. Now we can use ~100kb of memory for Jerry heap on stm32f4 board. We couldn't move the IoT.js's stack to ccm so far, because there are only 11kb on ccm left. If we could decrease the stack size of IoT.js then we could use the entire sram as Jerry heap.

**Comment by tczene** [comment]
Here are the patches:
[IoT.js](https://github.com/Samsung/iotjs/pull/307)
[JerryScript](https://github.com/Samsung/jerryscript/pull/732)
[nuttx](https://bitbucket.org/seanshpark/nuttx/pull-requests/1/omit_memory_section_from_binary/diff)
[nuttx apps](https://bitbucket.org/seanshpark/nuttx_apps/pull-requests/1/added_build_options/diff)
[nuttx arch](https://bitbucket.org/seanshpark/nuttx_arch/pull-requests/1/added_custom_stack_address_to_iotjs/diff)
[nuttx boards](https://bitbucket.org/seanshpark/nuttx_boards/pull-requests/1/moved_bss_to_ccm/diff)

**Comment by seanshpark** [comment]
@tczene , you've done a great work.
```
+    .data : {
+        _sdata = ABSOLUTE(.);
+        *(.data .data.*)
+        *(.gnu.linkonce.d.*)
+        CONSTRUCTORS
+        _edata = ABSOLUTE(.);
+    } > ccmram AT > flash
+
+    .bss : {
+        _sbss = ABSOLUTE(.);
+        *(.bss .bss.*)
+        *(.gnu.linkonce.b.*)
+        *(COMMON)
+        _ebss = ABSOLUTE(.);
+    } > ccmram
+
+    .jerry_mem : {
+        _sjerry_mem = ABSOLUTE(.);
+        *(.jerry_mem .jerry_mem.*)
+        *(COMMON)
+        _ejerry_mem = ABSOLUTE(.);
+    } > sram
```
Seems that `data` and `bss` are moved to CCM if possible, so, have you tried with some network test?

**Comment by tczene** [comment]
Hi,
I updated the patches.
Yes I have tried. Simple http tests run well.

**Comment by seanshpark** [comment]
@tczene , it seems there was a typo in `arm/src/stm32/stm32_eth.c`
```
-#if 0
-defined(CONFIG_SYSTEM_IOTJS) || defined(CONFIG_SYSTEM_TUVTESTER)
-static struct stm32_ethmac_s __attribute__((section (".ccmram"))) \
-                            g_stm32ethmac[STM32_NETHERNET];
+#if CONFIG_ITOJS_USE_CCM
+static struct stm32_ethmac_s g_stm32ethmac[STM32_NETHERNET] __attribute__((section(".sram_section")));
```
`CONFIG_ITOJS_USE_CCM` should be `CONFIG_IOTJS_USE_CCM`

Can you check with the network again?

**Comment by seanshpark** [comment]
@tczene , I've added review comments for nuttx. please check.

**Comment by chokobole** [comment]
close since as we mentioned here [hw-boards](https://github.com/Samsung/iotjs/blob/master/docs/Getting-Started.md#hw-boards), the optimization for stm seires boards are up to each developer.
