### ISSUE TITLE
Complete net module

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#31]
https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Net

net
- [x] createServer()
- [x] connect(options, connectListener)
- [x] connect(port, host, connectListener)
- [x] createConnection(opitions, connectListener)
- [x] createConnection(port, host, connectListener)

net.Server
- [x] listen(options, callback)
- [x] listen(port, host, callback)
- [x] close()
- [x] event: listening
- [x] event: connection
- [x] event: close
- [x] event: error

net.Socket
- [x] new Socket(options)
- [x] connect(port, host, connectListener)
- [x] write(data, callback)
- [x] end(data)
- [x] destroy()
- [x] resume()
- [x] pause()
- [x] setTimeout()
- [x] setKeepAlive()
- [x] event: lookup
- [x] event: connect
- [x] event: data
- [x] event: drain
- [x] event: end
- [x] event: timeout
- [x] event: close
- [x] event: error

**Comment by wateret** [comment]
Closing as all the APIs are implemented
