### ISSUE TITLE
Add command line arguments for turn on and off flags.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#312]
Some flags currently managed by build time options are able to be set by command lime arguments.

For example, when --jerry-memstat option for build.py is given, it makes Jerry with memstat feature on. and IoT.js will automatically turn on the flags as below.. 
```
 #ifdef ENABLE_JERRY_MEM_STATS
   jerry_flag |= JERRY_FLAG_MEM_STATS;
   jerry_flag |= JERRY_FLAG_SHOW_OPCODES;
 #endif
```

But I think it better to decide it at the time executing IoT.js via command line whether tuning on or off such flags.

For example,
```
$ iotjs --mam-stat --show-opcodes app.js
```

**Comment by yichoi** [comment]
Closing. I found that this command line options work fine.
