### ISSUE TITLE
Improving document registeration process.

### ISSUE THREAD

**Issue by lemmaa** [Samsung/iotjs#315]
As many parts are involved not only in the development but also in documentation, we need to improve our document release process. So, I suggest 'in source documentation first' policy.

By following this procedure, we can publicly review the document by PR, looks like source code, and improvement it all together. After the review, we can merge it and publish it on the project wiki or web pages.
 
For the first step, I converted a part of wiki contents to in source document, in PR https://github.com/Samsung/iotjs/pull/314

**Comment by seanshpark** [comment]
+1

**Comment by yichoi** [comment]
closing. no more discussion
