### ISSUE TITLE
how to measure the flash/ram usage in stm32f4 board

### ISSUE THREAD

**Issue by jiangzidong** [Samsung/iotjs#316]
I am using the stm32f407, which has 192k RAM and 1M flash. After I build iotjs for nuttx, is there a method to measure its flash/ram usage?

`free` command in nuttx will show the memory usage  (I think it means RAM, right?) of the system.

**Comment by seanshpark** [comment]
> I think it means RAM, right?

Yes, `free` command for dynamic RAM usage. I didn't look in the `free` codes but one can copy the code to measure free RAM and periodically show its amount. 
And yes `map` for `System.map` file for looking static usage of RAM and Flash.

**Comment by jiangzidong** [comment]
@seanshpark And for `System.map`, we need to distinguish the iotjs from other parts in nuttx by the symbol name, right?

**Comment by seanshpark** [comment]
> we need to distinguish the iotjs from other parts in nuttx by the symbol name, right?

I think it could be better to modify loader script so that all related iotjs symbols stay in some specific place, some thing like
```
    _jerry_text_start = ABSOLUTE(.);
    *\libjerryentry.a:*(.text*)
    *\libjerrycore.a:*(.text*)
    *\libfdlibm.a:*(.text*)
    _jerry_text_end = ABSOLUTE(.);
```

**Comment by nuttx** [comment]
The binutils ''size'' command will also give you the static memory usage (or perhaps arm-none-eabi-size) .

**Comment by jiangzidong** [comment]
@nuttx "size" is not included in the nuttx shell. How can i use the command?

**Comment by nuttx** [comment]
> @nuttx <https://github.com/nuttx> "size" is not included in the nuttx 
> shell. How can i use the command?
>

The size command is used on the HOST PC after you build.  It will give 
you the static memory usage.

At runtime, there will be additional memory usage from allocations from 
the heap.  You can see this dynamic memory usage using the NSH free command:

nsh> free

Greg

**Comment by yichoi** [comment]
We can measure the flash size [here](https://samsung.github.io/iotjs-test-results/)
We need to measure the memory size too.

**Comment by yichoi** [comment]
You can find the memory result at [here](https://samsung.github.io/iotjs-test-results/#)
