### ISSUE TITLE
Latest Status information in Build-for-NuttX.md

### ISSUE THREAD

**Issue by fivdi** [Samsung/iotjs#320]
The [Latest Status](https://github.com/Samsung/iotjs/blob/40b38f0ef60e387960c304f56df39c90ce33fc97/docs/Build-for-NuttX.md#6-latest-status) information at the bottom [Build-for-NuttX.md](https://github.com/Samsung/iotjs/blob/40b38f0ef60e387960c304f56df39c90ce33fc97/docs/Build-for-NuttX.md) implies that IoT.js requires more memory than is available on an STM32F4Discovery board. As stated at the top of the page, this page only provides historical information. However, when I read this page a few weeks ago, by the time I had read all the way down to the end of the page, I had forgotten that the page is only there to provide historical information. I assumed that there was no point in trying IoT.js out on an STM32F4Discovery board as it wasn't going to work anyway. Although I'm not 100% sure, I now believe that IoT.js should function on an STM32F4Discovery board today. Perhaps the Latest Status information should be removed or modified to make things clearer.

**Comment by wateret** [comment]
Good point. FYI, IoT.js works on STM32F4Discovery after bytecode-snapshot support of Jerryscript.

**Comment by yichoi** [comment]
closing. #389 landed.
