### ISSUE TITLE
Binaries for the STM32F4Discovery board

### ISSUE THREAD

**Issue by fivdi** [Samsung/iotjs#321]
Would it be possible to provide IoT.js binaries for the STM32F4Discovery board? Binaries that could be flashed with the st-flash utility? This would make things easier for people new to IoT.js. People like me for example :)

**Comment by LaszloLango** [comment]
I think setting up daily builds would be great, but currently we don't have any published prebuild binaries.

**Comment by haesik** [comment]
@LaszloLango Do you have any progress on proposed feature?

**Comment by LaszloLango** [comment]
@haesik, no, I haven't worked on it.

**Comment by glistening** [comment]
We don't have plan to provide pre-built binary. There are many combinations of binaries from iot.js since we support several platforms and modules that is configurable.
