### ISSUE TITLE
Build on MacOS fails with genromfs missing

### ISSUE THREAD

**Issue by mulderp** [Samsung/iotjs#322]
Hi,

I am trying to run the `oneshot.sh` build script on MacOS.
For this, I installed genromfs manually from Sourceforge and run a local build. This works:

```
pm:nuttx pmu$ ls -ltr ../../embedded/genromfs-0.5.2
total 248
-rw-r--r--  1 pmu  staff   8685 Jun 26  2007 romfs.txt
-rw-r--r--  1 pmu  staff    307 Jun 26  2007 readme-kernel-patch
-rwxr-xr-x  1 pmu  staff    415 Jun 26  2007 genrommkdev
-rw-r--r--  1 pmu  staff    620 Jun 26  2007 genromfs.lsm
-rw-r--r--  1 pmu  staff  19408 Jun 26  2007 genromfs.c
-rw-r--r--  1 pmu  staff   3412 Jun 26  2007 genromfs.8
-rwxr-xr-x  1 pmu  staff    243 Jun 26  2007 checkdist
-rw-r--r--  1 pmu  staff    995 Jun 26  2007 NEWS
-rw-r--r--  1 pmu  staff   1206 Jun 26  2007 Makefile
-rw-r--r--  1 pmu  staff   3457 Jun 26  2007 ChangeLog
-rw-r--r--  1 pmu  staff  17983 Jun 26  2007 COPYING
-rw-r--r--  1 pmu  staff  16508 Dec 21 13:07 genromfs.o
-rwxr-xr-x  1 pmu  staff  19668 Dec 21 13:07 genromfs
```

But when I run the Nuttx build script, I still get a:

```
pm:harmony pmu$ cd nuttx/nuttx/
pm:nuttx pmu$ make
LN: include/arch/board to /Users/pmu/projects/iotjs/harmony/nuttx/nuttx/configs/stm32f4discovery/include
LN: include/arch/chip to arch/arm/include/stm32
LN: arch/arm/src/chip to arch/arm/src/stm32
LN: include/apps to ../apps/include
LN: platform/board to /Users/pmu/projects/iotjs/harmony/nuttx/apps/platform/stm32f4discovery
make[3]: Nothing to be done for `context'.
make[3]: Nothing to be done for `context'.
LN: platform/board to /Users/pmu/projects/iotjs/harmony/nuttx/apps/platform/stm32f4discovery
./nsh_romfsetc.c:59:41: fatal error: nsh_romfsimg_iotjs.h: No such file or directory
 #  include CONFIG_NSH_CUSTOMROMFS_HEADER
                                         ^
compilation terminated.
LN: platform/board to /Users/pmu/projects/iotjs/harmony/nuttx/apps/platform/stm32f4discovery
make[2]: Nothing to be done for `depend'.
```

**Comment by mulderp** [comment]
Note dependencies of this issue to: https://github.com/Samsung/iotjs/issues/311#issuecomment-159439166

**Comment by mulderp** [comment]
Not sure what file to copy for STM32 for genromfs:

```
pm:nuttx pmu$ find . -name "nsh_r*"
./configs/sama5d4-ek/include/nsh_romfsimg.h
./configs/vsn/include/nsh_romfsimg.h
```

**Comment by fivdi** [comment]
If I'm not mistaken, the manually modified `harmony/nuttx/nuttx/tools/nsh_romfsimg.h` should be copied to `/harmony/nuttx/apps/nshlib/nsh_romfsimg_iotjs.h`

**Comment by mulderp** [comment]
I can't find that source file:

```
pm:iotjs pmu$ find harmony -name "nsh_romfs*"
harmony/nuttx/apps/nshlib/nsh_romfsetc.c
harmony/nuttx/apps/nshlib/nsh_romfsimg.h
harmony/nuttx/nuttx/configs/sama5d4-ek/include/nsh_romfsimg.h
harmony/nuttx/nuttx/configs/vsn/include/nsh_romfsimg.h
```

Also not sure where/how to update the branches to possibly see the file.

**Comment by fivdi** [comment]
This is what I see after following the instructions on [bitbucket](https://bitbucket.org/seanshpark/nuttx/wiki/Home):
```
brian@linuxbox:~$ find harmony -name "nsh_romfs*"
harmony/nuttx/nuttx/tools/nsh_romfsimg.h
harmony/nuttx/nuttx/configs/vsn/include/nsh_romfsimg.h
harmony/nuttx/nuttx/configs/sama5d4-ek/include/nsh_romfsimg.h
harmony/nuttx/apps/nshlib/nsh_romfsimg_iotjs.h
harmony/nuttx/apps/nshlib/nsh_romfsetc.o
harmony/nuttx/apps/nshlib/nsh_romfsetc.c
harmony/nuttx/apps/nshlib/nsh_romfsimg.h
```
I tried to use the exact instructions from bitbucket and looked for tips in `oneshot.sh` whenever there were issues. I'm not sure if `oneshot.sh` is suitable for the first build. For example, [make menuconfig](https://gist.github.com/chunseoklee/c1ad97ad80d2dd6c8038#file-oneshot-sh-L50) has been commented out in `oneshot.sh`, but in the bitbucket instructions it's still there.

By combining the instructions from `bitbucket` and commands from `oneshot.sh`, I assumed that the following:
```
cd tools
./mkromfsimg.sh (nuttx absolute path where .config exist)
```
should be:
```
cd tools
./mkromfsimg.sh ..
```

Please note that I haven't successfully built IoT.js for the STM32Discovery board yet, so I'm by no means an expert on the subject.

**Comment by seanshpark** [comment]
Hi,
```
./nsh_romfsetc.c:59:41: fatal error: nsh_romfsimg_iotjs.h: No such file or directory
```

FYI, this file is generated by
```
cd tools
./mkromfsimg.sh (nuttx absolute path where .config exist)
```
step. for example
```
cd tools
./mkromfsimg.sh $HOME/harmony/nuttx/nuttx
```
It converts `rcS.template` file in `tools` folder into C source file in form of an array.
Output file is `nsh_romfsimg.h` and instruction is like, copy to `nuttx/apps/nshlib/nsh_romfsimg_iotjs.h` file.

If you type `rcS.template` file it will show something like this
```
mount -t vfat /dev/mmcsd0 /mnt/sdcard

addroute 127.0.0.0 255.0.0.0 127.0.0.1
addroute 0.0.0.0 0.0.0.0 XXXROUTEADDRTHISIPXXX
```

first line will mount SD-card to `/mnt/sdcard` folder so that we can have R/W disk for JS source files.
second and third line is to add routing table to the network so that network packets
can go to the right place, `local` or `eth0`. so this is very important to IoT.js to work properly.

why this file is generated at built time is that users may assign any IP address and  `XXXROUTEADDRTHISIPXXX` is replaced by the IP address the user has given to `CONFIG_NSH_IPADDR`. so users should change this block to actual value. 
```
CONFIG_NSH_IPADDR=0x0a000002
CONFIG_NSH_DRIPADDR=0x0a000001
CONFIG_NSH_MACADDR=0x1e000a000002
```

**Comment by mulderp** [comment]
Thanks!

Now I have the build running on MacOS too. Not 100% sure if everything worked but the error about missing header file went away:

````
canning dependencies of target httpparser
[100%] Building C object CMakeFiles/httpparser.dir/http_parser.c.obj
Linking C static library libhttpparser.a
[100%] Built target httpparser
==> Build IoT.js

python js2c.py release snapshot /Users/pmu/projects/iotjs/harmony/iotjs/build/x86_64-darwin/release/bin/jerry

Failed to dump ../src/js/assert.js: - -11]

[Failed - 1] python js2c.py release snapshot /Users/pmu/projects/iotjs/harmony/iotjs/build/x86_64-darwin/release/bin/jerry

cp: ./build/arm-nuttx/release/lib/libiotjs.a: No such file or directory
6. Build nuttx...
LN: include/arch/board to /Users/pmu/projects/iotjs/harmony/nuttx/nuttx/configs/stm32f4discovery/include
LN: include/arch/chip to arch/arm/include/stm32
LN: arch/arm/src/chip to arch/arm/src/stm32
LN: include/apps to ../apps/include
make[3]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
....
AR:   binfmt_globals.o binfmt_register.o binfmt_unregister.o binfmt_loadmodule.o binfmt_unloadmodule.o binfmt_execmodule.o binfmt_exec.o binfmt_dumpmodule.o symtab_findbyname.o symtab_findbyvalue.o symtab_findorderedbyname.o symtab_findorderedbyvalue.o builtin.o libbuiltin_getname.o libbuiltin_isavail.o
make: *** No rule to make target `lib/liblibiotjs.a', needed by `pass2deps'.  Stop.
````

**Comment by seanshpark** [comment]
There's two issues,
1) `Failed to dump ../src/js/assert.js: - -11]`
--> I've added new issue for this problem.
for the mean time, please build with `--no-snapshot` option.
This is what I used.
```
./tools/build.py --buildtype=release --buildlib --target-arch=arm --target-os=nuttx \
--jerry-heaplimit=78 --target-board=stm32f4dis --no-init-submodule \
--nuttx-home=/Volumes/Work/work/harmony/nuttx/nuttx --no-snapshot
```
I'm not sure about `stm32f4dis` cause libtuv requires `stm32f4disco`. it will be changed to `stm32f4` in the near future.

2) `No rule to make target 'lib/liblibiotjs.a', needed by 'pass2deps'.  Stop.`
--> I've updated nuttx to link with `libiotjs.a` which was previously `liblibiotjs.a` but it's pushed with `--force` so please update to latest code like below in nuttx folder where `.config` exist.
```
(you may be already in iotjs branch, but if you're not...)
git checkout iotjs
git fetch
git reset origin/iotjs --hard
```

**Comment by seanshpark** [comment]
BTW, running the iotjs built in mac seems to have some problem. I get
```
ICE: Assertion 'mem_try_give_memory_back_callback == NULL' failed at
/Volumes/Work/work/harmony/iotjs/deps/jerry/jerry-core/mem/mem-allocator.cpp
(mem_register_a_try_give_memory_back_callback):11.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

**Comment by wateret** [comment]
FYI, even jerryscript alone fails some of unit-tests on Mac. 
Related issue is https://github.com/Samsung/jerryscript/issues/610

I'm going to check it soon.

**Comment by yichoi** [comment]
Closing since Samsung/iotjs#435 merged. genromfs is not needed anymore.
