### ISSUE TITLE
Segmentation Fault#When call fs.statSync or fs.stat as returning empty string which is path.

### ISSUE THREAD

**Issue by hyunjunekim** [Samsung/iotjs#323]
If call fs.statSync or fs.stat as empty string which is path, raise `Segmentation fault`.
Example,
> var fs = require('fs');
> var stats1 = fs.statSync('');

Because on the binding function, get the null value through path String(iotjs_module_fs.cpp:293line).
> String path = handler.GetArg(0)->GetString();

If should call uv_fs_stat using null value which is path argument, occur to `Segmentation fault`.

**Comment by glistening** [comment]
Thank you for reporting bug. I see same problem in current source. After investigating the source, I found there are same problems in fs.open and so on, too. First, I will make testcases issue-323.js using your report and put the issue-323 into our repository.

**Comment by yichoi** [comment]
#396 landed. closing
