### ISSUE TITLE
mac: segment fault in build for nuttx while snapshot generation

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#324]
Although build in mac is not yet supported but as in issue #322, building for nuttx, snapshot generation fails when running jerry.

Error:
```
[100%] Built target httpparser
==> Build IoT.js

python js2c.py release snapshot /Users/pmu/projects/iotjs/harmony/iotjs/build/x86_64-darwin/release/bin/jerry

Failed to dump ../src/js/assert.js: - -11]
```
When I run `jerry` with any dummy parameters, it fails with segment fault
```
$ /.../harmony/iotjs/build/x86_64-darwin/debug/bin/jerry fdsfds
Segmentation fault: 11
```

**Comment by yichoi** [comment]
Closing since current Nuttx build works with snapshot
