### ISSUE TITLE
Parser error on "catch"

### ISSUE THREAD

**Issue by scriby** [Samsung/iotjs#336]
I'm trying to run some code like this:

```
promise.then(function() {

}).catch(function() {

});
```

iotjs is throwing an error:

```
iotjs build/server.js
    .catch(function (err) {
     ^
ERROR: Ln 56, Col 6: Expected 'Identifier' token
```

It seems to not like the fact that the function name is "catch".

**Comment by zherczeg** [comment]
we are in the middle of landing a new JS parser for JerryScript:

https://github.com/Samsung/jerryscript/pull/813

I hope it will fix this problem. Please wait a bit until we complete the landing process.

**Comment by LaszloLango** [comment]
The current version throws a reference error since there is no `promise`. Promise is an ES6 feature. IoT.js is currently based on JerryScript and only support ES5.1. See also:
https://github.com/Samsung/jerryscript/issues/205 and https://github.com/Samsung/jerryscript/issues/671

**Comment by scriby** [comment]
I am using the bluebird library for promises, not native es6 promises.

Iotjs was throwing a parser error, not a runtime exception.

**Comment by zherczeg** [comment]
There has been a jerry update in IoT.js. Could you check that the problem still persists? I see a reference error here.

**Comment by yichoi** [comment]
closing. I found that it works fine.
