### ISSUE TITLE
--no-checktest doesn't working 

### ISSUE THREAD

**Issue by polaroi8d** [Samsung/iotjs#337]
In Build for Nuttx, https://github.com/Samsung/iotjs/wiki/Build-for-NuttX on the 3th step there is a problem with no-checktest parameter...

> ...
> 3. Build IoT.js with libuv and JerryScript
> 
> As noted in Build for Linux page, you need to give additional options for NuttX.
> 
> --target-arch=arm 
> --target-os=nuttx 
> --nuttx-home=(full path of nuttx home where .config file exist)
> --buildlib
> --no-checktest

--no-checktest doesn't working, instead of **--no-check-test**...

**Comment by hs0225** [comment]
The correct command line option is "--no-check-test".  You can check the availbale option by using "-h" option. (tools/build.ph -h).
