### ISSUE TITLE
wrong libraries path

### ISSUE THREAD

**Issue by polaroi8d** [Samsung/iotjs#338]
In the Build for NuttX tutorial there is some wrong libraries path in the 4th step - https://github.com/Samsung/iotjs/wiki/Build-for-NuttX 

>_ For the moment, lib files need to be copied manually._
> 
> cp build/arm-nuttx/release/libs/libjerrycore.a ../nuttx/nuttx/lib/libjerry.a
> cp build/arm-nuttx/release/libs/libuv.a ../nuttx/nuttx/lib
> cp build/arm-nuttx/release/iotjs/liblibiotjs.a ../nuttx/nuttx/lib/libiotjs.a
> cp build/arm-nuttx/release/libs/libfdlibm.a ../nuttx/nuttx/lib/libfdlibm.a

**correct:**
cp build/arm-nuttx/release/lib/libjerrycore.a ../nuttx/nuttx/lib/libjerry.a
cp build/arm-nuttx/release/lib/libtuv.a ../nuttx/nuttx/lib
cp build/arm-nuttx/release/iotjs/liblibiotjs.a ../nuttx/nuttx/lib/libiotjs.a
cp build/arm-nuttx/release/lib/libfdlibm.a ../nuttx/nuttx/lib/libfdlibm.a

**Comment by haesik** [comment]
Build for Nuttx has been updated and changed  
https://github.com/Samsung/iotjs/wiki/Build-for-Nuttx-(new)
