### ISSUE TITLE
Is there a plan for iotjs to switch to use newer version of JerryScript?

### ISSUE THREAD

**Issue by cwong1** [Samsung/iotjs#339]
The branch of JerryScript used by iotjs's current build system is from Sept. 16th 2015. Is there a plan to switch to a newer branch of JerryScript anytime soon?

**Comment by zherczeg** [comment]
You can make IoT.js work with the latest jerry after you add this patch:
https://github.com/Samsung/iotjs/pull/330

**Comment by poussa** [comment]
We can close this since the PR330 was merged.
