### ISSUE TITLE
Nominating Akos Kiss, Laszlo Lango, and Zoltan Herczeg to IoT.js maintainer status

### ISSUE THREAD

**Issue by zherczeg** [Samsung/iotjs#343]
Hi,

I would like to nominate Akos Kiss ( @akiss77 ), Laszlo Lango ( @LaszloLango ), and Zoltan Herczeg ( @zherczeg ) to be IoT.js maintainers. They have extensive JerryScript knowledge, and also cotributed to IoT.js.

Any seconds?

**Comment by seanshpark** [comment]
+1

**Comment by lemmaa** [comment]
+1

**Comment by poussa** [comment]
Will this resume the iot.js development? It has been stalled during 2016.

**Comment by zherczeg** [comment]
Yes, we plan to increase the activity on this project.

**Comment by lemmaa** [comment]
There is no objection, I updated wiki page https://github.com/Samsung/iotjs/wiki/Assigned-people
Congratulations!!! :)

**Comment by poussa** [comment]
Congratulations to new maintainers!

Intel has plans to submit patches, new features and new OS port to IOT.js and JerryScript. What would be the proper way to start discussing the topics? Do you want just the PR or should we create an issue(s) to talk about the those first?

**Comment by lemmaa** [comment]
@poussa create an issue first, then PR is recommended. 
For JerryScript, our goal is quite simple. Optimization first. But for IoT.js, it's much more complicate. We need to have a time to discuss about the direction for each activities. So create an issue before PR is very important and fruitful. 

P.S. Despite IoT.js was open sourced together with JerryScript last year, it was maintained in-house way until now. So we need big change from now on. Fortunately, we are planning a workshop recently for next step. Let's discuss together in there.

**Comment by LaszloLango** [comment]
@lemmaa, thank you! :)
