### ISSUE TITLE
Buffer can not use []

### ISSUE THREAD

**Issue by ouki-wang** [Samsung/iotjs#360]
var buf=new Buffer('abc')
buf[0]=99 // it does NOT work
why?

**Comment by ouki-wang** [comment]
zero value is very important when Manipulating device, and String can not contain zero value. so the buffer [] method is very important, looking forward to solve this problem

**Comment by LaszloLango** [comment]
@ouki-wang, it works for me on the latest version. What version are you using?

**Comment by ouki-wang** [comment]
@LaszloLango 
it does not work on the latest version(4dd47dc06696dbd1c1f8d126838c18ba5cd9c93a)

//test.js
var buf = new Buffer('abc')
buf[0] = 99
console.log(buf.toString())

run command
iotjs ./test.js
abc

run command
node ./test.js
cbc

**Comment by LaszloLango** [comment]
@ouki-wang, thanks for the detailed test. The problem is that `[]`operator of buffers is unimplemented at the moment. You must use `buffer.write` instead.

```Javascript
var buf = new Buffer('abc')
buf.write ('c', 0);
console.log(buf.toString());
```

See also: https://github.com/Samsung/iotjs/wiki/IoT.js-API:-Buffer

**Comment by ouki-wang** [comment]
@LaszloLango 
We expect Samsung to achieve [] operator, because we can not write non-string value。
for example：
buf[0] = 2
buf[1] = 0
buf[2] = 1
buf[3] = 6

**Comment by zherczeg** [comment]
You can use: String.fromCharCode()
Implementing this would be difficult at the moment because neither proxy objects and typed arrays are not supported by JerryScript at the moment.

**Comment by yichoi** [comment]
It's related with [JerryScript](https://github.com/Samsung/jerryscript) not IoT.js

**Comment by vprunet** [comment]
buffer[ index ] is not supported (by JerryScript).
The buffer API does not provide any function to read/write individual byte values.
buffer.toString is fairly limited as this function hangs when a buffer value does not represent a valid string.

Am I the only one needing to read and write arbitrary data from a buffer (in particular to handle tcp/ip data)?

We have extended the Buffer API with readByte and writeByte methods (in iotjs_module_buffer.c ).
We can provide a PR if nothing better emerges (such as the support for the [] notation in JerryScript).
