### ISSUE TITLE
how to monitor serial

### ISSUE THREAD

**Issue by ouki-wang** [Samsung/iotjs#361]
How to monitor file readable, such as serial (ttyACM0), argument  UV_READALBE can not be used.
And these functions are not available (uv_poll_init uv_poll_start uv_poll_stop)

**Comment by glistening** [comment]
You seems to be asking libtuv or libuv, not JS level. Is it right? Could you give me more information what you had tried? What device do you use? x86 desktop? RPI2 ? STM32F4discovery on nuttx ? Could you show your test code?

**Comment by glistening** [comment]
Recently we added support for uv_poll_init, uv_poll_start and uv_poll_stop on linux and nuttx. I close this issue.
