### ISSUE TITLE
Availability/Status of "Extended API"

### ISSUE THREAD

**Issue by pfalcon** [Samsung/iotjs#365]
https://github.com/Samsung/iotjs/wiki/IoT.js%20API%20Reference#extended-api lists "Extended API", however there're no links to the detailed documentation like for "Basic API" on the same page, nor searching the source code reveals any implementation of names from Extended API. What's the status of it? Is it tentative APIs which don't really exist, or some proprietary (not open-source) extension, or something else? Thanks.

**Comment by seanshpark** [comment]
Hi, what I know of is this.
> What's the status of it? 
Something like a wish-list when Basic is somewhat done.
> Is it tentative APIs which don't really exist?
Yes, currently.
> or some proprietary (not open-source) extension?
No proprietary exist. :)

**Comment by pfalcon** [comment]
Thanks, that answers it. I guess I'll close it, hope other folks who have a similar question will be able to found it.
