### ISSUE TITLE
Raspberry-Pi2/3 build issue, cross-compile issue 

### ISSUE THREAD

**Issue by gudbooy** [Samsung/iotjs#366]
I've been struggling to build IoT.js on Raspberry-Pi2/3 

According to the build manual posted on WIKI page, there are a few wrong guideline [I will pull requests of them]

First, I tried to build on both Raspberry-Pi2 and 3, the error comments are same.

**[pi@raspberrypi: /iotjs]/$ ./tools/build.py --buildtype=release --no-init-submodule --target-arch=arm --target-os=linux**

  Building C object
  CMakeFiles/cmTryCompileExec2768068880.dir/testCCompiler.c.o

  /usr/bin/arm-linux-gnueabihf-gcc -D__LINUX__ -fno-builtin -D__ARM__
  -D__arm__ -mthumb -fno-short-enums -mlittle-endian -O2 -o
  CMakeFiles/cmTryCompileExec2768068880.dir/testCCompiler.c.o -c
  /home/pi/workspace/iotjs/build/arm-linux/release/deps/libtuv/CMakeFiles/CMakeTmp/testCCompiler.c

  /home/pi/workspace/iotjs/build/arm-linux/release/deps/libtuv/CMakeFiles/CMakeTmp/testCCompiler.c:
  In function ‘main’:

  **/home/pi/workspace/iotjs/build/arm-linux/release/deps/libtuv/CMakeFiles/CMakeTmp/testCCompiler.c:11:1:
  sorry, unimplemented: Thumb-1 hard-float VFP ABI**

   { (void)argv; return argc-1;}
   ^

  CMakeFiles/cmTryCompileExec2768068880.dir/build.make:57: recipe for target
  'CMakeFiles/cmTryCompileExec2768068880.dir/testCCompiler.c.o' failed

  make[1]: Leaving directory
  '/home/pi/workspace/iotjs/build/arm-linux/release/deps/libtuv/CMakeFiles/CMakeTmp'

  make[1]: *** [CMakeFiles/cmTryCompileExec2768068880.dir/testCCompiler.c.o]
  Error 1

  Makefile:118: recipe for target 'cmTryCompileExec2768068880/fast' failed

  make: *** [cmTryCompileExec2768068880/fast] Error 2

Second, I also tried to cross-compile the IoT.js on x86_64 linux machine.

**mini@eslab04:~/iotjs$ ./tools/build.py --buildtype=release --no-init-submodule --target-arch=arm --target-os=linux**

CMake Error at cmake/option/option_arm-linux.cmake:33 (message):
  **TARGET_BOARD is undefined**
Call Stack (most recent call first):
  cmake/options.cmake:38 (include)
  CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/mini/iotjs/build/arm-linux/release/deps/libtuv/CMakeFiles/CMakeOutput.log".

In the python code in ./tools/build.py, the --target-board option has no choice value. What parameter  should I insert ?

**Comment by LaszloLango** [comment]
`--target-board=rpi2`

**Comment by esevan** [comment]
@LaszloLango Is there any update for rpi internal update? only support cross-compile now?

**Comment by gudbooy** [comment]
@LaszloLango 
Thank you 
Is it possible to pull requests of wiki page?

**Comment by LaszloLango** [comment]
@gudbooy, no. Unfortunately it is not possible. This is why most of the documentations were moved into the repository (https://github.com/Samsung/iotjs/tree/master/docs). Could you post the your update wiki somewhere? Or at least a diff file. For example on https://gist.github.com/ ?

**Comment by LaszloLango** [comment]
@gudbooy, is this what we are talking about: https://github.com/Samsung/iotjs/blob/master/docs/Build-for-ARM-Linux-(RPi2).md ? If yes, then you can create a pull request and we can accept your changes after you've got at least 2 LGTMs.

**Comment by gudbooy** [comment]
@LaszloLango  Thank you. I will handle this ASAP

**Comment by gudbooy** [comment]
@LaszloLango The PR: #345 handles R-Pi2 build command correction, I will handle the Raspberry-Pi2 native build ASAP

**Comment by yichoi** [comment]
Closing this issue because documents for RPi2 is updated, and we don't have plan to support internal build IoT.js on RPi2 board now. @gudbooy If you want to working on internal build task on RPi2 board, you can make new issue for it.

**Comment by gudbooy** [comment]
@yichoi 
OK, I will handle soon
