### ISSUE TITLE
[Raspberry-Pi] test_net[3, 7, 8].js failed

### ISSUE THREAD

**Issue by gudbooy** [Samsung/iotjs#369]
When I try to  run test_net3, 7, 8.js individually, it just produces a segment fault.

Thus, I run the IoT.js on GDB which produces the following log

Starting program: /home/pi/iotjs/build/arm-linux/debug/bin/iotjs test_net3.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76ffc2f0 (LWP 22015)]
[New Thread 0x767fc2f0 (LWP 22016)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x76ffc2f0 (LWP 22015)]
0x75fd031c in internal_getent (result=0x76ffba90, result@entry=0x76ffbb2c, buffer=0x75fd69ac "/etc/hosts", buffer@entry=0x76ffb670 "",
    buflen=buflen@entry=1056, errnop=0x76ffb670, errnop@entry=0x76ffbb74, herrnop=0x76ffbb3c, herrnop@entry=0xe6d50 <gaih_inet+2912>, af=af@entry=0,
    **flags=flags@entry=0) at nss_files/files-XXX.c:268
268	nss_files/files-XXX.c: No such file or directory.**

The backtrace Log

(gdb) bt
0  0x75fd031c in internal_getent (result=0x76ffbaa0,
    result@entry=0x76ffb634, buffer=0x75fd69ac "/etc/hosts",
    buffer@entry=0x76ffb680 "", buflen=buflen@entry=1056,
    errnop=0x76ffb680, errnop@entry=0x76ffbb44, herrnop=0x76ffbb54,
    herrnop@entry=0xd5b21 <gaih_inet+2040>, af=af@entry=0,
    flags=flags@entry=0) at nss_files/files-XXX.c:268
**1  0x75fd1490 in _nss_files_gethostbyname4_r (
    name=0x21d510 "localhost", pat=0x76ffbb44, buffer=0x76ffb680 "",
    buflen=1056, errnop=0x76ffbb48, herrnop=0x76ffbb54, ttlp=0x0)
    at nss_files/files-hosts.c:402**
**2  0x000d5b20 in gaih_inet ()
3  0x000d6f54 in getaddrinfo ()**
4  0x0009046a in uv__getaddrinfo_work (w=0x21d498)
    at /home/mini/iotjs/deps/libtuv/source/unix/uv_unix_getaddrinfo.c:121
5  0x0008bb16 in worker (arg=0x0)
    at /home/mini/iotjs/deps/libtuv/source/unix/uv_unix_threadpool.c:97
6  0x0008c648 in uv__thread_start (arg=0x21cc78)
    at /home/mini/iotjs/deps/libtuv/source/unix/uv_unix_thread.c:61
7  0x000b6512 in start_thread (arg=0x0) at pthread_create.c:335
8  0x000d8bec in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by nova0821** [comment]
It doesn't produce segment fault with "Raspbian JESSIE" on May, 2016. However, it doesn't pass test cases that are net3,7,8 and dns.

I fixed them and make pull request. (https://github.com/Samsung/iotjs/pull/385/commits/b85a7d3ce2f7851b1925a60b51ca689746f416c5)

**Comment by yichoi** [comment]
#385 landed. closing
