### ISSUE TITLE
Latest ROM/RAM usage numbers on STM32F4Discovery?

### ISSUE THREAD

**Issue by zippocage** [Samsung/iotjs#370]
I have been trying to build IoTjs for NuttX in order to understand the current ROM and RAM use on STM32F4Discovery but I have make issues and can't get past them right now.

Does someone have the latest ROM use numbers for STM32F4Discovery?

According to @tilmannOSG [slideshare presentation from April 2016](http://www.slideshare.net/SamsungOSG/introduction-to-iotjs-60814606) (slide 13) JerryScript alone uses about 190 kB.

@seanshpark wrote in #136 back in July 2015:

> Current version for STM32F4 version requires about 350KB image ROM and about 100K RAM(roughly) 

Are there more recent ROM/RAM figures for iotjs on STM32F4?

Thank you!

**Comment by zherczeg** [comment]
JerryScript with LTO, stripping, and -Os on ARM Thumb2 target is <160K now.

**Comment by zippocage** [comment]
@zherczeg Thanks but I would like to have the complete ROM use. DO you perhaps have figures for iotjs in total?

**Comment by zippocage** [comment]
I have now built iotjs for NuttX and here are my figures from using the size command:

libtuv:               ~19 kB
HTTP parser:   ~11 kB
Jerry  script:    ~163 kB
Iotjs lib:           ~ 88 kB

Total:               ~280 kB
