### ISSUE TITLE
Update to JerryScript 1.0 API?

### ISSUE THREAD

**Issue by pfalcon** [Samsung/iotjs#372]
JerryScript recently has undergone noticeable API changes, preparing for 1.0 (it's at 1.0-RC1 now). It would be nice to know what plans IoT.js maintainers have in regard to update to JrS 1.0 API. Like, have any work already started on that, or is there wait for official JrS 1.0 release first, or there're no immediate plans to update to new API, or is it expected a community to contribute update patches? Thanks.

**Comment by zherczeg** [comment]
The API adoption is in progress, but it has not finished yet.

**Comment by LaszloLango** [comment]
@pfalcon, you can find the in-progress  version here: https://github.com/LaszloLango/iotjs/tree/jerry-update

It does not contain the new build system and 3 test cases are failing (in filesystem module). I won't be able to continue the update at this week.

**Comment by pfalcon** [comment]
Thanks for the responses and information! I'll leave ticket open, for other folks to easily see it.

**Comment by LaszloLango** [comment]
UPDATE: I've updated the working branch, but those 3 tests are still failing.

**Comment by akosthekiss** [comment]
Update is happening at #375

**Comment by pfalcon** [comment]
Thanks, closing this ticket.
