### ISSUE TITLE
Need to update Wiki page about "Build for ARM Linux (RPi2)"

### ISSUE THREAD

**Issue by nova0821** [Samsung/iotjs#377]
Wiki page "Build for ARM Linux (RPi2)" is not same with "docs/Build-for-ARM-Linux-(RPi2).md" file.

Also, It is needed to update some contents in there.

**Comment by yichoi** [comment]
#379 merged

**Comment by nova0821** [comment]
Update build guide for Raspberry Pi 2: https://github.com/nova0821/iotjs-wiki/commit/e2b11528324b6eaf0c634cf1bdb24c9fa09c377d
(Sync with "docs/Build-for-ARM-Linux-(RPi2).md")

**Comment by yichoi** [comment]
updated Wiki Page "Build for ARM Linux (RPi2)"
