### ISSUE TITLE
docs/Build-for-NuttX-(new).md is not updated

### ISSUE THREAD

**Issue by haesik** [Samsung/iotjs#378]
Wiki page [https://github.com/Samsung/iotjs/wiki/Build-for-Nuttx-(new)](https://github.com/Samsung/iotjs/wiki/Build-for-Nuttx-(new)) was updated but the docs/Build-for-NuttX-(new).md was not updated,

**Comment by yichoi** [comment]
updated Wiki page "Build for Nuttx (new)"
