### ISSUE TITLE
How to skip tidy check and test?

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#381]
According to documents, I can skip tidy check by using "--notidy" build option. But, this option was not working.
(https://github.com/Samsung/iotjs/wiki/Build-for-Linux)
And 'checktest' defalut option is true.  I can't find false option.

**Comment by LaszloLango** [comment]
The correct command line option is: `--no-check-tidy`

**Comment by LaszloLango** [comment]
Use `tools/build.py --help` to check the available options of `build.py`.

**Comment by yichoi** [comment]
According to #382, wiki page Build for Linux and docs are updated. 
Please refer it
