### ISSUE TITLE
Need to update(or delete) WiKi page about "IoT.js Package"

### ISSUE THREAD

**Issue by nova0821** [Samsung/iotjs#386]
According to WiKi page "IoT.js Package"(https://github.com/Samsung/iotjs/wiki/IoT.js-Package), it looks like ipm registry is working now and it describe how to setup ipm, but it is not working now.

Many people who interest this project will follow it, but will fail. (I did it, too.)

I think the title of the page should have "TBD" or just delete the page and remove the link from iotjs.net.

How do you think?

**Comment by yichoi** [comment]
It would be better to modify document since we don't run ipm server.

**Comment by yichoi** [comment]
closing. #387 landed
