### ISSUE TITLE
Build break for nuttx(with updated jerryscript)

### ISSUE THREAD

**Issue by haesik** [Samsung/iotjs#398]
When I build iotjs for nuttx with updated source codes, I met a build break. 
It seems that the changed jerryscript does not support "arm" keyword of CMAKE_SYSTEM_PROCESSOR. 

-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
System is unknown to cmake, create:
Platform/EXTERNAL to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- CMAKE_SYSTEM_NAME         EXTERNAL
-- CMAKE_SYSTEM_PROCESSOR    arm
-- CMAKE_BUILD_TYPE          Release
-- JERRY_LIBC                ON
-- JERRY_LIBM                ON
-- JERRY_CMDLINE             ON
-- UNITTESTS                 OFF
-- PORT_DIR                  /home/haesik/harmony/iotjs/deps/jerry/targets/default
-- COMPILER_DEFAULT_LIBC     OFF
-- ENABLE_LTO                OFF
-- ENABLE_ALL_IN_ONE         ON
-- ENABLE_STRIP              ON
CMake Error at jerry-libc/CMakeLists.txt:30 (message):
  Machine architecture arm isn't supported

-- Configuring incomplete, errors occurred!
See also "/home/haesik/harmony/iotjs/build/arm-nuttx/release/deps/jerry/CMakeFiles/CMakeOutput.log".

[Failed - 1] cmake /home/haesik/harmony/iotjs/deps/jerry -DCMAKE_TOOLCHAIN_FILE=/home/haesik/harmony/iotjs/cmake/config/arm-nuttx.cmake -DEXTERNAL_LIBC_INTERFACE=/home/haesik/harmony/nuttx/nuttx/include -DEXTERNAL_CMAKE_SYSTEM_PROCESSOR=arm -DMEM_HEAP_SIZE_KB=78 -DENABLE_LTO=OFF -DFEATURE_SNAPSHOT_SAVE=OFF -DFEATURE_SNAPSHOT_EXEC=ON -DCMAKE_C_FLAGS=-D__NUTTX__ -Os -fno-strict-aliasing -fno-strength-reduce -fomit-frame-pointer -D__ARM__ -D__arm__ -mthumb -fno-short-enums -mlittle-endian -O2 -mcpu=cortex-m4 -march=armv7e-m -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DTARGET_BOARD=STM32F4DIS -DCMAKE_EXE_LINKER_FLAGS= -DEXTERNAL_INCLUDE_DIR=/home/haesik/harmony/nuttx/nuttx/include /home/haesik/harmony/nuttx/nuttx/include/cxx

**Comment by yichoi** [comment]
Closing since Samsung/iotjs#435 merged
