### ISSUE TITLE
Null String allocates 1 byte heap memory

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#399]
With recently merged commit 54cd255979f5f1fb3e6ee38e2b56b99c60b48955 for fixing #323, we allocate 1 byte memory with malloc for every null string. Previously, null string is represented by setting _data to NULL. I think memory defragmentation should be considered more carefully in iot environment since it has small memory. Although this patch make it easy to remove many bugs relating non-nullchecked access, I think previous approach, i.e. without allocation, is more suit for iotjs. If maintainers think the commit seems good, at least, making null string as singleton would be better.

**Comment by glistening** [comment]
As for now, I checked isssue #323 passes without the patch 54cd255. I will make a PR. If there is other reason for the change, Let me know.

In addition, 

 93   IOTJS_ASSERT(_size >= 0);
 94   IOTJS_ASSERT(_cap >= 0);
 95 
 96   if (_cap >= 0) {
 97     _data = AllocBuffer(_cap + 1);
 98   } else {
 99     _data = NULL;
100   }

line 98, 99, 100 seems strange. because line 94 says _cap is non-negative.

**Comment by yichoi** [comment]
Closing since #444 merged
