### ISSUE TITLE
Complete UART module

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#409]
- [x] JS API
  - [x] initialize
  - [x] read
  - [x] write
  - [x] on
- [x] x86 linux dummy
- [x] arm-linux on Raspberry Pi
- [x] arm-nuttx on STM32F4-discovery
- [x] Create document

**Comment by sinban04** [comment]
I'm going to implement this part, is it right that this part is not implemented yet?
When i see the docs, there is no document related to uart, so i think it's not implemented yet.

**Comment by sae-bom** [comment]
I'm sorry that this part is already in progress. The code for UART on linux is internally almost done.

**Comment by hs0225** [comment]
Done.
