### ISSUE TITLE
Complete SPI module

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#410]
Implement SPI module
- [x] spi constructor
- [x] transfer
- [x] transferSync
- [x] close
- [x] closeSync

Test SPI module
- [x]  arm-linux on Raspberry Pi2
- [x]  arm-nuttx on STM32F4-discovery

Write API documentation

**Comment by RedCarrottt** [comment]
Do you have a progress in implementing SPI module? If you don't have a progress, I will handle it.

**Comment by yichoi** [comment]
We have implemented SPI but we could not test enough because there is not proper H/W to test this module. I think we need to find proper H/W first.

**Comment by hs0225** [comment]
Done.
