### ISSUE TITLE
Any plan about BLE IoT.js module?

### ISSUE THREAD

**Issue by esevan** [Samsung/iotjs#420]
IoT.js is a JavaScript platform for a very tiny device, and nowadays bunch of coin-cell backed devices emerge. Most of them use only P2P communication using BLE which is a super energy-efficient communication module. (cf. there's even a JavaScript platform named Puck.js (BLE + espruino) already)

Does anybody of the iotjs community have any plan to add a new ble module or port an existing ble module to IoT.js? Or similar project ongoing already?

**Comment by yichoi** [comment]
We are planning to support BLE with #474, If you want to join us, please check the status.
