### ISSUE TITLE
Unexpected read-related system call on the NuttX side.

### ISSUE THREAD

**Issue by chokobole** [Samsung/iotjs#443]
When call read-related system call with longer or equal than 1024 buffer size, it doesn't seem to work well.

For example, if type command like below,
``` bash
iotjs test_buffer.js, 
```

I found that nothing happened, even though i put some of "console.log" in it.

So I tracked down what was happening, and I found belows.

```c++
String ReadFile(const char* path) {
  // iotjs_util.cpp
   ...
  size_t read = fread(contents.data(), 1, len, file);
   ...
}
```

read's value will be returned to 0.

Also, when you call fs.readFileSync API, it happens the same..

```c++
static ssize_t uv__fs_read(uv_fs_t* req) {
     // uv_unix_fs.c
      ...
      result = read(req->file, req->bufs[0].base, req->bufs[0].len);
      ...
```

result's value will be returned to 0.

At last, it comes to an end with reading nothing at all.

**Comment by chokobole** [comment]
It is related to https://github.com/Samsung/iotjs/pull/434.

**Comment by yichoi** [comment]
Closing since #434 landed
