### ISSUE TITLE
Nominating Wonyong Kim (@chokobole) to become an IoT.js committer

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/iotjs#448]
I would like to nominate Wonyong Kim to become a committer. He already has 11 patches:

#446 Fix check_tidy error
#435 Add targets for nuttx-stm32f4 to support nuttx main repository. 
#434 Set read size to 1023 when read files for nuttx compatibility 
#433 Implement chdir 
#429 Update submodule 'libtuv' to the latest. 
#428 Update submodule 'libtuv' to the latest.
#424 Fix ./tools/build.py --clean error
#414 Implement to copy all the libraries in need to nuttx lib.
#413 Fix Issue #403(Support to build IoT.js for Raspberry Pi on Mac OS.)
#412 Fix Issue #398 (Build break for nuttx with updated jerryscript) 
#395 Fix typo and grammar errors

**Comment by yichoi** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by nova0821** [comment]
+1

**Comment by glistening** [comment]
+1

**Comment by haesik** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by yichoi** [comment]
Congratulations!
