### ISSUE TITLE
Build break for latest nuttx

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#454]
Deleted 'nuttx/gpio.h' header file and changed gpio api in latest nuttx.
If developers follow the document(https://github.com/Samsung/iotjs/blob/master/targets/nuttx-stm32f4/README.md) to build iotjs, they’ll have some problems.

/home/hosung/work/iotjs/my/iotjs/src/platform/arm-nuttx/iotjs_module_gpio-arm-nuttx.cpp:18:24: fatal error: nuttx/gpio.h: No such file or directory
 #include <nuttx/gpio.h>

So, need to fix problems.

**Comment by yichoi** [comment]
Closing since #468 is merged
