### ISSUE TITLE
Building error when following nuttx-stm32f4 guide

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#455]
When following the instructions in https://github.com/Samsung/iotjs/blob/master/targets/nuttx-stm32f4/README.md, following error occurs:

```
cp ../../../iotjs/build/arm-nuttx/debug/lib/lib* .
cp: cannot stat ‘../../../iotjs/build/arm-nuttx/debug/lib/lib*’: No such file or directory
make[3]: *** [preconfig] Error 1
```

In addition, on following page https://github.com/Samsung/iotjs/wiki/Getting-Started,
the link to Build for Nuttx (new) seems broken. It leads to main page ( https://github.com/Samsung/iotjs/wiki ).

**Comment by yichoi** [comment]
Wiki is fixed

**Comment by yichoi** [comment]
Closing since #456 is merged
