### ISSUE TITLE
iotjs_string_t should be able to handle strings with '\0' inside

### ISSUE THREAD

**Issue by yichoi** [Samsung/iotjs#479]
It has been only partially supported.

**Comment by glistening** [comment]
`iotjs_string_t` is simply a pair of buffer and size. It provides very simple functions (i.e., create, destroy, empty, getting data/size, append), which internally use `memcpy`, `realloc`, and don't try to interpret the internal buffer one by one as character. So `iotjs_string_t` is able to handle strings with '\0' inside. I believe we can close this issue.
