### ISSUE TITLE
Re-enable skipped tests after TC driver update

### ISSUE THREAD

**Issue by yichoi** [Samsung/iotjs#480]
Below tests have been skipped after TC driver update. (#450)
They should be re-enabled / or removed from TC if not necessary.
- [x] test_cwd.js
- [x] test_exit.js
- [x] test_next_tick.js - It can be re-enabled if we use `setTimeout` instead of `process.nextTick` in test driver(`tools/test_runner.js`), but then jerry assertion occurs - ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at iotjs/deps/jerry/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):43.

**Comment by yichoi** [comment]
(FYI) `$ iotjs tools/check_test.js -- start-from=test_uncaught_error1.js` fails with jerry assertion,
but `$ iotjs tools/check_test.js -- start-from=test_uncaught_error2.js` doesn't. (Tested with https://github.com/Samsung/iotjs/commit/63f1ab2cd7dbd8964ef3c8a09a25d05d621aea3e)

**Comment by daeyeon** [comment]
`test_process_cwd, test_process_exit, and test_process_next_tick` are now available.
