### ISSUE TITLE
Determine module search path order

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/iotjs#49]
Nodejs search for a module in the order of 
(1) ./node_modules
(2) $NODE_PATH/node_modules
(3) $HOME/node_modules
(4) $HOME/node_libraries
(5) (node execpath)/node/lib

We need to determine the search order w.r.t. multiple plaforms since enviroment or cwd is not available in small devices.

**Comment by yichoi** [comment]
Closing since #417 merged.

Maybe we should re-consider the path with `node` in it. (in another issue)
