### ISSUE TITLE
Nominating Sanggyu Lee (@glistening) to become an IoT.js committer

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/iotjs#497]
I would like to nominate Sanggyu Lee to become a committer. He already has 11 patches:

#496 Fix nuttx build break
#493 Enable error message description on debug build
#492 Update jerry submodule
#486 Add binding APIs for putting an element by index
#470 Implement fs.rename and fs.renameSync
#466 Implements fs.unlink(Sync) and fs.writeFile(Sync)
#460 Add array creation and testing API in binding layer (#449)
#444 Don't allocate 1 byte heap memory for Null String
#405 Fix UnicodeDecodeError on running check_test.py (#404)
#402 Add a testcase in issue-323.js
#401 Update submodule 'libtuv' to the latest

**Comment by zherczeg** [comment]
+1

**Comment by chokobole** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by nova0821** [comment]
+1

**Comment by yichoi** [comment]
Congratulation!
