### ISSUE TITLE
Nominating Hosung Kim (@hs0225) to become an IoT.js committer

### ISSUE THREAD

**Issue by nova0821** [Samsung/iotjs#515]
I would like to nominate Hosung Kim to become a committer. 
He already has 10 patches:

#509 Implement PWM for linux
#494 First Implementation PWM module
#468 Implement GPIO module for latest nuttx
#465 Update nuttx-stm32f4.md
#445 Update GPIO document
#441 Update GPIO document 
#438 Implement GPIO for nuttx
#425 Implement GPIO port for linux general 
#392 Update the document about "Build-for-Linux" page
#382 modify docs/Build-for-Linux.md. Because there is wrong build option.

**Comment by yichoi** [comment]
+1

**Comment by nova0821** [comment]
+1

**Comment by chokobole** [comment]
+1

**Comment by glistening** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by yichoi** [comment]
Congratulations!
