### ISSUE TITLE
Internal Build Problem on Raspberry Pi2

### ISSUE THREAD

**Issue by sinban04** [Samsung/iotjs#551]
I tested building iotjs on the raspberry pi 2.
(There was advance of build system enabling to build on the raspberry pi 2 #437 )

In the middle of building, there was some error and I'm trying to solve it.
is it right that current iotjs code has bug inside ?

I will attach my result of building on the raspberry pi 2
![0](https://cloud.githubusercontent.com/assets/15901475/20512288/bfae5d84-b0c1-11e6-922c-c579042bb6e7.PNG)
![1](https://cloud.githubusercontent.com/assets/15901475/20512291/c3cb4904-b0c1-11e6-9d02-5fba836a645d.PNG)

I got this error, so i solve partially, ( i changed "subprocess.call", to include another argument 'shell=True')
and then it works,
And there is another problem, it does not get the command "git submodule init" like below
![2](https://cloud.githubusercontent.com/assets/15901475/20512315/f0846106-b0c1-11e6-9606-906e508824b1.PNG)

So, i just wanna make it clear that current version has bug in building on the raspberry pi 2?
If it's, i'm trying to solve this problem. 
Thanks.

**Comment by nova0821** [comment]
@sinban04 Thanks to report it. I checked your error messages, it looks like you need to install ``cmake`` to build libtuv.

I will update wiki document. (Build for RPi 2 - Build IoT.js on Raspberry Pi 2 section.)

**Comment by sinban04** [comment]
Oh Thanks, I newly set up the raspberry pi 2, so probably there would have benn no cmake program, installed on the raspberry pi 2
