### ISSUE TITLE
Complete OS Module

### ISSUE THREAD

**Issue by RedCarrottt** [Samsung/iotjs#555]
Complete OS Module

I think we need OS module in order to access running system's status.

Refer to [node.js os module](https://nodejs.org/dist/latest-v6.x/docs/api/os.html).

- [ ] os.cpus()
- [ ] os.endianness()
- [ ] os.freemem()
- [ ] os.homedir()
- [ ] os.hostname()
- [ ] os.networkInterfaces()
- [ ] os.totalmem()
- [ ] os.uptime()
- [ ] os.userInfo()

**Comment by RedCarrottt** [comment]
I will implement this module.

**Comment by yichoi** [comment]
Thanks for your interest in IoT.js however our primary goal is not to expand APIs like node.js but focus on minimum optimized set of APIs. I am afraid that I do not think this APIs are necessary.
