### ISSUE TITLE
Porting IoT.js to Artik5/10

### ISSUE THREAD

**Issue by gudbooy** [Samsung/iotjs#564]
We have been trying to port IoT.js to Artik 5/10 (Fedora Platform) in order to use it in the graduate course.
Actually, it has almost done (currently dealing with minor tests and eliminating the warning messages).

So, my question is that we can PR this ?

PR will include following things
- Artik5/10 Documentation ( Internal, Cross-compile build manual )
- Minor modification on build.py
- Eliminating the warning messages during the compilation phase
- Shell Script Addition (dnf-install-arm.sh :  compile tools, etc..)

**Comment by nova0821** [comment]
@gudbooy We have a plan to release IoT.js version 1.0 in next year 1Q. (Please see - https://github.com/Samsung/iotjs/milestone/5) 

I think there will be many changes in APIs and build script file until version 1.0 is released. 
Therefore, I think it will be better to keep your changes in your repo and request PR after version 1.0 is released.

**Comment by gudbooy** [comment]
@nova0821 
Okay, I will PR after the version 1.0 is released.

**Comment by daeyeon** [comment]
@gudbooy You can do that and we're welcome for your contribution. You may need to check if the things mentioned are still available since there has been a lot of changes since this issue was opened.
