### ISSUE TITLE
One document to rule them all

### ISSUE THREAD

**Issue by loki04** [Samsung/iotjs#596]
It would be lovely if there is only one place for the documentation of iotjs.

1.- Currently there is a minimal introduction of iotjs via gh-pages,
2.- there is a wiki at github which might be the most up-to-date documentation,
3.- and finally there is `doc` sub-directory under the git branches of iotjs - which is based on wiki with differences and outdated content.

How about if there will be only one place for all of those?

Let me just suggest a solution!

Create a separate repository which holds every docs and update the wiki and gh-pages from this. Check out this method: http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by loki04** [comment]
Maybe it will be even better if iotjs just simple uses its `docs` folder and does not spread the information across different places. I am going to share a simple solution very soon.

**Comment by LaszloLango** [comment]
#597 is landed.
