### ISSUE TITLE
#491 patch broke tcp on STM32F4

### ISSUE THREAD

**Issue by vprunet** [Samsung/iotjs#600]
Patch #491  introduced extra \e\n\d characters in tcp sockets (on STM32F4/nuttx) with several unfortunate effects for real use :
- if the other end is not iot.js/Nuttx and the socket close is initiated by the Nuttx side, the extra \e\n\d is not understood by the receiving party (for example a third party web server).
- even on Nuttx, iot.js hangs  if tcp data contain arbitrary binary characters. This is due to an extraneous call to Buffer.toString which breaks when the buffer does not represent a valid string (see also #360 ).

We had to completely remove the patch to be able to connect iot.js/STM32F4 to a remote web socket server.

**Comment by glistening** [comment]
Yes. You're right. Patch #491 is incomplete. However, removing this patch makes even our simple TCP test cases hang when running on STM32F4. I think both solutions (removing and not removing) are not complete. I think we need to investigate the reason of not returning EOF on Nuttx. But I am not good at Nuttx internals.

**Comment by glistening** [comment]
@vprunet We've further investigated on this issue and we got the conclusion that NuttX on STM32F4 does not provide stable behavior for multiple connection/socket and poll() with multiple descriptors. We will not try to put more resources to make NuttX itself more stable. Do you have any information or better workaround? If so, could you share it with us?

**Comment by yichoi** [comment]
We are going to upgrade our base NuttX. Let's discuss about this when this would happen again
