### ISSUE TITLE
Potential merge with Node.js

### ISSUE THREAD

**Issue by lastmjs** [Samsung/iotjs#610]
If Node.js becomes extensible so that other JS engines are able to be used instead of V8, such as JerryScript, would it be possible to somehow merge IoT.js into Node.js, or even get rid of IoT.js and just use Node.js with JerryScript to get the same benefits that IoT.js is seeking currently?

https://www.google.com/amp/s/blogs.windows.com/msedgedev/2016/11/29/node-chakracore-vm-neutrality/amp/?client=ms-android-google

**Comment by yichoi** [comment]
I think the target is different each others. if needed we can discuss about it again
