### ISSUE TITLE
Wrong scope in modules

### ISSUE THREAD

**Issue by lauriro** [Samsung/iotjs#617]
`this` refers to the `exports` in Node.js, but to `module` in IoT.js

```javascript test.js
console.log(this === module, this === exports)
// iotjs test.js -> true false
// node test.js -> false true
```

**Comment by glistening** [comment]
I've checked the different behaviors. And I cannot find reason to behave differently against node. So we would like to resolve it. We will investigate this issue and fix it. If you have solution, please could you kindly push the PR?

**Comment by lauriro** [comment]
#620
