### ISSUE TITLE
build error, /usr/bin/ld: cannot find -lbluetooth

### ISSUE THREAD

**Issue by lsmIndex** [Samsung/iotjs#622]
When I build, there are error like this..
"/usr/bin/ld: cannot find -lbluetooth"
What else module should I install?

Scanning dependencies of target libiotjs
[ 11%] [ 11%] [ 11%] [ 15%] Building C object CMakeFiles/libiotjs.dir/src/module/iotjs_module_process.c.o
Building C object CMakeFiles/libiotjs.dir/src/iotjs_string_ext.c.o
Building C object CMakeFiles/libiotjs.dir/src/iotjs_js.c.o
Building C object CMakeFiles/libiotjs.dir/src/iotjs.c.o
Linking C static library liblibiotjs.a
[ 96%] Built target libiotjs
Linking C executable iotjs
/usr/bin/ld: cannot find -lbluetooth
collect2: error: ld returned 1 exit status
make[2]: *** [iotjs] Error 1
make[1]: *** [CMakeFiles/iotjs.dir/all] Error 2
make: *** [all] Error 2

[Failed - 2] make -j

**Comment by nova0821** [comment]
@lsmIndex Hello, bluetooth lib dependency will be removed after https://github.com/Samsung/iotjs/pull/621 is merged.

**Comment by LaszloLango** [comment]
@lsmIndex, until it is not landed you must install `libbluetooth-dev`

**Comment by yichoi** [comment]
closing. #621 is merged
