### ISSUE TITLE
Define extended modules' API convention rules.

### ISSUE THREAD

**Issue by nova0821** [Samsung/iotjs#629]
Because we implemented extended modules from public ``node.js`` modules(like node-i2c) , API style of them is not equal.

For example, some modules have ``close()`` function and other have ``unexport()`` function which have same role. Also, some modules need to make each object using ``new`` and other can be get by using ``open()`` function. I think user can be confused using these APIs.

That's why it is needed to define extended modules' API convention rules.

1) All extended modules should have same method to make them.
2) Functions with same role should have same name.
3) Prefer to use callback function. (Do not make many events because it is hard to read.)
4) and more..

Here is our extended modules' list.
- GPIO
- I2C
- PWM
- ADC
- UART
- SPI

We will handle this issue with below steps:
1) Define extended modules' API convention rules.
2) Update modules' APIs following 1).

**Comment by yichoi** [comment]
Please post general convention of APIs here

**Comment by nova0821** [comment]
@yichoi I think it will better to make as a WIKI document to explain general convention of APIs, because developers who want to implement new extended modules need to follow our convention.

I will make general convention of APIs as a WIKI document and make PR.

**Comment by yichoi** [comment]
Ok

**Comment by daeyeon** [comment]
Th looks done.
