### ISSUE TITLE
Javascript coding convention

### ISSUE THREAD

**Issue by kolipka** [Samsung/iotjs#631]
I would like to start conversation about JS coding convention. On wiki https://github.com/Samsung/iotjs/wiki/Coding-Style-Guideline#coding-style-guideline-for-javascript there is information about few selected rules from google coding guidelines. This is missleading:
1. Do we use whole google guidelines and selected rules are just exceptions?
  Propably not since selected rules are in line with google.
2. Do we stick only to selected rules?
  If yes, then there is nothing about 80 chars per line limit, but our check_tidy.py enforce this limit.

In my personal opinion we should stick to well know, strict and widely followed in JS community:
https://www.npmjs.com/package/eslint-config-airbnb - most widely used
https://www.npmjs.com/package/eslint-config-standard - second in popularity
https://www.npmjs.com/package/eslint-config-idiomatic - not quite popular, but very well documented in many languages (https://github.com/rwaldron/idiomatic.js/)

This will prevent many errors and enforce good quality code in our repository.

**Comment by nova0821** [comment]
I am not first author of guideline, I understand like below:

1. Developer must follow the guideline which is mentioned in guideline.
2. If there are some ambiguous cases, developer can search in google's rule and recommend to follow it.

@kolipka Can you write some rules which is not general in JS community? or need more additional rules? Give us more detail example not just URL.

**Comment by kolipka** [comment]
OK, this is not a simple request :)

There is a lot of rules. Google does specify only some of them (~55 from more than 250) while others explicite sets them all. Problems I see in google:
allows this: 
 - http://eslint.org/docs/rules/no-cond-assign (if (a=1) - is OK - source of hard to find errors)
 - http://eslint.org/docs/rules/eqeqeq (does not enforce === and !==)
 - var shadowing
and a lot more related eg.: to code style. 

I think we should have more restrictive rules to have better quality of JS code. Since we will use ESLint, it will be enforced automatically.

**Comment by nova0821** [comment]
@kolipka Could you update our rule document(in https://github.com/Samsung/iotjs/wiki/Coding-Style-Guideline) and make PR? (You can find the document file in ``/docs/help``.)

If you want to update JS coding style rule, you need to make more specific document because we already have our rules in there. I think it will be better to discuss with your proposed rules.

After our JS coding style rule is updated, #627 should be updated with new rule.

**Comment by kolipka** [comment]
@nova0821 I would love to edit Wiki, but have no access to do that. Actually I would write there two sentences:
We are following airbnb rules described in details [here](https://github.com/airbnb/javascript) without any exception as of today. Please check your PR with tools/eslint.sh before you submit.

Otherwise I would have to describe ~200 rules :)
Actually if we want to keep 80 char line with, we would have to change one rule, since airbnb allows 100 chars per line.

Despite description on our Wiki we don't keep those rules in our code (please check http_outgoing.js:178: parameter name is ms, and in the body we use msecs. With rules enforced it would not happen). That is why we need strict enforcement and more rules than just basic ones.

**Comment by nova0821** [comment]
@kolipka You can update Wiki document by making PR in ``docs`` folder. (https://github.com/Samsung/iotjs/blob/master/docs/help/Coding-Style-Guideline.md)

When review of your PR(About Wiki document), one of committer will merge it to Wiki page.

I think we have the rule which is not matched with airbnb's That's why I request you to update Wiki document. Please check the difference with our rule and theres and we can discuss with it.

**Comment by kolipka** [comment]
@nova0821 I made #639

Since we actually don't enforce google rules on our code, I don't think we need to list all rules changes. There are most propably 200 ESLint rules not defined by Google, so it would be a lot to describe.

From this PR it will be checked automatically, so no need to remember all of them. You can also use ESLint with --fix and it will fix a lot of them automatically.

**Comment by hs0225** [comment]
The code style rules may change depending on the setting of eslint.
For example, `if` statement must need braces in PR #627. But node.js allow that `if` statement could be used without braces.
In my opinion, although we can not guild all of the rules, we need to explain the rules that are used frequently.

And in PR #627, 4 spaces are used after `if` statement on a single line. But 1 space or 6 space is sometime used. I think, we should guide unified rule about this to users and should add eslint config, if that is possible.

**Comment by kolipka** [comment]
@hs0225 We will not use few rules frequently. We will use ALL ESLint rules always. 

Please check #639 - all ESLint rules are explicitely set and explained. This is why I want to use those settings, #627 will be changed to reflect what we will agree here. In fact I should abandon it, and make it again when we agree on rules.

**Comment by yichoi** [comment]
Airbnb rules are based on ES2015. so it may not the best choice for IoT.js.
I don't want to change the existing rules but just clarify and specify the existing rules.
I think coding rules are somewhat religious. If the opinions are diverged, I will decide by myself.

**Comment by kolipka** [comment]
To clarify:
* Config i suggest uses airbnb-base/legacy - it is for ES5 only, not covering ES6+
* I made simple check aginst current (eslint-config-google) rules. **We violate it in ~600 cases**.
* Comparison of our (explicit) rules agains proposed AirBnB ES5:
1. var (ESLint: 'no-undef', **the same**)
**violated: 35 times**
eg.: http_server.js:118:10 (key), http_outgoing.js:184:25(msec)
2. semicolons (ESLint: 'semi', **the same**)
**violated: 11 times**
eg.: dgram.js:148:2
3. Function Declaration in blocks(ESLint: 'no-inner-declarations', **the same**)
4. Wrapper objects of primitive types (ESLint: 'no-new-wrappers', **the same**)
5. with (ESLint: 'no-with', **the same**)
6. Modifying prototypes of builtin objects (ESLint: 'no-extend-native', **the same**)
7. Naming (ESLint: 'camelcase' + 'new-cap', **the same**)
**violated: 3 + 27**
eg.: gpio.js:22:5, gpio.js:72:15

AirBnB config introduce a lot additional rules, that will unify the look of our code and help find more bugs.

**Comment by LaszloLango** [comment]
Just a quick note. I'm not familiar with eslint, but if it isn't only a style checker (indentation, case convention, etc.), but reports deeper issues (e.g. best practice violations), then we must do the JS changes carefully. They might have some impact on memory consumption too. They shouldn't, but might be.

**Comment by kolipka** [comment]
@LaszloLango For now we have no rules so I think it is worse, When you will encounter such rule, we can change it with one line in eslint config to find all places where we have a problem.
Anyway: is there any guideline about cost of some constructs in JerryScript? Eg.: we usually use caching:
var someVal = myObject.someVal;
I expect it gives performance improvement but at the cost of memory. I would like to know the cost of a closure, .bind() and other things.

**Comment by LaszloLango** [comment]
@kolipka, using eslint is defiantly in improvement. :) The memory usage of JerryScript in IoT.js is under investigation at the moment. I cannot say now what constructions should be avoided in the future development or is there any. What we need is to able to measure the memory usage consistently. But it is independent from eslint.

**Comment by nova0821** [comment]
@LaszloLango @kolipka 

I also agree using eslint is better than now. We need to decide which rules in there and how we provide JS coding style guide for user.

In my opinion, we need to choose the rules which we really need and write minimal document.
@kolipka says he suggest to use ``airbnb-base/legacy - it is for ES5 only, not covering ES6+``, but it looks he linked the guideline document(https://github.com/airbnb/javascript) which has the rules for ES6. We need to make it more clearly.

**Comment by kolipka** [comment]
@nova0821 guide document describe all rules available in ESLint. I think it is OK since maybe some day we will use also ES6+ too. Anyway ESLint will check only ES5 rules.
I do not know what Code Editor you are using but most of them (even Vim) can read .eslintrc and will guide / display errors, so you do not have to remember any of those rules.
I am against extracting only few rules since I think we need them all. It will require time to pick it, it will open our code to lower quality and bugs. Also if we find that certain rule does not suit our needs, or like @LaszloLango said - introduce some memory/performance penalty we can change it, as an exception.

**Comment by cztomsik** [comment]
standard?
http://standardjs.com/rules.html
there are no configs -> no decisions to make :)

**Comment by kolipka** [comment]
@daeyeon I would like to suggest this as a 1.x candidate

**Comment by daeyeon** [comment]
This is related to https://github.com/Samsung/iotjs/issues/1262 and https://github.com/Samsung/iotjs/pull/1270 landed.
