### ISSUE TITLE
Question about precommit.py

### ISSUE THREAD

**Issue by kolipka** [Samsung/iotjs#645]
https://github.com/Samsung/iotjs/blob/master/tools/precommit.py#L120
we add modules specified as excluded to included. Since this script builds on Travis, is it for a purpose to test something?

**Comment by hs0225** [comment]
Yes. This is to test all modules which include excluded modules.

**Comment by kolipka** [comment]
@hs0225 OK thanks.

**Comment by tadziopazur** [comment]
I think this could be done a bit differently - can we have explicit configurations for Travis to run thru?
Right now modules that are not used (in certain build) still would be included in test build.
I.e.: if we have two modules that cannot work together, the precommit would still verify a build with them both enabled.

If we had explicit test configurations (we have a test/ directory to hold these kind of things), precommit (and Travis) would run exactly what we want, not everything it finds.
How does that sound?
