### ISSUE TITLE
PWM API is non-portable and insufficient

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#658]
PWM API has currently several issues:

1. Implementation leaks to the interface level (both period and dutyCycle are specified in nanoseconds, instead of seconds)
2. There are platform limits to PWM chips (i.e.: minimum and maximum period, duty cycle limits and granularity). There is no way to find out these limits from JS application
3. There is no way to find out current period/duty cycle values. This poses two problems:
- an app cannot retrieve the state (i.e.: just after start)
- an app has no way to tell how the desired values ended up being understood by the HW (HW supports 100, 110, 120kHz. App requesting for 112kHz would end up getting either 110 or 120kHz.
4. The linux and nuttx APIs are incoherent: on linux only setPeriod is supported, on nuttx there is only setFrequency

**Comment by hs0225** [comment]
#659 was landed.
