### ISSUE TITLE
Provide experimental features

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#692]
It would be good to specify the stability of features (modules or APIs, and so on). Node.js provides 3 level of stability: Deprecated, Experimental, Stable. We will introduce experimental level first. The experimental features have high probability of changes and may be not stable so we must inform the users of the features. Here are requirements:

- Provide build script for enabling experimental feature
- Specify the feature is experimental in API documents
- Provide way to skip test cases of experimental feature
- Provide standard guards to enclose the code for experimental features (for both C and JavaScript respectively)

**Comment by daeyeon** [comment]
Done.
