### ISSUE TITLE
Refactor platform folder structure

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#710]
There are a lot of unnecessary files that must exist because of the build test in the current `src/platform` folder. We need to arrange these. And the targets folder also need the arrangement.
I suggest changing the folder structure and name as below.
 - replace `.inl.h` with `.c`.
 - does not implement dummy file and not test it in Travis.
 - rename `targets` folder to `config` and put all config file in that folder.
 - put all documents in docs folder. (move the documents in targets folder to the docs folder)
 - board folder naming convention is `os-board name`(ex. nuttx-stm32f4dis)

```
├── config
│   └── nuttx-stm32f4dis
│       └── app
├── docs
│   ├── api
│   ├── build
│   ├── devs
│   ├── help
│   └── targets
└── src
    ├── js
    ├── modules
    │   └── iotjs_module_gpio.c
    └── platform
        ├── linux
        │   └── iotjs_module_gpio-linux.c
        └── nuttx
            ├── iotjs_module_gpio-nuttx.c
            └── nuttx-stm32f4dis
                └── iotjs_module_gpio-nuttx.c
```

**Comment by tadziopazur** [comment]
Could you please hold off for a moment?
I think next week I'll have some time to understand and, if I have something useful to say - discuss this item.

**Comment by akosthekiss** [comment]
@hs0225 In the platform subtree, I'm not sure that `platform/os/os-board` has much more expressive power than `platform/os/board`. Is there any specific reason to repeat the OS part on the path? And for the source file names, why is it needed to add a suffix to the platform-specific parts of the module implementations, or - if platform-specific suffix is a must - why don't we add `-os-board` for board-specific files (e.g., `iotjs_module_gpio-nuttx-stm32f4dis.c`), or why don't we just add a generic suffix everywhere (e.g., `-platform` or `-impl`)?

Alternatives/suggestions:
```
    src
    ├── js
    ├── modules
    │   └── iotjs_module_gpio.c
    └── platform
        ├── linux
        │   └── iotjs_module_gpio-linux.c or
                iotjs_module_gpio.c or
                iotjs_module_gpio-impl.c
        └── nuttx
            ├── iotjs_module_gpio-nuttx.c or
                iotjs_module_gpio.c
                iotjs_module_gpio-impl.c
            └── stm32f4dis
                └── iotjs_module_gpio-nuttx.c or 
                    iotjs_module_gpio-nuttx-stm32f4dis.c or 
                    iotjs_module_gpio.c or 
                    iotjs_module_gpio-impl.c
```

**Comment by hs0225** [comment]
@tadziopazur Unfortunately, I have already worked on it. But please do not hesitate to give me any feedback.

@akosthekiss I agree not to use `os` repeatedly in the folder name. And attaching the os suffix to the filename in platform subtree is to distinguish it from the file in the module subtree. 
I suggest the following.
```
├── config
│   └── nuttx
│       └── stm32f4dis
│           └── app
├── docs
│   ├── api
│   ├── build
│   ├── devs
│   ├── help
│   └── targets
│       └── nuttx
│           └── stm32f4dis
└── src
    ├── js
    ├── modules
    │   └── iotjs_module_gpio.c
    └── platform
        ├── linux
        │   └── iotjs_module_gpio-linux.c
        └── nuttx
            ├── iotjs_module_gpio-nuttx.c
            └── stm32f4dis
                └── iotjs_module_gpio-nuttx-stm32f4dis.c
```

**Comment by akosthekiss** [comment]
@hs0225 Actually, the toolchain would/should not mind having two source files with the same name, but it might help in debugging in some cases to have all files named differently. The suggestion works with me.

**Comment by yichoi** [comment]
#730 was landed
