### ISSUE TITLE
Complete HTTP module

### ISSUE THREAD

**Issue by ILyoan** [Samsung/iotjs#72]
- [x] http.METHODS
- [x] http.STATUS_CODES
- [x] http.createServer([requestListener])

- [x] Class: http.Server
    - [x] Event: 'request'
    - [x] Event: 'connection'
    - [x] Event: 'close'
    - [x] server.listen(port[, hostname][, backlog][, callback])
    - [x] server.close([callback])
    - [x] server.setTimeout(msecs, callback)
    - [x] server.timeout

- [x] Class: http.ServerResponse
    - [x] Event: 'close'
    - [x] Event: 'finish'
    - [x] response.writeHead(statusCode[, statusMessage][, headers])
    - [x] response.setTimeout(msecs, callback)
    - [x] response.statusCode
    - [x] response.statusMessage
    - [x] response.setHeader(name, value)
    - [x] response.headersSent
    - [x] response.getHeader(name)
    - [x] response.removeHeader(name)
    - [x] response.write(chunk[, encoding][, callback])
    - [x] response.end([data][, encoding][, callback])

- [x] http.request(options[, callback])
- [x] http.get(options[, callback])

- [x] Class: http.ClientRequest
    - [x] Event: 'response'
    - [x] Event: 'socket'
    - [x] request.write(chunk[, encoding][, callback])
    - [x] request.end([data][, encoding][, callback])
    - [x] request.setTimeout(timeout[, callback])

- [x] http.IncomingMessage
    - [x] Event: 'close'
    - [x] message.headers
    - [x] message.setTimeout(msecs, callback)
    - [x] message.method
    - [x] message.url
    - [x] message.statusCode
    - [x] message.statusMessage
    - [x] message.socket

**Comment by LaszloLango** [comment]
Everything marked as complete in this issue, so we should close this.
