### ISSUE TITLE
Refactor build script to be more CMake friendly

### ISSUE THREAD

**Issue by galpeter** [Samsung/iotjs#723]
The current build script provides all of the logic on how to build each sub-module (jerry/http-parser/libtuv), where to copy the resulting libraries. Thus if someone would want to build the project without invoking the build.py the cmake call will fail. It would be possible to manually call each sub-module's cmake and build them but it is tedious and would not make much sense.

Building each sub-module can be done with cmake and would allow the build to run fully parallel.
By allowing the cmake to handle the configure step it would possible to run the following command:
```
cmake -DPLATFORM_DESCRIPTOR=x86_64-linux <path to top-level CMakeLists.txt>
```
Which configures everything for Linux 64bit. It would also be possible to pass other arguments to fine tune the build (like module requirements, jerry flags, target os/board information, etc..)

The build.py then would still be kept as thin layer. 

For this I've created a PR so others could check and provide feedback:
https://github.com/Samsung/iotjs/pull/708

All previous build.py calls should also work.

**Comment by daeyeon** [comment]
PR for this has been merged into master.
