### ISSUE TITLE
Is it possible to pass a void* pointer from C to Javascript?

### ISSUE THREAD

**Issue by akhilkedia** [Samsung/iotjs#724]
Hi!

I am making a Native Module which needs to pass a `void*` pointer to JavaScript.
Later on, the JavaScript can pass the `void*` back to the Native Module.

From what I can tell, none of the `iotjs_jval_create_*` functions seem to suitable for this.

There are two workarounds I can think of - 
1. Split the contents of the `void*` (The memory address which the pointer contains) as a byte array, and pass that using `iotjs_jval_create_byte_array`. I don't want to do this as different environments might have different `sizeof(void*)`.
2. Maintain a mapping (via LinkedList/Hashmap/anything) in my Native Code from `void*` to `int`, and pass that `int` to the javascript code. Later on use that mapping to convert the `int` back to `void*`. But this will require me to write a lot of extra code.

Is there some function for passing the void* that I am missing?

**Comment by zherczeg** [comment]
For security reasons I would not pass a pointer to JS code which can be modified by JS. However, you can assign a user pointer to any JS object. This pointer can only be accessed from JS.

I would recommend to do the following:
* Create an object with `jerry_create_object`
* Assign a user pointer with jerry_set_object_native_pointer (new API) / jerry_set_object_native_handle (old API)
* When you need the pointer get it with jerry_get_object_native_pointer / jerry_get_object_native_handle

The new API will be available after a Jerry update.
