### ISSUE TITLE
High memory consumption in 'setTimeout'

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/iotjs#725]
`setTimeout` calls consume too much memory in IoT.js. I've investigated the issue and here are my experiences. The net module use `resetSocketTimeout()` frequently. For example in `test_net3.js` the setTimeout is called 828 times. 

JS backtrace of `Timeout.prototype.activate`:
```
Frame 0: timers:43 (in function() at line:42, col:30)
Frame 1: timers:90 (in function() at line:68, col:22)
Frame 2: iotjs.js:48 (in function() at line:46, col:25)
Frame 3: net:308 (in resetSocketTimeout() at line:302, col:1)
Frame 4: net:98 (in function() at line:77, col:28)
Frame 5: net:642 (in function() at line:639, col:46)
Frame 6: test/run_pass/test_net3.js:70 (in function() at line:1, col:2)
Frame 7: module:188 (in function() at line:180, col:36)
Frame 8: module:168 (in function() at line:152, col:23)
Frame 9: module:193 (in function() at line:192, col:26)
Frame 10: iotjs.js:31 (in startIoTjs() at line:23, col:3)
Frame 11: iotjs.js:221 (in function() at line:17, col:2)
```

Each `setTimeout` call allocate 176 byte in release and 232 byte in debug build. This means 140K peak of timer calls on `test_net3.js`. One big problem is that the timer handler structure in libtuv is too big. It isn't optimized for low memory environments. For example it has a reserved field that wastes a lot of memory.
The other problem is that this handler is only freed when the JS wrapper object is freed.

Is it OK to do complex reworks in `libtuv` or not? Do we plan to upstream `libuv` changes frequently? Do you have suggestion how to reduce the memory consumption of timers?

**Comment by zherczeg** [comment]
Probably it could help if we could delete the timer when it is cleared. Unfortunately there is a delayed delete, which unreferences the object, but does not call its native destructor.

Perhaps it could help if the native part of such objects would be deleted as well.

**Comment by glistening** [comment]
@LaszloLango For latter, please give us some time for investigating this issue. Probably we can fix the former first, because it is simpler than latter and independent problem.

**Comment by glistening** [comment]
@LaszloLango 
1) _Is it OK to do complex reworks in libtuv or not?_ 
OK. If it is necessary to reduce memory consumption.
2) _Do we plan to upstream libuv changes frequently?_ 
Presently, no. We have other high priority tasks.
3) _Do you have suggestion how to reduce the memory consumption of timers?_ 
We will be busy probably till May. I think this is presumably related to garbage collector. Or it is a just memory leak bug. I don't have time to investigate this issue. If you have any idea, please continue to rework to mitigate this situation.

@zherczeg Could you explain what do you mean by `delayed delete`? Is it related to jerryscript garbage collector or iotjs implementation?

**Comment by LaszloLango** [comment]
First part of the timer optimization is landed (https://github.com/Samsung/libtuv/pull/76)
Second part: https://github.com/Samsung/libtuv/pull/79
This patch reduces the total memory usage by 20Kbytes on `test_net3.js`. The peak usage was also reduced by 10Kbytes. (Measured with Freya tool of Valgrind on x86_64-linux)

**Comment by glistening** [comment]
Thank you for your second improvement.

I think we saved 2 x sizeof(void*) per a uv_timer_s with second part.
The removal of start_id would not give us gain because of uint64_t timeout immediately before uint32_t repeat. If so, what about rolling back uint32_t repeat to uint64_t repeat? Because 2^32 milliseconds are about 49.7 days. It may not be enough for some scenario.

In addition, I am guessing the second patch's gain on NuttX and TizenRT might be 10Kbytes, and 5 Kbytes since the sizeof(void*) is 32bit, not 64bit. Is it right?
If you cannot measure it on NuttX, could you please use x86_32-linux? It would help us for estimating the effect on NuttX and TizenRT.

**Comment by LaszloLango** [comment]
@glistening my bad. I thought `repeat` is a counter to how many times do you want to run the timer. I checked in the documentation and you are right. `repeat` must be uint64_t. Although I think it won't be happening in a real world use case to use such a big repeat  time. :)

**Comment by LaszloLango** [comment]
@glistening measured the path on RPi2:

*test_net_3.js*
Before:
```
  [1] Peak: 85.3Kb (87355b) Allocs: 69236 Reallocs: 0 Total: 598.5Kb (612876b) 
  Group: iotjs
    [2] iotjs_buffer_allocate (/home/pi/lango/iotjs/src/iotjs_util.c:61)
      [3] Peak: 71.8Kb (73560b) Allocs: 828 Reallocs: 0 Total: 97.0Kb (99360b) 
      iotjs_timerwrap_create (/home/pi/lango/iotjs/src/modules/iotjs_module_timer.c:26)
```
After:
```
  [1] Peak: 80.5Kb (82515b) Allocs: 69236 Reallocs: 0 Total: 592.0Kb (606252b) 
  Group: iotjs
    [2] iotjs_buffer_allocate (/home/pi/lango/iotjs/src/iotjs_util.c:61)
      [3] Peak: 67.0Kb (68656b) Allocs: 828 Reallocs: 0 Total: 90.5Kb (92736b) 
      iotjs_timerwrap_create (/home/pi/lango/iotjs/src/modules/iotjs_module_timer.c:26)
```

**Comment by glistening** [comment]
@LaszloLango Oh, great! Thank you.

**Comment by LaszloLango** [comment]
@glistening I've update my prev. comment with the results of release builds.

**Comment by LaszloLango** [comment]
Fixed.
