### ISSUE TITLE
nuttx/stm32f4discovery build fails

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#736]
nuttx: 1b6630ee7557687f7717b52a0d938c72a3e047a8
iotjs: de4cabb9707449dc95eefe2b301e14f30d9918ed

There are macro redefinition errors:
$tools/build.py --target-os=nuttx --sysroot=/opt/iotjs/nuttx/nuttx --target-arch=arm --target-board=stm32f4dis --jerry-heaplimit=78 --buildtype=release --no-init-submodule --no-parallel-build
(...)
/opt/iotjs/iotjs_test/deps/libtuv/include/uv-nuttx.h:60:0: error: "ENOTSUP" redefined [-Werror]
 #define ENOTSUP       EOPNOTSUPP
 ^
cc1: all warnings being treated as errors
CMakeFiles/libiotjs.dir/build.make:74: recipe for target 'CMakeFiles/libiotjs.dir/src/iotjs_binding.c.obj' failed

**Comment by galpeter** [comment]
It seems the newer nuttx provides the ENOTSUP macro.
Hopefully this PR will fix it: https://github.com/Samsung/libtuv/pull/75

**Comment by glistening** [comment]
I checked nuttx/stm32f4discovery builds well after libtuv PR #75 landed.
