### ISSUE TITLE
Nominating Daeyeon Jeong (@daeyeon) to become an IoT.js committer

### ISSUE THREAD

**Issue by hs0225** [Samsung/iotjs#741]
I would like to nominate Daeyeon Jeong to become a committer.
He already has 10 patches:

Support experimental build (#692) (#693)
Add a description of --config (#695)
Set Coverity-Scan (#697)
Fix travis configuration for Coverity Scan (#709)
Fix #672 in iotjs_string_create_with_size/buffer (#712)
Fix #674 to check if user inputs are valid (#713)
Fix #673 via checking bound_range properly (#714)
Update Timer, Stream, Module API docs (#728)
Update HTTP, Net, Process API docs (#729)
Make socket error readable (#738)

**Comment by yichoi** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by chokobole** [comment]
+1

**Comment by glistening** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by rtakacs** [comment]
+1

**Comment by yichoi** [comment]
Congratulations! I've updated [here](https://github.com/Samsung/iotjs/wiki/Assigned-people)
