### ISSUE TITLE
Proposal: Test naming

### ISSUE THREAD

**Issue by galpeter** [Samsung/iotjs#743]
Currently the test case names does not have a "strict" rule.
There are test file like `test_i2c.js` and also `test_uncaught1.js`. In the first example the test name explicitly contains the module under testing (or related module under testing). But the `test_uncaught1.js` does not contain any module info thus it is not clear for which module is tested (the `test_uncaught1.js` tests one of the `process` module's functionality).

Additionally the names of the test cases are used for test skipping. For example if someone specifies the `skip-module=i2c` the `test_i2c.js` will not be executed which is great. However if the test file is named like `test_writebyte.js` the file would have been executed.

The detection of which tests should be skipped is done by an `indexOf` call, that is we only check if the module name (specified by the `skip-module` argument) is in the target test's name. In the case of the `test_uncaught1.js` to skip it the `skip-module=uncaught` would be necessary.

What I'm proposing is to have all test file names the same naming convention. That is all test files should be named like: `test_<module name>[_<functionallity].js`. Most of the tests already adhere to this convention.

The affected test files (and their new proposed name) in the `test/run_pass` are the following:

Current name |  New name
-|-
test_cwd.js | test_process_cwd.js
test_exit.js | test_process_exit.js
test_experimental_on.js | test_process_experimental_on.js
test_experimental_off.js | test_process_experimental_off.js
test_fs1.js | test_fs_1.js
test_fs2.js | test_fs_2.js
test_gpio1.js | test_gpio_1.js
test_gpio2.js | test_gpio_2.js
test_httpclient_timeout.js | test_net_httpclient_timeout.js
test_httpclient_timeout2.js | test_net_httpclient_timeout2.js
test_httpserver.js | test_net_httpserver.js
test_httpserver_timeout.js | test_net_httpserver_timeout.js
test_net10.js | test_net_10.js
test_net1.js | test_net_1.js
test_net2.js | test_net_2.js
test_net3.js | test_net_3.js
test_net4.js | test_net_4.js
test_net5.js | test_net_5.js
test_net6.js | test_net_6.js
test_net7.js | test_net_7.js
test_net8.js | test_net_8.js
test_net9.js | test_net_9.js
test_next_tick.js | test_process_next_tick.js
test_timers2.js | test_timers_2.js
test_uncaught1.js | test_process_uncaught1.js
test_uncaught2.js | test_process_uncaught2.js
test_uncaught_error1.js | test_proces_uncaught_error1.js
test_uncaught_error2.js | test_proces_uncaught_error2.js

In the `test/run_fail` dir all files should be renamed:

Current name |  New name
-|-
assert_fail1.js | test_assert_fail1.js
assert_fail2.js | test_assert_fail2.js
assert_fail3.js | test_assert_fail3.js
fs_callbacks_called.js | test_fs_callbacks_called.js
process_exit1.js | test_process_exit1.js
process_exit2.js | test_process_exit2.js
process_exitcode1.js | test_process_exitcode1.js
process_exitcode2.js | test_process_exitcode2.js
require_fail1.js | test_iotjs_require_fail1.js 
runtime_error1.js | test_runtime_error1.js
syntax_fail1.js | test_runtime_syntax_fail1.js
uncaught_error_event.js | test_event_uncaught_error_event.js

There are also test files which are related to an issue. These files
usually starts with the `issue-` prefix which should not be renamed.

If we have a consistent naming scheme it would be possible for the test runner to automatically detect if a given test file can not be executed because the IoT.js was not built with the given module. Thus we would not need to pass the `skip-module` argument for the test runner (at least not for the built-ins which were not built into the system).

Any comments?

**Comment by hs0225** [comment]
I agree with your opinion. The module name in the test's name must be precisely specified so that the test runner accurately test the built module. And if possible, instead of writing a number in the file name, it would be better to specify what the test is.

Current name |  New name
-|-
test_fs.js | test_fs_oepn_read_async.js
test_fs1.js | test_fs_oepn_read_sync.js
test_fs2.js | test_fs_event.js
test_gpio1.js | test_gpio_output.js
test_gpio2.js | test_gpio_input.js

**Comment by galpeter** [comment]
@hs0225 yeah replacing the numbers with more informative text is better. I'll create a PR which renames the tests so others can see a more concrete thing.
