### ISSUE TITLE
Built-in package downloader module

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#75]
As described in https://github.com/Samsung/iotjs/wiki/IoT.js-Package page we may need a built-in package downloader module, but should optional in compile time so that not consume flash space if not needed.

Condition
* has IP network that can connect to ipm registry server
* has storage

What
* server program to manipulate
* with simple commands
```
install <package>
list
remove <package>
```

**Comment by yichoi** [comment]
Closing. No plan to open ipm server now.
