### ISSUE TITLE
Confusing "exclude" module list in `build.config`

### ISSUE THREAD

**Issue by akosthekiss** [Samsung/iotjs#750]
In `build.config`, modules can be listed as "always" (i.e., must be included in the build), "include" (i.e., also to be included in the build, unless overridden by command line option), and "exclude" -- and this category is what needs to be discussed. The problem is that actually the "exclude" modules of `build.config` are not excluded from anywhere (as far as building IoT.js goes): the config files "exclude" list _must not_ overlap with the "include" list, only the above mentioned command line option (`--iotjs-exclude-module`) can remove (exclude) modules from there.

However, `build.config`'s "exclude" list is used
- for checking that those modules are not even required (transitively) by included modules (in `module_analyzer.py`),
- for defining the `skip-module` option to the test driver (in `build.py`), and
- for composing the `--iotjs-include-module` (!!!) command line option for build tests (in `precommit.py`).

This leads to some interesting situations:
- In current master, several modules are listed as "excluded" just to ensure that they are build-tested but not run-tested. Forcing the build tests also forces the dummy implementation of some native modules even for platforms where they cannot and will not be implemented ever (otherwise the build would fail).
- With PR #730, "exclude" becomes platform-dependent. There, e.g., the darwin-specific "exclude" list is empty. This removes the need for dummy native module implementations, as no modules will be build-tested in addition to the "always" and "include" list. However, it will also remove any require checks and will not parametrize the test driver either. (Same situation for TizenRT.)

I'm still not sure whether 
- "exclude" is a misnomer and it should simply have a different name (e.g., "build-test"), or
- it is a mix of two different concepts (e.g., keep the "exclude" name for checking that some modules are not transitively required and skipped when tested; and have a new separate "build-test" list as well to be used by `precommit.py`)

The answer perhaps depends on whether both features are really needed or not.

So, the question to be discussed is what to do with "exclude"? (Or is it good as it is?)

**Comment by glistening** [comment]
@akosthekiss I agree with you. We need to refine the build option ''exclude". We will start to discuss and follow up this issue after high priority task (due date next Friday) is done. Thank you for suggestion and thorough review about #730.

**Comment by hs0225** [comment]
The word "exclude" seems to be confusing. And I don't think exclude is necessary. However, we need a list of modules suppoted by platform. So I suggest the follwing.

Before,
```
"module": {
    "always": ["buffer", "console", "events", "fs", "module", "timers"],
    "include": ["assert", "dns", "http", "net", "stream", "testdriver"],
    "exclude": {
      "all": [],
      "linux": ["adc", "ble", "dgram", "gpio", "i2c", "pwm", "spi", "uart"],
      "nuttx": ["adc", "dgram", "gpio", "i2c", "pwm", "stm32f4dis", "uart"],
      "darwin": [],
      "tizenrt": ["gpio", "pwm"]
    }
  }
```

After,
```
supported_module: {
    "basic": ["buffer", "console", "events", "fs", "module", "timers", "assert", "dns", "http", "net", "stream", "testdriver"],
    "linux": ["adc", "ble", "dgram", "gpio", "i2c", "pwm", "spi", "uart"],
    "nuttx": ["adc", "dgram", "gpio", "i2c", "pwm", "stm32f4dis", "uart"],
    "darwin": [],
    "tizenrt": ["gpio", "pwm"]
}

include_module: ["buffer", "console", "events", "fs", "module", "timers", "assert", "dns", "http", "net", "stream", "testdriver"]
```

I want to hear a better idea.

**Comment by akosthekiss** [comment]
I'm not sure what the difference between "supported_module.any" and "build module" is. It seems that they list the same modules. Also, I'm not completely sure how the lists of built/included and tested modules are compiled. (If I'm right, the set of tested modules should always be a subset of the built/included modules, but in the suggested approach, "supported_module.any" + "supported_module.OS" >= "build_module".)

I can think of another approach, please see below:
```js
"module": {
  "include": ["buffer", "console", "events", "fs", "module", "timers", "assert", "dns", "http", "net", "stream", "testdriver"],
  "include-untested": [], // there might be a better name for this, perhaps (simply "untested"?) (this line could be omitted since missing keys should be treated as empty lists)
  "platform": { // there might be a better name for this, perhaps ("os"?)
    "linux": {
      // not adding key "include" because linux does not add anything that can be tested 
      "include-untested": ["adc", "ble", "dgram", "gpio", "i2c", "pwm", "spi", "uart"]
    },
    "nuttx": {
      "include-untested": ["adc", "dgram", "gpio", "i2c", "pwm", "stm32f4dis", "uart"]
    },
    // not adding key "darwin", because darwin has nothing to add at all
    // "darwin": { "include": [], "include-untested": [] }
    "tizenrt": {
      "include-untested": ["gpio", "pwm"]
    }
  }
}
```
It is a bit more verbose than suggested but allows a per-OS extension of both the build-only ("include-untested") and the fully-supported ("include") lists. (Json keys are the results of first thoughts only, may not be the best choices, as indicated by comments.)

**Comment by hs0225** [comment]
@akosthekiss The module list is required below:

1. Binary used by a developer (`build_module`), If the developer builds modules that do not exist in the supported module, it will return an error.
2. Test runner for modules included in binary (`build_module`)
3. On Travis, all implemented modules in each os and test runner (`supported_module.any`+ `supported_module.os`) ex) linux : any + linux

The `build_module` allows the developer to change the modules they want to include in the build. However, the `supported_module` cannot be modified. If we remove `build_module`, they should only build with the command `--iotjs-include-module` and `--iotjs-exclude-module` in order to include modules they want. 

refer to : 
https://github.com/Samsung/iotjs/wiki/Writing-New-Builtin-Module#writing-builtin-javascript-module
https://github.com/Samsung/iotjs/wiki/Build-for-x86-Linux#include-extended-module

**Comment by akosthekiss** [comment]
@hs0225 What confuses me is:
> The build_module allows the developer to change the modules they want to include in the build. However, the supported_module cannot be modified. If we remove build_module, they should only build with the command --iotjs-include-module and --iotjs-exclude-module in order to include modules they want.

This is a config file that can be replaced (build.py takes the `--config` option to use an alternative config file, different from the default). This means that there is no way to ensure that "`supported_module` cannot be modified" (it can be just as much modified as `build_module`, technically). In my opinion, the default config file should come with the defaults, and the command line options of build.py should allow the deviation from these defaults (which can be either the complete replacement of the config file via `--config` if a user has very different configuration needs, or the tweaking only of some of its settings, e.g, via `--iotjs-*-module`). So, I'd still advocate removing redundancies from the config file.

**Comment by glistening** [comment]
@akosthekiss Thank you for comment. `supported_module` is read-only property that the developers cannot and should not edit. It is a collection of the implemented and verified modules for each platform. The developers enables modules by selecting modules in `supported_module` (any + specific os) and including those in `build_module`. Are you suggesting separating `supported_module` from config file? IMHO, (at least for me) it is helpful to keep the supported modules list near to the `build_module` in same config file so that the developer can look at the list before he/she select, and copy and paste, it also prevent typo.

**Comment by akosthekiss** [comment]
To me, it's a bit strange to have something unmodifiable in a _config_ file. But so be it. But then I'm still not convinced about the need for `build_module`, exactly because of the syncing burden. (Typos are just one thing. Another thing is that someone will have to copy-paste from `supported_module ` to `build_module` any time the former changes. And yet another thing is that `build_module` is not differentiated by target platforms. So no matter what is supported on a target, the build will always use one single fixed set of modules by default.) Why not let the build script compile the list of built modules from `supported_module.any` + `supported_module.os` and just add "deltas" to that: either on the command line of the build script (`--iotjs-*-module`) or in the config file (by using some new `include,exclude_module` keys). (Is there any use case where `build_module` is completely different from `supported_module` and fixed to something else?)
