### ISSUE TITLE
Embedding packages in iotjs

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#76]
As described in  https://github.com/Samsung/iotjs/wiki/IoT.js-Package page, we may need to embed downloaded packages inside iotjs.  It can be done such as
1) download packages to some specific folder
2) give option to build script to enable embedding with the specific folder
3) convert package scripts to C code
4) require() finds packages in embed area

Application script should exist at the root of the specific folder.

**Comment by yichoi** [comment]
Closing. No plan to open ipm server now.
