### ISSUE TITLE
[Doc] Documentation for ReadableStream does not mention the event 'error'

### ISSUE THREAD

**Issue by akhilkedia** [Samsung/iotjs#760]
The documentation for `ReadableStream` [in the docs folder](https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-Stream.md#events) does not mention the `error` event, but the source code [here](https://github.com/Samsung/iotjs/blob/master/src/js/stream_readable.js) clearly shows the stream emitting that event.
Will be a simple edit of the docs to fix.

**Comment by yichoi** [comment]
#764 landed for this issue. I would like to listen your opinion

**Comment by akhilkedia** [comment]
This works. :)
I was compiling a list of current HTTP APIs supported by IoT.js and saw some missing, and so thought I should report those.
