### ISSUE TITLE
[Doc] Documentation for http.ClientRequest does not mention the events 'finish', 'close' and 'error'

### ISSUE THREAD

**Issue by akhilkedia** [Samsung/iotjs#766]
The documentation for [`http.ClientRequest`](https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-HTTP.md#events-1) in the `docs` folder does not mention the events `finish`, `close` or `error`, but the source code of `http_client` [here](https://github.com/Samsung/iotjs/blob/master/src/js/http_client.js) shows that it inherits from `http_outgoing`, which does emit those events [here](https://github.com/Samsung/iotjs/blob/master/src/js/http_outgoing.js).
Will be a simple edit of the docs to fix.

**Comment by yichoi** [comment]
Why don't you fix this issue by yourself ? :)
