### ISSUE TITLE
Measure memory usage

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/iotjs#774]
IMHO, we need to define how we'd like to measure memory usage of IoT.js. It would be nice to have tools for that. I see several different solutions here:

1) JS heap usage #754
Pros:
  * JerryScript provides this information, so it is easy to gather the data
  * Can be used on boards too
Cons:
  * JS heap is only a part of the actual memory usage
  * Won't work with other JS engines
2) Measure with Freya tool of Valgrind (https://github.com/szeged/Freya)
Pros:
  * Accurate and detailed information of memory usage
  * Configurable 
Cons:
  * A new dependency of this project
  * Cannot use on boards like STM32f4
3) Use `mallinfo` in IoT.js main (http://man7.org/linux/man-pages/man3/mallinfo.3.html)
Pros:
  * Easy to integrate
Cons:
  * Works only on Linux
  * Not sure how accurate is this solution, because JerryScript allocate the whole heap at start.
4) Use `getrusage` in IoT.js main (http://man7.org/linux/man-pages/man2/getrusage.2.html)
Pros/cons: same as `mallinfo` (3)

I'd like to hear your opinions. Is #754 a good start? What information and how should we print? E.g.: difference in percentage, geometric mean, highlight positive or negative results, console friendly output instead of MD format, etc.

**Comment by yichoi** [comment]
@LaszloLango +1 for #754. I will be a good start.

**Comment by yichoi** [comment]
Need to invent more convenient way to measure for NuttX. @rtakacs might have an idea for this, which mentioned at #754

**Comment by zherczeg** [comment]
On NUTTX we probably need to implement an infrastructure such as memstats. Probably we need to redirect malloc in some way.

**Comment by LaszloLango** [comment]
We might consider to use the [benchmark](https://github.com/nodejs/node/tree/master/benchmark) of NodeJS.

**Comment by yichoi** [comment]
https://samsung.github.io/iotjs-test-results/#
