### ISSUE TITLE
STM / nuttx installation branch breaks on various steps

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [Samsung/iotjs#777]
I have tried to compile for nuttx on OS X and linux now, but both branches seem to be broken in the tutorials. E.g. on OS X some steps are missing / wrong / not complete, but eventually some compilation with nuttx will fail.

On Linux somehting woth kconfig seems to be wrong.

Do you by chance have a comprehensive walkthrough? Can you include deployment to a device into the test suite?

**Comment by yichoi** [comment]
@hs0225 @rtakacs ?

**Comment by hs0225** [comment]
Our wiki page has not been updated yet. Please refer to [here](https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-NuttX.md). 
Could you tell me in detail which step failed on OS X and Linux?
Please use `kconfig-frontends-3.9.0.0` tag in kconfig.
The simplest way to run a test suite on a device is to copy it directly to the sd card.

**Comment by yichoi** [comment]
@eljefedelrodeodeljefe do you need further help or suggestion ?

**Comment by daeyeon** [comment]
The broken links has been fixed. https://github.com/Samsung/iotjs/wiki/Getting-Started
