### ISSUE TITLE
Unit Tests for release 1.0

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#853]
This task is not for migrating Node.js tests as many as possible, but for bugfixing.

1) Find tests, which test 1 feature what IoT.js should support.
2) If fails, then fix it, and migrate the test

Common Checklists
---
- For the adopted tests, put the Samsung license and Node.js one in order, and update the year on Samsung's one with 2017.

:books: Please update this section once you find any.

Group A
---

- [x] Net
- [x] HTTP
- [x] File-System

Group B
---

- [x] Timers

**Comment by yichoi** [comment]
Need to report Unit Test Coverage

**Comment by daeyeon** [comment]
For release 1.0, we investigated `http`, `http`, `fs`, and `timers` which seem high priority, and adopted some of them with bug fixes. The items confirmed and left were reported. 

This task turns out quite big to finish up for 1.0 release schedule. So I think we need to close this for now and divide them smaller and make them 1.x tasks.
