### ISSUE TITLE
Some known issues for Release 1.0

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#854]
**Infra**
- [x] Add daily benchmark (memory usage and binary footprint size) for NuttX/STM32 and Linux/RPi (https://samsung.github.io/iotjs-test-results/)
- [x] Integrate license verification tool (https://goo.gl/SXMcbq)
---
**Defects**
- [x] Fix static analysis defects (https://scan.coverity.com/projects/samsung-iotjs)
- [x] Validating target supports on RPi/Linux and NuttX/STM32.
---
**Code Coverage**
- [x] Goal: Functions 100% (Public in JS only), Statement over 80% (checker: ./tools/measure_coverage.sh)

**Comment by yichoi** [comment]
Somwhat dupe with #932.
let's close together with the issues are resolved
