### ISSUE TITLE
Nominating Péter Gál (@galpeter) to become an IoT.js committer

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#856]
I would like to nominate Péter Gál to become a committer.

Here are patches:

- Typo fix in jerry.cmake file for JERRY_PORT_DEFAULT (#848)
- Fix build type parameter for js2c call (#827)
- Remove unused require calls from http server module (#826)
- Remove unused require calls from http common module (#825)
- Remove 'parser=this' constructs from http_common js module (#824) 
- Avoid creating anonymous functions in stream writable js module (#828)
- Merge setTimeout, setInterval, clearTimeout, clearInterval functions (#820)
- Remove code duplications in timers js module (#819)
- Inline SetModuleDirs in module.js (#809) 
- Fix include order for newer clang-format (#815)
- Remove self=this from module.js (#814)
- Move file system constants into it single usage place in fs.js (#813)
- Test case for the Event Emitter (#812)
- Avoid manual argument copy, use Array slice instead in events.js (#810)
- Do not create empty object for native js sources (#795) 
- Inline emitError into error prototype method (#794) 
- Inline emitReadable into its single call-site (#793)
- Detect supported modules when running the tests (#783) 
- Use built-in js methods to get module directory in SetModuleDirs (#782) 
- Replace concatdir usage with array concat in module.js (#781)
- Merge tryPath and statPath functions in module.js (#780)
- Use array for headers in http_common.js (#776) 
- Switch to MinSizeRel build type if we are doing Release build (#775)
- Rename test files to include module names (#749) 
- Fix JerryScript api header reference in dev docs (#763)
- Remove BUILDTYPE cmake argument from http-parser (#762)
- Refactor build system to be more CMake-friendly (#708) 
- Force string conversation when processing the magic strings (#700) 
- Module analyzer tool fix (#701)
- Rework the js module analyzer code part (#691) 
- Simplify HTTP parser methods (#678) 
- Remove duplicate tizen entires from build.config (#664) 
- Allow js2c to be invoked from cmdline (#663)
- Eliminate the macro generated jump methods (#640) 
- Improve the js2c script (#637) 
- Rework the build.py script (#632)
- Use print function in precommit.py (#634) 
- Module analyzer should not use greedy regexps (#611) 
- Replace process.JSONParse with JSON.parse (#607) 
- Remove obsolete merge.py tool (#605) 
- Improve check_tidy script (#603)
- Improve build script Python 3.x compatibility (#595)

**Comment by LaszloLango** [comment]
+1

**Comment by yichoi** [comment]
+1

**Comment by hs0225** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by daeyeon** [comment]
+1

**Comment by chokobole** [comment]
+1

**Comment by jerry-fossa** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by yichoi** [comment]
Congratulations! I've added him to [here](https://github.com/Samsung/iotjs/wiki/Assigned-people)
