### ISSUE TITLE
[Doc] Getting Started documentation Optimization Tips link 404ing

### ISSUE THREAD

**Issue by minessis** [Samsung/iotjs#858]
The link to [Optimization Tips](https://github.com/Samsung/iotjs/blob/master/devs/Optimization-Tips)  **just above** [this point](https://github.com/Samsung/iotjs/wiki/Getting-Started#for-developers) in the Getting Started documentation, is broken/missing.

**Comment by LaszloLango** [comment]
@minessis you can find the latest documentation of IoT.js under the docs folder. I think the wiki pages are out of date. Here is what you are looking for: https://github.com/Samsung/iotjs/blob/master/docs/devs/Optimization-Tips.md

**Comment by daeyeon** [comment]
The link has been fixed. https://github.com/Samsung/iotjs/wiki/Optimization-Tips
