### ISSUE TITLE
[Question] Is it intentional to have travis build all modules for all platforms?

### ISSUE THREAD

**Issue by akhilkedia** [Samsung/iotjs#866]
When travis checks iotjs, `tools/precommit.py` intentionally includes all excluded modules from `build.config` for that platform in the build as well, and excluded modules is empty.
Is this intentional? If yes, for any module to be merged into master, it is necessary that it must atleast build for all platforms?

**Comment by daeyeon** [comment]
Yes, that's intended, but it doesn't mean that every module in master should be built for all the platforms. Assuming a module supporting `nuttx` only, you can put it into `module/exclude/nuttx`. If it supports all platforms, then use `module/exclude/all`.

The names such as `exclude` and `include` may confuse you as issued in #750. To make them clear to everyone, each needs to be renamed.

**Comment by akhilkedia** [comment]
@daeyeon It works, thanks! :)
