### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#873]
1) Ensuring that it precisely describes API interface and its parameter conditions.
2) Applying the most of Node.js format (e.g, title, subtitle, leveling rules, and so on) except the following cases.
  - Place 'Platform Support' section at the beginning.
  - Use the current format for callback arguments
3) Improving lacks and faults of the documents.

---
Common Checklists
---
1) For primitive types, start with lowercase. e.g) `{String}` should be `{string}`. Its criteria is the form of Node.js.
2) Use single quotes for contents and samples.
3) Remove TOC
4) For callback arguments, follow the below example.

```
* `someCallback` {Function}
  * `arg1` {integer}
  * `arg2` {Object}
```
5) Remove the section title, `constructor`, and write it simply like below.
```
new Buffer(array)
```
6) Remove all the section titles such as Class Methods, Prototype Function, Module Functions/Properties, Properties, Event, and so on.
```
## Class Methods <--- should be deleted.
### dgram.createSocket(options[, callback]) <-- keep the three hashmarks
```
7) Use the below format like Node.js

```
Buffer.from(string,[ encoding]) // for Class Method
buf.copy(...) // for Prototype Function or Module Function
```

8) In case of Class and Event, use the prefix as below, but not for others like Class Method.
```
Class: http.ClientRequest // Ok
Event: 'abort' // Ok 

Class Method: Buffer.alloc // Bad
```

:books: Please update this section once you find any.

---
Group A
---

- [x] Net
- [x] HTTP    
- [x] DGRAM
- [x] File-System
- [x] Buffer
- [x] DNS

Group B
---

- [x] Assert
- [x] Events
- [x] Module
- [x] Process
- [x] Stream
- [x] Timers

Group C
---

- [x] ADC
- [x] BLE
- [x] GPIO    
- [x] I2C
- [x] PWM
- [x] SPI
- [x] UART

**Comment by zherczeg** [comment]
I would like to work on the DGRAM module (testing + documentation).

**Comment by LaszloLango** [comment]
I'd kike to work on the HTTP module.

**Comment by galpeter** [comment]
I'll work on the dns module.

**Comment by bzsolt** [comment]
I'll work on the **fs** module.

**Comment by glistening** [comment]
@daeyeon, @zherczeg, @LaszloLango, @galpeter, @bzsolt 

I found some inconsistency between the each module documentation:

1. "Prototype Function" or "Class Method"
Some modules (e.g. `HTTP`, `NET`) use the term `Prototype Function`, other (e.g., `Buffer`) uses `Class Method`.

2. Nested Class
`File System` starts the nested class from level 2, and doesn't use "Class Method" for class's method. 
`Net` start the nested class from level 1, and uses "Prototype Functions" for nested class. As a result, different TOC will generated, although the class method nodes (`stats.isDirectory` and `server.close`) for Nested Class are in same 3rd level.

3. Constructor
Some modules explicitly shows some method is `Constructor` , and others don't use `constructor`

I'd like to get your opinions what style we'll use. Here is my opinion.

For item 1, I prefer "Class Method" since more modules use this style. But I also like to remove the level at all. Don't use aggregation level.

For 2, anything work for me. But I want to avoid too depth level for multi-level nested class.

For 3, Does it provide valuable information to API users? If not, I want to remove `Constructor` since it makes work easy.

**Comment by daeyeon** [comment]
@glistening Thanks for sharing your concerns.

1. `Prototype Function` is a term we've used so far. I expect every document in progress use `Class Method`.

2. We can apply the leveling rule of Node.js format except `Platform Support`. It's a section we only have and now intentionally uses level 3. That's because it doesn't represent each document itself although it's placed at the beginning of every docs.

3. It depends on modules. If there is a factory method like `http.request()` to create `http.ClientRequest` object, then a description for its constructor seems not needed. Whereas 'Buffer' object is directly created, so a description for it is needed.

**Comment by zherczeg** [comment]
1) I agree. It seems grouping was introduced only in IoT.js.
2) For buffer these levels are used:
```
# Buffer
## Class: Buffer
### new Buffer(arrayBuffer[, byteOffset [, length]])
```
Ref: https://github.com/nodejs/node/blob/master/doc/api/buffer.md
Similar in dgram:
https://raw.githubusercontent.com/nodejs/node/master/doc/api/dgram.md
```
# UDP / Datagram Sockets
## Class: dgram.Socket
### Event: 'message'
### socket.bind(options[, callback])
```

**Comment by zherczeg** [comment]
There is one more question: callback argument. Node.js help does not list them, only explains them in the text. It was listed before and I kept it, because I think it is a good idea. This is the format I used

```
* `someCallback` {Function}
** `arg1` {integer}
** `arg2` {Object}
```

Shall we use this or copy the Node.js variant?

**Comment by robertsipka** [comment]
@zherczeg : I think your suggested format is better for callback arguments.

**Comment by LaszloLango** [comment]
1. I agree too. We can remove it.
2. I think 3 levels should be enough for everything.

@zherczeg I like your suggestion on the callback functions.

**Comment by glistening** [comment]
"Prototype function" and "Class method" are different. I am sorry for making you confused.

`Prototype function` is like instance method, and generally documented with lowercase names like **buf.copy**. On the other hand, `Class method` is like static member function, and describes with first letter uppercase, full class name like **Buffer.from**. 

So, here is new questions that will replace older 1

1-1. Will we put the grouping level (like `Class Method` and `Prototype Function`) or not?

1-2.. Will we specify the kind of method? or use upper/lowercase implicit rule?

```
Class Method: Buffer.from(string[, encoding])

Prototype Function:buf.copy(...)
```

Or
```
Buffer.from(string,[ encoding])

buf.copy(...)
```

**Comment by zherczeg** [comment]
Sorry, should be like this:
```
* `someCallback` {Function}
  * `arg1` {integer}
  * `arg2` {Object}
```

**Comment by daeyeon** [comment]
@zherczeg I also think that your one is better. Let's use it.

**Comment by glistening** [comment]
Here is summary till now.

**1-1**, **3** Remove grouping level. (`Prototype function`, `Class method` and `Constructor` level)
**2**. Use node.js form for nested class.
For callback arguments, use @zherczeg 's suggestion.

Now, **1-2** remains.

**Comment by zherczeg** [comment]
@glistening Could you give an example like mine above?

**Comment by glistening** [comment]
@zherczeg Here is updated example from above comment:

### Class Method: Buffer.from(string[, encoding])

### Prototype Function: buf.copy(...)

Or

### Buffer.from(string,[ encoding])

### buf.copy(...)


Please notice that the prefix "Class Method:" and "Prototype Function:" in former. For latter, it does not contains the prefixes.

**Comment by zherczeg** [comment]
I prefer the latter. Class Method is pretty obvious without explicitly saying it.

**Comment by LaszloLango** [comment]
Should we add test for every event and function even if they are trivial? Could you check #884 is detailed enough? (Recently updated)

**Comment by daeyeon** [comment]
Regarding Class Method, it seems better to follow the below rule that is applied to others.
```
{section-type}: {title}
```
Examples:
```
Class: http.ClientRequest
Class Method: http.ClientRequest
Class Property: Buffer.poolSize
Event: 'abort'
```

**Comment by daeyeon** [comment]
Let me summarize the current majority opinion.

1. Remove all grouping levels such as Prototype Function, Module Functions/Properties, Properties, Event, and so on.
2. Use Node.js format according to many preferences.

```
Buffer.from(string,[ encoding]) // for Class Method
buf.copy(...) // for Prototype Function
```

In case of Class and Event, use the prefix as below, but not for others like Class Method.
```
Class: http.ClientRequest // Ok
Event: 'abort' // Ok 

Class Method: Buffer.alloc // Not ok
```

Sorry for any confusion caused.

**Comment by zherczeg** [comment]
Am I understand correctly that:
```
## Class Methods
### dgram.createSocket(options[, callback])
```
should be changed to
```
## dgram.createSocket(options[, callback])
```
So the "Class Methods" group should be deleted, and one hashmark before the function?

For me the font size of two hashmarks is big. Or shall we keep the three hashmarks, just delete the group?

**Comment by daeyeon** [comment]
@zherczeg In the example, `## Class Methods` should be removed and we can keep ###.

**Comment by LaszloLango** [comment]
Question: what is the correct style for array parameters? I think `{Array}` does not say anything about the type of the array elements. Based on the reviews on #907 I think @zherczeg agrees. In the mentioned PR I wrote `{[string]}`, so the square brackets refers to it is an array, but it can confuse someone that it is optional. My other thought was the following form: `{Array of string}`. What do you think? Any other idea? Is there any good example in the existing API docs that should be followed?

**Comment by zherczeg** [comment]
It seemed to me that they explain the items, the type is simply {Array}. They mostly focus on textual explanation in Node.js. (Questionably strategy, but they do it).

**Comment by zherczeg** [comment]
E.g. listing the callback arguments is our extension, in Node.js they simply {Function}.

**Comment by daeyeon** [comment]
@LaszloLango Thanks for pointing it out. How about `{Array.<string>}` ?

**Comment by zherczeg** [comment]
I would `{Array[string]}` or `{Array[{string}]}` This way we could use the pipe to add more types:

`{Array[string|null|undefined]}`

**Comment by zherczeg** [comment]
The latter is a bit stricter type `{Array{string}}` could go as well, but looks a bit strange for me.

**Comment by LaszloLango** [comment]
Both `{Array.<string|null>}` and `{Array[string|null]}` are good to me.

**Comment by daeyeon** [comment]
As you already know, `[]` could conflict with the meaning of optional. `{Array.<MyClass>}` is used in jsdoc. Please find `Arrays and objects` in http://usejsdoc.org/tags-type.html. Others may already be familiar with it. :-)
