### ISSUE TITLE
I2C API has mismatched abstractions

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#882]
I2CBUS represents in fact i2c device, as it has device address embedded into it.
Bus should accept complete transactions (address, r/w, payload) or oerations (i.e.: enumeration), while device should just have the address set explicitly during construction (and non-mutable).

The example (https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-I2C.md):

```
var I2C = require('i2c');
var i2c = new I2C();
var i2c_bus = i2c.open({device: '/dev/i2c-1', address: 0x23}, function(err) { ...});
```
i2c_bus represents a device of address 0x23, not the bus.

**Comment by hs0225** [comment]
It can be regarded as a representative object of an address, but also an object of a bus. The above variable is a created by the app developer. If the developer only uses '0x23' address on the bus, he or she can name the variable names as above.
