### ISSUE TITLE
Inconsistent datatypes in i2c configuration

### ISSUE THREAD

**Issue by tadziopazur** [Samsung/iotjs#883]
Excerpt from i2c API (https://github.com/Samsung/iotjs/blob/master/docs/api/IoT.js-API-I2C.md): 
```
i2c.open(configuration[, callback])

    configuration <Object>, configuration for open I2CBus
        device <String(linux)|Number(nuttx)>, device path
        address <Number>
    callback <Function(err: Error)>
    Returns: <I2CBus>
```

This is inconsistent and IMO needs to change. Application should not have to explicitly depend, much less check for the type of OS to access hardware resources.

There are some ideas how to achieve the uniformity goal if there is any need for them.

**Comment by hs0225** [comment]
@tadziopazur Since there are no more comments you think, I'll close the issue. Please reopen if necessary. If the unique features of the platform are integrated force, but rather can be confusing for developers.
