### ISSUE TITLE
Implement native JS(src/js/*.js) modules as c builtin code 

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/iotjs#93]
We have to discuss the following topics. 

1. Benifit
 * size
 * performance

2. Feasibility

**Comment by yichoi** [comment]
Closing.

C code will be harder to read, write, and maintain, etc. It can decrease development productivity, especially for current IoT.js whose [milestone 1](https://github.com/Samsung/iotjs/milestone/1) has not been finished yet. And it can be a bigger problem for developers who are familliar with node.js and v8 APIs, but not IoT.js and JerryScript APIs. They may even want to refer to existing codes when their new module implemetation, but it will be harder to do if everything is written in C.

On the other hand, it is not straightforward how much benefit we can achieve. For example, when reading a named property of JS object (simple `obj.prop`), to perfectly describe the behavior of JS equivalence in C, we should execute complex operations like: catch and throw proper error when property getter throws, sometimes check if property exists before actually reading it, etc.

So I think it's better to open a new issue when a specific module really needs a re-implementation. (like PR #393)
