### ISSUE TITLE
Timers module error handling

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/iotjs#933]
There are some differences in error handling of Timers module between IoT.js and NodeJS. `iotjs/test/run_pass/test_timers_error.js` tests that every wrong argument must throw an exception, but NodeJS does not throw in some cases. The fault tolerance is different. `nodejs/test/parallel/test-timers-clear-null-does-not-throw-error.js` tests that `clear` functions must not throw exception on null/undefined parameters. My question is that which one should be followed? Is it OK to modify IoT.js tests to adapt to the NodeJS behavior?

**Comment by yichoi** [comment]
In spite that we do not guarantee the compatibility with Node.js, It will be helpful to have same behavior with Node.js since the developers tend to expect the result what he/she have done before.

**Comment by pmarcinkiew** [comment]
In my opinion JS should to be easy to use so we should ignore invalid parameters and not throw. It should work similar to Node.jS and web browser. There is no throw for any of this test cases in Firefox and we throw for all of them. It is not what JS developer will expect.

**Comment by hs0225** [comment]
#946 was landed.
