### ISSUE TITLE
Tizen IoT.js for Raspberry Pi 3

### ISSUE THREAD

**Issue by amistewicz** [Samsung/iotjs#966]
http://download.tizen.org/snapshots/tizen/unified/latest/images/standard/common-iot_core-2parts-armv7l-rpi3/

**Comment by pmarcinkiew** [comment]
Just to clarify, we will try to build IoT.js Tizen port for Raspberry Pi 3 using this image of Tizen.

**Comment by yichoi** [comment]
Ok

**Comment by amistewicz** [comment]
and tar with kernel and modules: http://download.tizen.org/snapshots/tizen/unified/latest/images/standard/common-boot-arm64-rpi3/

**Comment by amistewicz** [comment]
Fix for old sfdisk: https://github.com/tizen-artik/sdboot/commit/ecf5e0e601ac389072261d32e4bf674f24ec77f1

**Comment by sumin-lim** [comment]
Hello, For the RPI Tizen Porting, I share a guide from 
https://github.com/sumin-lim/iotjs_doc/blob/master/iotjs_RPI3_Tizen.md

**Comment by pmarcinkiew** [comment]
Can we close this issue?

**Comment by yichoi** [comment]
Is it done ? I would like add specific requirements of Tizen IoT Headless. @sumin-lim or @haesik

**Comment by sumin-lim** [comment]
I share the plan for Tizen specific req for Tizen IoT Headless

**Apply Tizen Appfw & Peripheral I/O on IoT.js**
1. Apply Tizen’s Peripheral I/O on Iot.js (SRPOL)
2. Setting
- Add tizen CMAKE_SYSTEM_NAME 
- Apply Tizen dlog
(for this setting, I'm preparing this,
https://github.com/Samsung/iotjs/compare/master...sumin-lim:tizen ) 

3. Apply AppFW 
- Apply Tizen’s appcore-agent  and dlog on console&debug
- Appcore will be added as new modules (gcontext, tizenappfw)
- In this step, libtuv some watchers will be unlocked (prepare & check handler)

Always welcome to dicuss about Tizen IoT.js as a runtime.

**Comment by daeyeon** [comment]
Closed. You can refer to the above comments to use IoT.js on Tizen IoT.
