### ISSUE TITLE
Unit Test Stalling after merging 97515d9

### ISSUE THREAD

**Issue by glistening** [Samsung/iotjs#972]
Currently, all CI tests are stalled. They are in yellow. I found that it is stalled after

```
>>>> node/parallel
PASS : test-assert.js
PASS : test-http-status-message.js
PASS : test-http-write-head.js
PASS : test-net-bind-twice.js
PASS : test-net-end-without-connect.js
```

It seems related to latest merged PR 97515d9.
When I revert it, unit tests finish well on my local machine.

**Comment by yichoi** [comment]
@LaszloLango Please investigate this more

**Comment by LaszloLango** [comment]
@bzsolt started the investigation yesterday before the merge. We'll check it. There are some conflict between the tests. IMHO the problem came from the JS test runner.

**Comment by glistening** [comment]
@LaszloLango I got some information from JS test runner author. JS test runner does not have much features. For example, it cannot stop alive task, it can only stop tests which is completed (no computing any more) and in idle waiting. All tests are required not to enter infinite computing. This limitation mostly comes from low end devices and OSes.
